### ISSUE TITLE
[LSP] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1000]
**Expected behavior**
Should be able to registerRunnerCapabilities successfully

**Actual behavior**
Getting the following error
```
initialized: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
runtime/debug.Stack(0xc420113740, 0x154b580, 0x18a1070)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/debug/stack.go:24 +0x79
github.com/getgauge/gauge/api/lang.recoverPanic(0xc420089f40)
	src/github.com/getgauge/gauge/api/lang/server.go:286 +0x57
panic(0x154b580, 0x18a1070)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/getgauge/gauge/api/lang.registerRunnerCapabilities(0x1878a80, 0xc42006dc80, 0x187a980, 0xc42006e3d8, 0x1, 0x100e256)
	src/github.com/getgauge/gauge/api/lang/capabilities.go:127 +0x15f
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0x18ca8a0, 0x187a980, 0xc42006e3d8, 0x1878a80, 0xc42006dc80, 0xc420089f40, 0x12b4fc2, 0xc42004e4d0, 0x70, 0x1609d38)
	src/github.com/getgauge/gauge/api/lang/server.go:84 +0x6f9
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0x18ca8a0, 0x187a980, 0xc42006e3d8, 0xc42006dc80, 0xc420089f40, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:71 +0xc3
github.com/getgauge/gauge/api/lang.(*LangHandler).(github.com/getgauge/gauge/api/lang.handle)-fm(0x187a980, 0xc42006e3d8, 0xc42006dc80, 0xc420089f40, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:62 +0x52
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc420450970, 0x187a980, 0xc42006e3d8, 0xc42006dc80, 0xc420089f40)
	src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x6f
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	src/github.com/getgauge/gauge/api/lang/server.go:66 +0x6b
```
**Observed on**
* [Ruby LSP Tests](https://build.getgauge.io/go/tab/build/detail/Ruby-LSP-Tests/149/specs/1/darwin)

**Comment by sguptatw** [comment]
This can be observed when I am working on a huge java project like https://github.com/sguptatw/gauge-java-performance-usages.git

**Steps to replicate**
> Work on the project for a minute gotoDefn of a step, open/close files
* Give an implementation to the unimplemented step `something here 4`
* Close all files
* Open `specs3/example1.spec`
> Getting the above error and the IDE crashes.

**Comment by Apoorva-GA** [comment]
Unable to reproduce the issue. Please let us know, if there are any other steps that we can fallow.

**Comment by sguptatw** [comment]
I got this error when I was editing the contents of a non-gauge file as well. By a non-gauge file here I mean a .txt file

Here are the lsp logs of when it occured
```
10:03:47.649 --> request #0: initialize: {"processId":980,"rootPath":"/gauge-lsp-tests","rootUri":"file:///gauge-lsp-tests","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"]}},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true},"implementation":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true}},"saveFiles":true},"trace":"off","workspaceFolders":[{"uri":"file:///gauge-lsp-tests","name":"gauge-lsp-tests"}]}
10:03:47.649 <-- result #0: initialize: {"capabilities":{"textDocumentSync":1,"completionProvider":{"resolveProvider":true,"triggerCharacters":["*","* ","\"","\u003c",":",","]},"definitionProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentFormattingProvider":true,"renameProvider":true}}
10:03:47.649 --> result #0: client/registerCapability: null
10:03:47.649 --> notif: initialized: {}
10:03:47.650 <-- request #0: client/registerCapability: {"registrations":[{"id":"gauge-fileWatcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/gauge-lsp-tests/**/*{.cpt,.spec,.md}","kind":5}]}}]}
10:03:47.650 --> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///gauge-lsp-tests/specifications/gotodefinition/goto%!a(MISSING)%!c(MISSING)oncept.spec","languageId":"gauge","version":88,"text":"Goto a concept\n==============\n* initialize project \"data/gotodefinition\"\n\nGo to the definition of a concept from the usage\n------------------------------------------------\ntags: actions_on_project_load\n* textDocument/didOpen for \"/$specs/concept_definition.spec\"\n* goto definition of step \"Concept2\" in \"/$specs/concept_definition.spec\" at \"4\" and \"4\" should give details \"$specs/gotodefinition/concept.json\"\n\nGo to the definition of a newly created concept from the usage\n------------------------------------------------\ntags: actions_on_project_load\n* textDocument/didOpen for \"concepts/concept.cpt\"\n* edit content of file from \"concepts/addConcept.txt\" to \"concepts/concept.cpt\" and save\n* textDocument/didOpen for \"/$specs/concept_definition.spec\"\n* edit content of file from \"/$specs/concept_definition.txt\" to \"/$specs/concept_definition.spec\" and save\n* goto definition of step \"Concept2\" in \"/$specs/concept_definition.spec\" at \"4\" and \"4\" should give details \"$specs/gotodefinition/concept.json\"\n\n___\n* close the project"}}
10:03:47.650 --> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///gauge-lsp-tests/data/gotodefinition/specifications/concept_definition.spec","languageId":"gauge","version":1,"text":"Go to definition of concepts\n============================\nA Concept with definition\n-------------------------\n* Concept2\n\n\nA Concept without a definition\n-------------------------\n* undefined Concept\n* step1"}}
10:03:47.650 --> result #0: client/registerCapability: null
10:03:47.652 --> request #1: textDocument/codeAction: {"textDocument":{"uri":"file:///gauge-lsp-tests/data/gotodefinition/specifications/concept_definition.spec"},"range":{"start":{"line":0,"character":0},"end":{"line":10,"character":7}},"context":{"diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":10}},"message":"Step implementation not found","severity":1,"code":"step(\"Concept2\", async function() {\n\tthrow 'Unimplemented Step';\n});"},{"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":19}},"message":"Step implementation not found","severity":1,"code":"step(\"undefined Concept\", async function() {\n\tthrow 'Unimplemented Step';\n});"},{"range":{"start":{"line":10,"character":0},"end":{"line":10,"character":7}},"message":"Step implementation not found","severity":1,"code":"step(\"step1\", async function() {\n\tthrow 'Unimplemented Step';\n});"}]}}
10:03:47.653 <-- notif: window/logMessage: {"type":1,"message":"An error occurred. Refer lsp.log for more details."}
10:03:47.653 request #1: textDocument/codeAction: runtime error: invalid memory address or nil pointer dereference
goroutine 81 [running]:
runtime/debug.Stack(0xc0002373f0, 0x1667180, 0x1ca39f0)
    /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/getgauge/gauge/api/lang.recoverPanic(0xc0000c18b0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:291 +0x57
panic(0x1667180, 0x1ca39f0)
    /usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/getgauge/gauge/api/lang.createConceptInfo(0xc00022e000, 0x6f, 0x0, 0x0, 0x1, 0xc00024a080, 0x0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:90 +0x254
github.com/getgauge/gauge/api/lang.getSpecCodeAction(0xc00022e000, 0x6f, 0x0, 0x0, 0xa, 0x7, 0xc00048e160, 0x3, 0x4, 0x0, ...)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:52 +0x380
github.com/getgauge/gauge/api/lang.codeActions(0xc0000c18b0, 0x17418ea, 0x17, 0x1, 0xffffffffffffffff)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:44 +0x162
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0x1cd76a8, 0x17f3220, 0xc0000360d0, 0x17f0f20, 0xc0002b9da0, 0xc0000c18b0, 0x0, 0x0, 0x0, 0x0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:159 +0x1d3d
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0x1cd76a8, 0x17f3220, 0xc0000360d0, 0xc0002b9da0, 0xc0000c18b0, 0x0, 0x0, 0x0, 0x0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:72 +0xa6
github.com/getgauge/gauge/api/lang.(*LangHandler).handle-fm(0x17f3220, 0xc0000360d0, 0xc0002b9da0, 0xc0000c18b0, 0x0, 0x0, 0x0, 0x0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:63 +0x52
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc000368710, 0x17f3220, 0xc0000360d0, 0xc0002b9da0, 0xc0000c18b0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x6f
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:67 +0x6b
10:03:47.654 --> request #1: textDocument/codeAction: {"textDocument":{"uri":"file:///gauge-lsp-tests/data/gotodefinition/specifications/concept_definition.spec"},"range":{"start":{"line":0,"character":0},"end":{"line":10,"character":7}},"context":{"diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":10}},"message":"Step implementation not found","severity":1,"code":"step(\"Concept2\", async function() {\n\tthrow 'Unimplemented Step';\n});"},{"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":19}},"message":"Step implementation not found","severity":1,"code":"step(\"undefined Concept\", async function() {\n\tthrow 'Unimplemented Step';\n});"},{"range":{"start":{"line":10,"character":0},"end":{"line":10,"character":7}},"message":"Step implementation not found","severity":1,"code":"step(\"step1\", async function() {\n\tthrow 'Unimplemented Step';\n});"}]}}
10:03:47.656 <-- notif: window/logMessage: {"type":1,"message":"An error occurred. Refer lsp.log for more details."}
10:03:47.659 request #1: textDocument/codeAction: runtime error: invalid memory address or nil pointer dereference
goroutine 114 [running]:
runtime/debug.Stack(0xc0007353f0, 0x1667180, 0x1ca39f0)
    /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/getgauge/gauge/api/lang.recoverPanic(0xc000242d70)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:291 +0x57
panic(0x1667180, 0x1ca39f0)
    /usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/getgauge/gauge/api/lang.createConceptInfo(0xc0002fc070, 0x6f, 0x0, 0x0, 0x1, 0xc0002a4200, 0x0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:90 +0x254
github.com/getgauge/gauge/api/lang.getSpecCodeAction(0xc0002fc070, 0x6f, 0x0, 0x0, 0xa, 0x7, 0xc0005f0f20, 0x3, 0x4, 0x0, ...)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:52 +0x380
github.com/getgauge/gauge/api/lang.codeActions(0xc000242d70, 0x17418ea, 0x17, 0x1, 0xffffffffffffffff)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:44 +0x162
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0x1cd76a8, 0x17f3220, 0xc0000360d0, 0x17f0f20, 0xc00002f320, 0xc000242d70, 0x0, 0xc00025dee8, 0x12f8e02, 0xc00003f3e0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:159 +0x1d3d
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0x1cd76a8, 0x17f3220, 0xc0000360d0, 0xc00002f320, 0xc000242d70, 0x0, 0x0, 0x0, 0x0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:72 +0xa6
github.com/getgauge/gauge/api/lang.(*LangHandler).handle-fm(0x17f3220, 0xc0000360d0, 0xc00002f320, 0xc000242d70, 0x56, 0x0, 0x0, 0x0)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:63 +0x52
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc00043a2d0, 0x17f3220, 0xc0000360d0, 0xc00002f320, 0xc000242d70)
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x6f
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
    /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:67 +0x6b
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
