### ISSUE TITLE
maven plugin goal execute error after update java client to 0.6.8

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [getgauge/gauge#1081]
## environment
- gauge-maven-plugin (1.3.0)
- gauge (0.9.9)
- flash (0.0.1)
- html-report (4.0.4)
- java (0.6.8)
- screenshot (0.0.1)
- java (1.8.0_73)
- maven (3.3.9)
- idea (2018.1.4)
- java client (0.6.8)

## command
```shell
mvn test -X -DspecsDir=specs/xmjiancha -Denv="myenv"
```
## pom
```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>gauge_appium_android_maven</groupId>
  <artifactId>gauge_appium_android_maven</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>gauge_appium_android_maven</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.thoughtworks.gauge</groupId>
      <artifactId>gauge-java</artifactId>
      <version>0.6.8</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.appium</groupId>
      <artifactId>java-client</artifactId>
      <version>6.0.0-BETA5</version>
    </dependency>
    <dependency>
    <groupId>commons-dbutils</groupId>
    <artifactId>commons-dbutils</artifactId>
    <version>1.7</version>
  </dependency>
    <!-- https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
    <dependency>
      <groupId>org.xerial</groupId>
      <artifactId>sqlite-jdbc</artifactId>
      <version>3.21.0</version>
    </dependency>
    <dependency>
      <groupId>net.objecthunter</groupId>
      <artifactId>exp4j</artifactId>
      <version>0.4.8</version>
    </dependency>

    <dependency>
      <groupId>db.oracle.driver</groupId>
      <artifactId>ojdbc</artifactId>
      <version>6.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>com.thoughtworks.gauge.maven</groupId>
        <artifactId>gauge-maven-plugin</artifactId>
        <version>1.3.0</version>
        <executions>
          <execution>
            <phase>test</phase>
            <goals>
              <goal>execute</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
        <!-- see http://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.7.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.20.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```
## log
```log
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[DEBUG] Determined Maven Process ID 764
[DEBUG] boot classpath:  C:\Users\15512\.m2\repository\org\apache\maven\surefire\surefire-booter\2.20.1\surefire-booter-2.20.1.jar  C:\Users\15512\.m2\repository\org\apache\maven\surefire\surefire-api\2.20.1\surefire-api-2.20.1.jar  C:\Users\15512\.m2\repository\org\apache\maven\surefire\surefire-logger-api\2.20.1\surefire-logger-api-2.20.1.jar  C:\Users\15512\IdeaProjects\gauge_appium_android_maven\target\test-classes  C:\Users\15512\IdeaProjects\gauge_appium_android_maven\target\classes  C:\Users\15512\.m2\repository\com\thoughtworks\gauge\gauge-java\0.6.8\gauge-java-0.6.8.jar  C:\Users\15512\.m2\repository\org\assertj\assertj-core\3.10.0\assertj-core-3.10.0.jar  C:\Users\15512\.m2\repository\org\reflections\reflections\0.9.11\reflections-0.9.11.jar  C:\Users\15512\.m2\repository\org\javassist\javassist\3.21.0-GA\javassist-3.21.0-GA.jar  C:\Users\15512\.m2\repository\com\github\javaparser\javaparser-core\2.5.1\javaparser-core-2.5.1.jar  C:\Users\15512\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar  C:\Users\15512\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar  C:\Users\15512\.m2\repository\com\google\protobuf\protobuf-java\3.3.1\protobuf-java-3.3.1.jar  C:\Users\15512\.m2\repository\com\google\guava\guava\24.0-jre\guava-24.0-jre.jar  C:\Users\15512\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar  C:\Users\15512\.m2\repository\org\checkerframework\checker-compat-qual\2.0.0\checker-compat-qual-2.0.0.jar  C:\Users\15512\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.3\error_prone_annotations-2.1.3.jar  C:\Users\15512\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar  C:\Users\15512\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar  C:\Users\15512\.m2\repository\io\appium\java-client\6.0.0-BETA5\java-client-6.0.0-BETA5.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-java\3.11.0\selenium-java-3.11.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.11.0\selenium-chrome-driver-3.11.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.11.0\selenium-edge-driver-3.11.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.11.0\selenium-firefox-driver-3.11.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.11.0\selenium-ie-driver-3.11.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.11.0\selenium-opera-driver-3.11.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.11.0\selenium-remote-driver-3.11.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.11.0\selenium-safari-driver-3.11.0.jar  C:\Users\15512\.m2\repository\net\bytebuddy\byte-buddy\1.7.9\byte-buddy-1.7.9.jar  C:\Users\15512\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar  C:\Users\15512\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar  C:\Users\15512\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar  C:\Users\15512\.m2\repository\org\apache\httpcomponents\httpcore\4.4.6\httpcore-4.4.6.jar  C:\Users\15512\.m2\repository\com\squareup\okhttp3\okhttp\3.9.1\okhttp-3.9.1.jar  C:\Users\15512\.m2\repository\com\squareup\okio\okio\1.13.0\okio-1.13.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-support\3.11.0\selenium-support-3.11.0.jar  C:\Users\15512\.m2\repository\org\seleniumhq\selenium\selenium-api\3.11.0\selenium-api-3.11.0.jar  C:\Users\15512\.m2\repository\com\google\code\gson\gson\2.8.2\gson-2.8.2.jar  C:\Users\15512\.m2\repository\org\apache\httpcomponents\httpclient\4.5.5\httpclient-4.5.5.jar  C:\Users\15512\.m2\repository\cglib\cglib\3.2.6\cglib-3.2.6.jar  C:\Users\15512\.m2\repository\org\ow2\asm\asm\6.0\asm-6.0.jar  C:\Users\15512\.m2\repository\org\apache\ant\ant\1.9.6\ant-1.9.6.jar  C:\Users\15512\.m2\repository\org\apache\ant\ant-launcher\1.9.6\ant-launcher-1.9.6.jar  C:\Users\15512\.m2\repository\commons-validator\commons-validator\1.6\commons-validator-1.6.jar  C:\Users\15512\.m2\repository\commons-beanutils\commons-beanutils\1.9.2\commons-beanutils-1.9.2.jar  C:\Users\15512\.m2\repository\commons-digester\commons-digester\1.8.1\commons-digester-1.8.1.jar  C:\Users\15512\.m2\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar  C:\Users\15512\.m2\repository\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar  C:\Users\15512\.m2\repository\org\springframework\spring-context\5.0.3.RELEASE\spring-context-5.0.3.RELEASE.jar  C:\Users\15512\.m2\repository\org\springframework\spring-aop\5.0.3.RELEASE\spring-aop-5.0.3.RELEASE.jar  C:\Users\15512\.m2\repository\org\springframework\spring-beans\5.0.3.RELEASE\spring-beans-5.0.3.RELEASE.jar  C:\Users\15512\.m2\repository\org\springframework\spring-core\5.0.3.RELEASE\spring-core-5.0.3.RELEASE.jar  C:\Users\15512\.m2\repository\org\springframework\spring-jcl\5.0.3.RELEASE\spring-jcl-5.0.3.RELEASE.jar  C:\Users\15512\.m2\repository\org\springframework\spring-expression\5.0.3.RELEASE\spring-expression-5.0.3.RELEASE.jar  C:\Users\15512\.m2\repository\org\aspectj\aspectjweaver\1.8.13\aspectjweaver-1.8.13.jar  C:\Users\15512\.m2\repository\org\openpnp\opencv\3.2.0-1\opencv-3.2.0-1.jar  C:\Users\15512\.m2\repository\javax\websocket\javax.websocket-api\1.1\javax.websocket-api-1.1.jar  C:\Users\15512\.m2\repository\org\glassfish\tyrus\tyrus-client\1.1\tyrus-client-1.1.jar  C:\Users\15512\.m2\repository\org\glassfish\tyrus\tyrus-core\1.1\tyrus-core-1.1.jar  C:\Users\15512\.m2\repository\org\glassfish\tyrus\tyrus-spi\1.1\tyrus-spi-1.1.jar  C:\Users\15512\.m2\repository\org\glassfish\tyrus\tyrus-websocket-core\1.1\tyrus-websocket-core-1.1.jar  C:\Users\15512\.m2\repository\org\glassfish\tyrus\tyrus-container-grizzly\1.1\tyrus-container-grizzly-1.1.jar  C:\Users\15512\.m2\repository\org\glassfish\grizzly\grizzly-framework\2.3.3\grizzly-framework-2.3.3.jar  C:\Users\15512\.m2\repository\org\glassfish\grizzly\grizzly-http-server\2.3.3\grizzly-http-server-2.3.3.jar  C:\Users\15512\.m2\repository\org\glassfish\grizzly\grizzly-http\2.3.3\grizzly-http-2.3.3.jar  C:\Users\15512\.m2\repository\org\glassfish\grizzly\grizzly-rcm\2.3.3\grizzly-rcm-2.3.3.jar  C:\Users\15512\.m2\repository\commons-dbutils\commons-dbutils\1.7\commons-dbutils-1.7.jar  C:\Users\15512\.m2\repository\org\xerial\sqlite-jdbc\3.21.0\sqlite-jdbc-3.21.0.jar  C:\Users\15512\.m2\repository\net\objecthunter\exp4j\0.4.8\exp4j-0.4.8.jar  C:\Users\15512\.m2\repository\db\oracle\driver\ojdbc\6.0\ojdbc-6.0.jar  C:\Users\15512\.m2\repository\org\apache\maven\surefire\surefire-junit3\2.20.1\surefire-junit3-2.20.1.jar
[DEBUG] boot(compact) classpath:  surefire-booter-2.20.1.jar  surefire-api-2.20.1.jar  surefire-logger-api-2.20.1.jar  test-classes  classes  gauge-java-0.6.8.jar  assertj-core-3.10.0.jar  reflections-0.9.11.jar  javassist-3.21.0-GA.jar  javaparser-core-2.5.1.jar  commons-io-2.5.jar  commons-lang-2.6.jar  protobuf-java-3.3.1.jar  guava-24.0-jre.jar  jsr305-1.3.9.jar  checker-compat-qual-2.0.0.jar  error_prone_annotations-2.1.3.jar  j2objc-annotations-1.1.jar  animal-sniffer-annotations-1.14.jar  java-client-6.0.0-BETA5.jar  selenium-java-3.11.0.jar  selenium-chrome-driver-3.11.0.jar  selenium-edge-driver-3.11.0.jar  selenium-firefox-driver-3.11.0.jar  selenium-ie-driver-3.11.0.jar  selenium-opera-driver-3.11.0.jar  selenium-remote-driver-3.11.0.jar  selenium-safari-driver-3.11.0.jar  byte-buddy-1.7.9.jar  commons-exec-1.3.jar  commons-codec-1.10.jar  commons-logging-1.2.jar  httpcore-4.4.6.jar  okhttp-3.9.1.jar  okio-1.13.0.jar  selenium-support-3.11.0.jar  selenium-api-3.11.0.jar  gson-2.8.2.jar  httpclient-4.5.5.jar  cglib-3.2.6.jar  asm-6.0.jar  ant-1.9.6.jar  ant-launcher-1.9.6.jar  commons-validator-1.6.jar  commons-beanutils-1.9.2.jar  commons-digester-1.8.1.jar  commons-collections-3.2.2.jar  commons-lang3-3.7.jar  spring-context-5.0.3.RELEASE.jar  spring-aop-5.0.3.RELEASE.jar  spring-beans-5.0.3.RELEASE.jar  spring-core-5.0.3.RELEASE.jar  spring-jcl-5.0.3.RELEASE.jar  spring-expression-5.0.3.RELEASE.jar  aspectjweaver-1.8.13.jar  opencv-3.2.0-1.jar  javax.websocket-api-1.1.jar  tyrus-client-1.1.jar  tyrus-core-1.1.jar  tyrus-spi-1.1.jar  tyrus-websocket-core-1.1.jar  tyrus-container-grizzly-1.1.jar  grizzly-framework-2.3.3.jar  grizzly-http-server-2.3.3.jar  grizzly-http-2.3.3.jar  grizzly-rcm-2.3.3.jar  commons-dbutils-1.7.jar  sqlite-jdbc-3.21.0.jar  exp4j-0.4.8.jar  ojdbc-6.0.jar  surefire-junit3-2.20.1.jar
[DEBUG] Forking command line: cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_73\jre\bin\java" -jar C:\Users\15512\AppData\Local\Temp\surefire124485614949327\surefirebooter3961467029114089451.jar C:\Users\15512\AppData\Local\Temp\surefire124485614949327 2018-06-12T20-09-53_532-jvmRun1 surefire3348786658478531962tmp surefire_08631050347634445446tmp"
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.555 s
[INFO] Finished at: 2018-06-12T20:09:54+08:00
[INFO] Final Memory: 14M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project gauge_appium_android_maven: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\15512\IdeaProjects\gauge_appium_android_maven\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] null
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] null
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:497)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project gauge_appium_android_maven: There are test failures.

Please refer to C:\Users\15512\IdeaProjects\gauge_appium_android_maven\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
There was an error in the forked process
null
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
null
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: There are test failures.

Please refer to C:\Users\15512\IdeaProjects\gauge_appium_android_maven\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
There was an error in the forked process
null
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
null
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

	at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:235)
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:112)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:354)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:984)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
null
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

## surefire report
```log
# Created on 2018-06-12T20:23:03.721
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.maven.surefire.junit.PojoTestSet.<init>(PojoTestSet.java:66)
	at org.apache.maven.surefire.junit.JUnit3Provider.createTestSet(JUnit3Provider.java:127)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: java.lang.NullPointerException
	at global.SuiteDataStoreHelp.getIntData(SuiteDataStoreHelp.java:15)
	at manager.TestContext.<clinit>(TestContext.java:21)
	... 12 more

```

**Comment by sguptatw** [comment]
@JohnHuahuaZhan the fix for this is available on version
```
Gauge version: 0.9.9.nightly-2018-06-01
Commit Hash: 812f26e
```

Gauge will be released soon.

**Comment by sguptatw** [comment]
Released. Available with version given below

```
Gauge version: 1.0.1.nightly-2018-06-19
Commit Hash: 583ef1d
```

gauge-maven-plugin version >= 1.3.3
