### ISSUE TITLE
write tcp 127.0.0.1:62729->127.0.0.1:62732: use of closed network connection

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [getgauge/gauge#1086]
## environment
- gauge-maven-plugin (1.3.3)
- gauge (0.9.9)
- flash (0.0.1)
- html-report (4.0.4)
- java (0.6.8)
- screenshot (0.0.1)
- java (1.8.0_73)
- maven (3.3.9)
- idea (2018.1.4)
- java client (0.6.8)
- MAC 10.13.5
## command
```shell
mvn gauge:execute -DspecsDir=specs/xmjiancha -Denv="myenv"
```
## pom
```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>gauge_appium_android_maven</groupId>
  <artifactId>gauge_appium_android_maven</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>gauge_appium_android_maven</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.thoughtworks.gauge</groupId>
      <artifactId>gauge-java</artifactId>
      <version>0.6.8</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.appium</groupId>
      <artifactId>java-client</artifactId>
      <version>6.0.0-BETA5</version>
    </dependency>
    <dependency>
    <groupId>commons-dbutils</groupId>
    <artifactId>commons-dbutils</artifactId>
    <version>1.7</version>
  </dependency>
    <!-- https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
    <dependency>
      <groupId>org.xerial</groupId>
      <artifactId>sqlite-jdbc</artifactId>
      <version>3.21.0</version>
    </dependency>
    <dependency>
      <groupId>net.objecthunter</groupId>
      <artifactId>exp4j</artifactId>
      <version>0.4.8</version>
    </dependency>

    <dependency>
      <groupId>db.oracle.driver</groupId>
      <artifactId>ojdbc</artifactId>
      <version>6.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>com.thoughtworks.gauge.maven</groupId>
        <artifactId>gauge-maven-plugin</artifactId>
        <version>1.3.3</version>
        <executions>
          <execution>
            <phase>test</phase>
            <goals>
              <goal>execute</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
        <!-- see http://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.7.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.20.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```
## log
```log
[INFO] Scanning for projects...
[INFO] 
[INFO] -------< gauge_appium_android_maven:gauge_appium_android_maven >--------
[INFO] Building gauge_appium_android_maven 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- gauge-maven-plugin:1.3.3:execute (default-cli) @ gauge_appium_android_maven ---
java.lang.NoClassDefFoundError: Could not initialize class manager.GlobalEnv
        at manager.DriverManager.androidDriver(DriverManager.java:75)
        at manager.DriverManager.driver(DriverManager.java:44)
        at data.screenshot.CustomScreenGrabber.takeScreenshot(CustomScreenGrabber.java:12)
        at com.thoughtworks.gauge.screenshot.ScreenshotFactory.takeScreenshot(ScreenshotFactory.java:58)
        at com.thoughtworks.gauge.screenshot.ScreenshotFactory.getScreenshotBytes(ScreenshotFactory.java:49)
        at com.thoughtworks.gauge.execution.MethodExecutor.createFailureExecResult(MethodExecutor.java:54)
        at com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:48)
        at com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.executeHook(HooksExecutor.java:100)
        at com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.execute(HooksExecutor.java:88)
        at com.thoughtworks.gauge.execution.HooksExecutor.execute(HooksExecutor.java:45)
        at com.thoughtworks.gauge.processor.MethodExecutionMessageProcessor.executeHooks(MethodExecutionMessageProcessor.java:65)
        at com.thoughtworks.gauge.processor.SuiteExecutionStartingProcessor.process(SuiteExecutionStartingProcessor.java:34)
        at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:92)
        at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:96)
        at com.thoughtworks.gauge.GaugeRuntime.lambda$connectSynchronously$1(GaugeRuntime.java:79)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: Could not initialize class manager.GlobalEnv

  Error Message: Connection closed [127.0.0.1:62732] cause: EOF
  Stacktrace: 
  

  Error Message: write tcp 127.0.0.1:62729->127.0.0.1:62732: use of closed network connection
  Stacktrace: 
  
Successfully generated html-report to => /Users/caihua/Documents/IdeaProject/gauge_appium_android_maven/reports/huaweiHonor9-8.0/html-report/2018-06-14 19.11.11/index.html
Specifications: 0 executed      0 passed        0 failed        0 skipped
Scenarios:      0 executed      0 passed        0 failed        0 skipped

Total time taken: 77ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.089 s
[INFO] Finished at: 2018-06-14T19:11:11+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.3.3:execute (default-cli) on project gauge_appium_android_maven: Gauge Specs execution failed. null: GaugeExecutionFailedException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

my project  failed to run with  ' use of closed network connection'

**Comment by JohnHuahuaZhan** [comment]
anyone could help me??
