### ISSUE TITLE
Getting an exception while working on specs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1103]
**Expected behavior**
Got an exception when I was debugging.
Another time when cut and paste the scenario into a different spec
```
11:50:48.710 request #1: textDocument/codeAction: runtime error: invalid memory address or nil pointer dereference
goroutine 81 [running]:
runtime/debug.Stack(0xc42037d3e0, 0x15d3540, 0x1a01b40)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/getgauge/gauge/api/lang.recoverPanic(0xc420564140)
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/api/lang/server.go:290 +0x57
panic(0x15d3540, 0x1a01b40)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/getgauge/gauge/api/lang.createConceptInfo(0xc420434000, 0x52, 0x2, 0x0, 0x1, 0xc4200480c0, 0x0)
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/api/lang/codeAction.go:90 +0x255
github.com/getgauge/gauge/api/lang.getSpecCodeAction(0xc420434000, 0x52, 0x2, 0x0, 0x6, 0x0, 0xc4202dc160, 0x2, 0x4, 0x0, ...)
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/api/lang/codeAction.go:52 +0x30b
github.com/getgauge/gauge/api/lang.codeActions(0xc420564140, 0x16a01f7, 0x17, 0x1, 0xffffffffffffffff)
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/api/lang/codeAction.go:44 +0x15a
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0x1a34590, 0x1714260, 0xc4200ce008, 0x1712060, 0xc4200dc540, 0xc420564140, 0xc4202c56e8, 0x12dade2, 0xc4201bbb00, 0x52)
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/api/lang/server.go:158 +0x1ceb
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0x1a34590, 0x1714260, 0xc4200ce008, 0xc4200dc540, 0xc420564140, 0x0, 0x0, 0x0, 0x0)
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/api/lang/server.go:72 +0xa6
github.com/getgauge/gauge/api/lang.(*LangHandler).(github.com/getgauge/gauge/api/lang.handle)-fm(0x1714260, 0xc4200ce008, 0xc4200dc540, 0xc420564140, 0x0, 0x0, 0x0, 0x0)
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/api/lang/server.go:63 +0x52
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc420080150, 0x1714260, 0xc4200ce008, 0xc4200dc540, 0xc420564140)
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x6f
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	/Users/sswaroop/work/go_wd/src/github.com/getgauge/gauge/api/lang/server.go:67 +0x6b
```
**Steps to replicate**
Intermittent issue

**Version**
```
Gauge version: 1.0.1.nightly-2018-06-27
Commit Hash: 0e3c1fc
```

**Comment by sguptatw** [comment]
Closing this issue as I did not face this for a while now.
