### ISSUE TITLE
Getting Step implementation not found and an exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1148]
**Expected behavior**
Should get step implementation not found only for steps that do not have an implementation

**Actual behavior**
Getting step implementation not found on an implemented step

**Steps to replicate**
* Create a gauge-js project.
* Create a specification
```
Specification name
===============
tags: no-lang-runner

* Vowels in English language are "aeiou".
Display links to run Spec and Scenario in a Specification
---------------------------------------------------------
* The word "gauge" has "3" vowels.
* The word "gauge" has "3" vowels.

Display links to run Specification with test cases in a Specification
-----------------------------------------------------------------------
* The word "gauge" has "3" vowels.
* The word "gauge" has "3" vowels.
```
> This gives wrong diagnostics and crashes the gauge server with exception
```
11:42:35.496 request #2: textDocument/codeAction: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
runtime/debug.Stack(0xc04243f400, 0xa36fa0, 0xecb880)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xae
github.com/getgauge/gauge/api/lang.recoverPanic(0xc0420b60f0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:291 +0x5e
panic(0xa36fa0, 0xecb880)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x237
github.com/getgauge/gauge/api/lang.createConceptInfo(0xc042470040, 0x39, 0x0, 0x0, 0x1, 0xc042298040, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:90 +0x25c
github.com/getgauge/gauge/api/lang.getSpecCodeAction(0xc042470040, 0x39, 0x0, 0x0, 0xd, 0x22, 0xc0421a6000, 0x1, 0x4, 0x0, ...)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:52 +0x312
github.com/getgauge/gauge/api/lang.codeActions(0xc0420b60f0, 0xb180bc, 0x17, 0x1, 0xffffffffffffffff)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:44 +0x161
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0xefcfc8, 0xb90dc0, 0xc04207e120, 0xb8ec80, 0xc042224300, 0xc0420b60f0, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:159 +0x1d2a
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0xefcfc8, 0xb90dc0, 0xc04207e120, 0xc042224300, 0xc0420b60f0, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:72 +0xad
github.com/getgauge/gauge/api/lang.(*LangHandler).(github.com/getgauge/gauge/api/lang.handle)-fm(0xb90dc0, 0xc04207e120, 0xc042224300, 0xc0420b60f0, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:63 +0x59
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc04245c7b0, 0xb90dc0, 0xc04207e120, 0xc042224300, 0xc0420b60f0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x76
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:67 +0x72
```

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-08
Commit Hash: 5652ab5

Plugins
-------
js (2.3.2.nightly-2018-08-08)
```
Blocks - https://github.com/getgauge/gauge/issues/265

**Comment by sriv** [comment]
This

```
* Vowels in English language are "aeiou". Display links to run Spec and Scenario in a Specification ---------------------------------------------------------
```

Has a conflict, is the second line part of a step or scenario? Which should get precedence?

Step can now span across lines.

**Comment by ajoecker** [comment]
in my eyes, the scenario should have precedence, otherwise it seems to be an endless thing, right ?

```
* Vowels in English language are "aeiou".
Display links to run Spec and Scenario in a Specification
another line
and another line
---------------------------------------------------------
* The word "gauge" has "3" vowels.
* The word "gauge" has "3" vowels.
```
and forcing a new line between them is not a viable option in my eyes

**Comment by sriv** [comment]
@ajoecker - if we stick to markdown specs (even Github Flavoured Markdown) this is how your example is rendered in Github:

![screenshot](https://user-images.githubusercontent.com/389148/43957364-34213eb6-9cc5-11e8-83f4-0fe5827a1cbe.png)

With Gauge we believe an unordered list would be a step.

**Comment by sriv** [comment]
cannot replicate the exception stacktrace. with gauge nightly (08-08-18)

**Comment by sguptatw** [comment]
Working as expected. 
```
Gauge version: 1.0.1.nightly-2018-08-08
Commit Hash: 5652ab5

Plugins
-------
js (2.3.2.nightly-2018-08-08)
```
