### ISSUE TITLE
Test fails with Error `Error Message: Connection closed [127.0.0.1:50992] cause: EOF`

### ISSUE THREAD

**Issue by rajiesh** [getgauge/gauge#1158]
### Expected behavior
Test should complete successfully

### Actual behavior
Test fails intermittently with exception as `Error Message: Connection closed [127.0.0.1:50992] cause: EOF`

Tests are run with command `gauge --tags 'regression' -n 15 -g 1 run specs`

### Steps to reproduce
On build.gocd.org environment functional tests run using gauge-ruby plugin are failing intermittently, not sure if its plugin or gauge core issue. Not observed it so far in the gauge-java tests that we have. However will update this issue if see similar failure on gauge-java tests.  

here is the gauge log during failure,

```
23:45:44.651 Compatible version of plugin ruby not found. Installing plugin ruby...
23:45:44.651 Gathering metadata for ruby
23:45:44.863 Downloading gauge-ruby-0.5.1-linux.x86_64.zip
23:45:46.659 Installing plugin ruby 0.5.1
23:45:46.664 Successfully installed plugin 'ruby'.
23:45:46.664 Compatible version of plugin html-report not found. Installing plugin html-report...
23:45:46.664 Gathering metadata for html-report
23:45:46.712 Downloading html-report-4.0.5-linux.x86_64.zip
23:45:47.994 Installing plugin html-report 4.0.5
23:45:48.008 Successfully installed plugin 'html-report'.
23:45:48.008 Installing required plugins.
23:45:48.008 Installing plugin 'screenshot'
23:45:48.008 Gathering metadata for screenshot
23:45:48.032 Downloading screenshot-0.0.1-linux.x86_64.zip
23:45:48.056 Checking updates...
23:45:48.484 Installing plugin screenshot 0.0.1
23:45:48.487 Successfully installed plugin 'screenshot'.
23:45:48.775 Using the -g flag will make the distribution strategy 'eager'. The --strategy setting will be overridden.
23:45:48.775 The following specifications satisfy filter criteria:
23:45:48.775 specs/BasicDependencyWalkInPipelineCompare.spec
23:45:48.775 specs/ConfigRepoEnvironmentMerge.spec
23:45:48.775 specs/EditExistingEnvironment.spec
23:45:48.775 specs/OverrideEnvironmentVariableDuringTrigger.spec
23:45:48.775 specs/PipelineLockingBehavior.spec
23:46:39.815 # BasicDependencyWalkInPipelineCompare
23:46:39.816 ## BasicDependencyWalkInPipelineCompare
23:46:39.816 * Basic Configuration - setup
23:46:40.097 * Using pipeline "up, down, child-of-down" - setup
23:46:40.670 * With "1" live agents - setup
23:46:57.700 * Capture go state "BasicDependencyWalkInPipelineCompare" - setup

####### More steps here........


23:53:28.407 Failed Step: Verify pipeline "pipeline-unlock-onComplete" is locked and not schedulable - Using api
23:53:28.407 Error Message: Connection closed [127.0.0.1:50992] cause: EOF
23:53:28.407 Specification: specs/PipelineLockingBehavior.spec:19
23:53:28.407 Stacktrace: 
23:53:28.407 Error Message: write tcp 127.0.0.1:35415->127.0.0.1:50992: use of closed network connection
23:53:28.407 Stacktrace: 
23:53:28.407 * Capture go state "PipelineLockingBehavior" - teardown
23:53:28.407 Error Message: write tcp 127.0.0.1:35415->127.0.0.1:50992: use of closed network connection
23:53:28.407 Stacktrace: 
23:53:28.407 Error Message: write tcp 127.0.0.1:35415->127.0.0.1:50992: use of closed network connection
23:53:28.407 Stacktrace: 
23:53:28.407 Error Message: write tcp 127.0.0.1:35415->127.0.0.1:50992: use of closed network connection
23:53:28.407 Stacktrace: 
23:53:28.407 Error Message: write tcp 127.0.0.1:35415->127.0.0.1:50992: use of closed network connection
23:53:28.407 Stacktrace: 
23:53:28.407 Error Message: write tcp 127.0.0.1:35415->127.0.0.1:50992: use of closed network connection
23:53:28.407 Stacktrace: 
23:53:28.508 Plugin [Html Report] with pid [10922] has exited
23:53:28.508 Specifications:	5 executed	4 passed	1 failed	0 skipped
23:53:28.508 Scenarios:	5 executed	4 passed	1 failed	0 skipped
23:53:28.508 
Total time taken: 7m38.719s
```

More logs from the console

```
/go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/method_cache.rb:79:in `recoverable?': undefined method `[]' for nil:NilClass (NoMethodError)
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/processors/execute_step_request_processor.rb:32:in `rescue in process_execute_step_request'
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/processors/execute_step_request_processor.rb:29:in `process_execute_step_request'
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/message_processor.rb:58:in `call'
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/message_processor.rb:58:in `process_message'
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:56:in `handle_message'
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:41:in `dispatch_messages'
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:85:in `<module:Runtime>'
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:33:in `<module:Gauge>'
	from /go/pipelines/regression-SPAs/vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:31:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
        Error Message: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
        Stacktrace: 

        Error Message: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
        Stacktrace: 

        Error Message: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
        Stacktrace: 

        Failed Step: Create artifact store "A1"
        Specification: specs/ArtifactStoreAPI.spec:14
        Error Message: Connection closed [127.0.0.1:45238] cause: EOF
        Stacktrace: 

    Error Message: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
    Stacktrace: 

  Error Message: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
  Stacktrace: 

Failed to initialize spec datastore. Error: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
# ConfigReposPipeline
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
# PipelineHistoryPagination
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
# TemplatesAPI
  Error Message: write tcp 127.0.0.1:37463->127.0.0.1:45238: use of closed network connection
  Stacktrace: 

Ruby runner Failed. Reason: exit status 1
```

### Gauge version
```
Gauge version: 1.0.0
gauge-ruby - 0.5.1
```

**Comment by rajiesh** [comment]
This issue turned out to be an error with the step implementation file, which resulted in the file not getting loaded. So the step couldn't be executed. This is not an issue with gauge. Closing the issue

**Comment by sriv** [comment]
Nevertheless, user code error should not crash gauge or the runner. Reopening this.

**Comment by sriv** [comment]
At the least, since not all language runners implement a sandbox, the errors in implementation should have proper error message

**Comment by sriv** [comment]
An update: @jonathangiber's example helped narrow down one case, i.e. if there is a null value added to `Gauge.writeMessage` then it crashes the gauge-java runner, causing the `use of closed network connection` errors.

As a principle we would like to have the runners not crash because of test code, however in this case, it was clearly the runner not handling the case. Have a fix for this issue, and will raise a PR.

### Steps to replicate:

- `gauge init java`
- Edit `StepImplementation.java`, add `Gauge.writeMessage(null)` in context step implementation.
- `gauge run specs`

Changes include:

- `gauge` will try to assess health of the runner by checking the connection before trying to execute a step, and if it detects that the runner died, it will break execution, giving faster feedback.
- this particular issue is to be fixed in `gauge-java`, i.e. ignore null messages.

@rajiesh 's problem report is with the `ruby` runner, where I see the same issue, `nil` value passed to `Gauge.write_message` crashes the runner. 

Protobuf asserts the values before building the message, and `nil` is not a valid String value. So all runners need to check for `nil`/`null` before adding it to the proto object.

**Comment by sriv** [comment]
Gauge will now break execution whenever the runner crashes, thus preventing all the noise when attempting to run subsequent steps. 

Note that runner needs to be alive and healthy in order for gauge to be able to proceed. So, breaking out is still an indication that either the runner or the user code needs to be looked at.

**Comment by sguptatw** [comment]
Still getting error `use of closed network connection` in the following scenario

**Steps to replicate**
* create a gauge-java project
* Modify step `Vowels in English language are <vowelString>.` implementation to add Gauge.writeMessage(null)
```
    @Step("Vowels in English language are <vowelString>.")
    public void setLanguageVowels(String vowelString) {
        Gauge.writeMessage(null);
        vowels = new HashSet<>();
        for (char ch : vowelString.toCharArray()) {
            vowels.add(ch);
        }
    }
```
* gauge run from the command line
Getting error
```
java.lang.NullPointerException: Element at index 0 is null.
        at com.google.protobuf.AbstractMessageLite$Builder.addAllCheckingNulls(AbstractMessageLite.java:367)
        at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:425)
        at gauge.messages.Spec$ProtoExecutionResult$Builder.addAllMessage(Spec.java:25758)
        at com.thoughtworks.gauge.MessageCollector.addPendingMessages(MessageCollector.java:33)
        at com.thoughtworks.gauge.MessageCollector.addPendingMessagesTo(MessageCollector.java:28)
        at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:49)
        at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:92)
        at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:98)
        at com.thoughtworks.gauge.GaugeRuntime.lambda$connectSynchronously$1(GaugeRuntime.java:81)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException: Element at index 0 is null.

        Error Message: write tcp 127.0.0.1:56876->127.0.0.1:56878: use of closed network connection
        Stacktrace:


        Failed Step: Vowels in English language are "aeiou".
        Specification: specs\example.spec:10
        Error Message: Connection closed [127.0.0.1:56878] cause: read tcp 127.0.0.1:56876->127.0.0.1:56878: wsarecv: An existing connection was forcibly closed by the remote host.
        Stacktrace:


    Error Message: write tcp 127.0.0.1:56876->127.0.0.1:56878: use of closed network connection
    Stacktrace:

Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:56876->127.0.0.1:56878: use of closed network connection
  ## Vowel counts in multiple word
    Error Message: write tcp 127.0.0.1:56876->127.0.0.1:56878: use of closed network connection
    Stacktrace:



    Error Message: write tcp 127.0.0.1:56876->127.0.0.1:56878: use of closed network connection
    Stacktrace:

Successfully generated html-report to => ...\write_message_nil\reports\html-report\index.html
Specifications: 1 executed      0 passed        1 failed        0 skipped
Scenarios:      1 executed      0 passed        1 failed        1 skipped
```
**Version**
```
Gauge version: 1.0.4.nightly-2018-11-08
Commit Hash: 5314b5e

Plugins
-------
java (0.7.0.nightly-2018-11-07)
```

**Comment by sriv** [comment]
please recheck - the PR #1235 has just been merged for this.

**Comment by sguptatw** [comment]
The latest Gauge nightly available is `8-11-2018`. The required nightly seems to be `9-11-2018`

**Comment by sguptatw** [comment]
The issue still persists with nightly
```
Gauge version: 1.0.4.nightly-2018-11-12
Commit Hash: a60ffbf

Plugins
-------
html-report (4.0.7.nightly-2018-11-12)
java (0.7.0.nightly-2018-11-07)
```
**Steps to replicate**
* Same as mentioned in comment https://github.com/getgauge/gauge/issues/1158#issuecomment-437308629

**Comment by sguptatw** [comment]
The runner crash message is displayed and the noise is minimized
```
Gauge version: 1.0.4.nightly-2018-11-19
Commit Hash: 5e997d2
```

The WriteMessage should handle null will be tracked as a part of https://github.com/getgauge/gauge/issues/1248

**Comment by ocary** [comment]
@sriv / @sguptatw - Is this change part of the Gauge 1.0.4?   Looking through the 1.0.4 tagged code, I'm seeing the changes ([example](https://github.com/getgauge/gauge/blob/v1.0.4/runner/grpcRunner.go)), but Issue 1158 is not included in the [release notes](https://github.com/getgauge/gauge/releases/tag/v1.0.4)
