### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by vbauer** [getgauge/gauge#117]
```
java.lang.NullPointerException
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.getPsiDirectory(ReferenceSearch.java:131)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.getConceptSteps(ReferenceSearch.java:127)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.access$000(ReferenceSearch.java:37)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch$1.run(ReferenceSearch.java:45)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:896)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:42)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:37)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:49)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:43)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor$1.visitVariable(ConcatenationInjector.java:186)
	at org.intellij.plugins.intelliLang.util.AnnotationUtilEx.visitAnnotatedElementInner(AnnotationUtilEx.java:164)
	at org.intellij.plugins.intelliLang.util.AnnotationUtilEx.visitAnnotatedElements(AnnotationUtilEx.java:131)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.processInjections(ConcatenationInjector.java:247)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector.getLanguagesToInject(ConcatenationInjector.java:117)
	at com.intellij.psi.impl.source.tree.injected.JavaConcatenationInjectorManager.doCompute(JavaConcatenationInjectorManager.java:107)
	at com.intellij.psi.impl.source.tree.injected.JavaConcatenationInjectorManager.access$300(JavaConcatenationInjectorManager.java:41)
	at com.intellij.psi.impl.source.tree.injected.JavaConcatenationInjectorManager$BaseConcatenation2InjectorAdapter.getLanguagesToInject(JavaConcatenationInjectorManager.java:148)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:446)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:315)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:144)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass$2.process(LineMarkersPass.java:221)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass$2.process(LineMarkersPass.java:218)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInjectableElements(InjectedLanguageManagerImpl.java:235)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.collectLineMarkersForInjected(LineMarkersPass.java:218)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:124)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by sriv** [comment]
This issue was moved to getgauge/Intellij-Plugin#48
