### ISSUE TITLE
Autocomplete of a multi-line step should be rendered in multiple lines

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1170]
_From @sguptatw on September 4, 2018 22:50_

**Expected behavior**
Autocomplete of a multi-line step should be rendered in multiple lines

**Actual behavior**
Autocomplete of a multi-line step is rendered in a single line. Getting an exception
```
04:15:06.314 request #2: textDocument/codeAction: runtime error: invalid memory address or nil pointer dereference
goroutine 102 [running]:
runtime/debug.Stack(0xc4201d33e0, 0x163b160, 0x1adf780)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/getgauge/gauge/api/lang.recoverPanic(0xc420552410)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:291 +0x57
panic(0x163b160, 0x1adf780)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/getgauge/gauge/api/lang.createConceptInfo(0xc4202f6720, 0x58, 0x7, 0x0, 0x1, 0xc42054e100, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:90 +0x255
github.com/getgauge/gauge/api/lang.getSpecCodeAction(0xc4202f6720, 0x58, 0x7, 0x0, 0x7, 0x0, 0xc42037e000, 0x1, 0x4, 0xc420316860, ...)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:52 +0x30b
github.com/getgauge/gauge/api/lang.codeActions(0xc420552410, 0x171de90, 0x17, 0x1, 0xffffffffffffffff)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:44 +0x15a
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0x1b132d0, 0x17981c0, 0xc4200360d0, 0x1795ec0, 0xc420730540, 0xc420552410, 0xc4200676e8, 0x12d6e5d, 0xc4202f7a40, 0x58)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:159 +0x1d23
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0x1b132d0, 0x17981c0, 0xc4200360d0, 0xc420730540, 0xc420552410, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:72 +0xa6
github.com/getgauge/gauge/api/lang.(*LangHandler).(github.com/getgauge/gauge/api/lang.handle)-fm(0x17981c0, 0xc4200360d0, 0xc420730540, 0xc420552410, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:63 +0x52
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc4203680a0, 0x17981c0, 0xc4200360d0, 0xc420730540, 0xc420552410)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x6f
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:67 +0x6b
```

**Steps to replicate**
* Create a spec with multi-line step
* Auto-complete the step in the specification.
> The auto-completed step is now rendered in a single line with the exception above

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-22
Commit Hash: 3750b26
```
Child of https://github.com/getgauge/gauge/issues/265

_Copied from original issue: getgauge/html-report#192_

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
