### ISSUE TITLE
NPE in Intellij IDEA

### ISSUE THREAD

**Issue by xpavlic4** [getgauge/gauge#118]
I wanted to see source code of DatatypeFactory from javax.xml package and ended up with following:

<code>
null
java.lang.NullPointerException
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.getPsiDirectory(ReferenceSearch.java:131)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.getConceptSteps(ReferenceSearch.java:127)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.access$000(ReferenceSearch.java:37)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch$1.run(ReferenceSearch.java:45)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:42)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:37)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:49)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:43)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor$1MyAnnoVisitor.visitVariableUsages(ConcatenationInjector.java:187)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor$1MyAnnoVisitor.visitVariable(ConcatenationInjector.java:205)
	at org.intellij.plugins.intelliLang.util.AnnotationUtilEx.visitAnnotatedElementInner(AnnotationUtilEx.java:165)
	at org.intellij.plugins.intelliLang.util.AnnotationUtilEx.visitAnnotatedElements(AnnotationUtilEx.java:132)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.processInjections(ConcatenationInjector.java:270)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector.getLanguagesToInject(ConcatenationInjector.java:117)
	at com.intellij.psi.impl.source.tree.injected.JavaConcatenationInjectorManager.a(JavaConcatenationInjectorManager.java:107)
	at com.intellij.psi.impl.source.tree.injected.JavaConcatenationInjectorManager.access$300(JavaConcatenationInjectorManager.java:41)
	at com.intellij.psi.impl.source.tree.injected.JavaConcatenationInjectorManager$BaseConcatenation2InjectorAdapter.getLanguagesToInject(JavaConcatenationInjectorManager.java:148)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:444)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:315)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:144)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:193)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:188)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:210)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
</code>

**Comment by sriv** [comment]
Yes, this has been reported via #117 too. This is an issue with Intellij Plugin and has been fixed via https://github.com/getgauge/Intellij-Plugin/commit/37e638fe596280fcaecf0ca0c4724198fe4c4ebe. This is yet to be pushed out as a release.

**Comment by kashishm** [comment]
This issue is fixed in latest [Intellij plugin release] (https://plugins.jetbrains.com/plugin/7535) and [0.0.6 github release] (https://github.com/getgauge/Intellij-Plugin/releases).
If the issue still persist, feel free to reopen [getgauge/Intellij-Plugin@48] (https://github.com/getgauge/Intellij-Plugin/issues/48).
