### ISSUE TITLE
Unable to install plugin using the file offline installation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1206]
**Expected behavior**
Should be able to install plugin using the offline file installation.

**Actual behavior**
Getting the error
```
Error ----------------------------------

Panicing : runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc000099960, 0xa50f20, 0x1064930)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xae
main.recoverPanic()
        src/github.com/getgauge/gauge/gauge.go:36 +0x5e
panic(0xa50f20, 0x1064930)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1c7
github.com/getgauge/gauge/plugin/install.InstallPluginFromZipFile(0xc0000a4080, 0x3e, 0xc000076080, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/plugin/install/install.go:159 +0x837
github.com/getgauge/gauge/cmd.glob..func10(0x106e100, 0xc000150cc0, 0x1, 0x3)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/cmd/install.go:43 +0xad
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0x106e100, 0xc000150c30, 0x3, 0x3, 0x106e100, 0xc000150c30)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x251
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x106d440, 0xe, 0xc0000a6080, 0xc00010c4b0)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x2d3
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).Execute(0x106d440, 0x0, 0xc000099f78)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:685 +0x32
github.com/getgauge/gauge/cmd.Parse(0x0, 0xb4d130)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/cmd/cmd.go:158 +0x44
main.main()
        src/github.com/getgauge/gauge/gauge.go:29 +0x45


Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        windows, 1.0.3.nightly-2018-10-01, 15b1e26
        csharp (0.10.6), dotnet (0.1.1), html-report (4.0.6), js (2.3.2), python (0.3.5), ruby (0.5.2), spectacle (0.1.4), xml-report (0.2.1)
```

**Steps to replicate**
* `gauge install java --file ...\gauge-java-0.6.8-darwin.x86_64.zip`

**Version**
```
Gauge version: 1.0.3.nightly-2018-10-01
Commit Hash: 15b1e26
```

**Comment by negiDharmendra** [comment]
Hey @sguptatw you trying to install gauge-java-0.6.8-darwin.x86_64.zip image on windows which is not going to work.
