### ISSUE TITLE
NPM installation should succeed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1229]
**Expected behavior**
NPM installation should succeed

**Actual behavior**
No download link found
```
Fetching download url for Gauge version 1.0.3
Error: No download link found for version 1.0.3, OS: windows, Arch: x86_64
    at Request.request.get [as _callback] (C:\Users\<user>\AppData\Roaming\npm\node_modules\@getgauge\cli\src\install.js:54:24)
    at Request.self.callback (C:\Users\<user>\AppData\Roaming\npm\node_modules\@getgauge\cli\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\<user>\AppData\Roaming\npm\node_modules\@getgauge\cli\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\<user>\AppData\Roaming\npm\node_modules\@getgauge\cli\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:275:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1091:14)
    at process._tickCallback (internal/process/next_tick.js:174:19)
+ @getgauge/cli@1.0.3
added 80 packages from 75 contributors in 16.631s
```

**Comment by sguptatw** [comment]
Working as expected now
