### ISSUE TITLE
NullPointerException at StepUtil.isGaugeFileExtension(StepUtil.java:260)

### ISSUE THREAD

**Issue by nyurik** [getgauge/gauge#125]
```
null
java.lang.NullPointerException
	at com.thoughtworks.gauge.util.StepUtil.isGaugeFileExtension(StepUtil.java:260)
	at com.thoughtworks.gauge.rename.CustomRenameHandler.isAvailableOnDataContext(CustomRenameHandler.java:51)
	at com.thoughtworks.gauge.rename.CustomRenameHandler.isRenaming(CustomRenameHandler.java:68)
	at com.intellij.refactoring.rename.RenameHandlerRegistry.getRenameHandler(RenameHandlerRegistry.java:76)
	at com.intellij.refactoring.actions.RenameElementAction.getHandler(RenameElementAction.java:51)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:84)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by ApoorvaM** [comment]
Issue moved to Gauge-IntelliJ plugin. This can be tracked [here](https://github.com/getgauge/Intellij-Plugin/issues/56).
