### ISSUE TITLE
Error: Failed to load gRPC binary module

### ISSUE THREAD

**Issue by VoidScroll** [getgauge/gauge#1258]
### Expected behavior
Should run `npm start`, gauge should execute the specifications in the `/specs` folder.

### Actual behavior
```C:\Users\Void Scroll\AppData\Roaming\gauge\plugins\js\2.3.2\node_modules\grpc\src\grpc_extension.js:55
    throw error;
    ^

Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v67-win32-x64-unknown
Found: [node-v57-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'C:\Users\Void Scroll\AppData\Roaming\gauge\plugins\js\2.3.2\node_modules\grpc\src\node\extension_binary\node-v67-win32-x64-unknown\grpc_node.node'
    at Object.<anonymous> (C:\Users\Void Scroll\AppData\Roaming\gauge\plugins\js\2.3.2\node_modules\grpc\src\grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Void Scroll\AppData\Roaming\gauge\plugins\js\2.3.2\node_modules\grpc\src\client_interceptors.js:145:12)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
```
Whenever the script is run, this happens. I have updated Node.js with which I use Gauge to the latest release. Reverting back to my previous version does not fix the error.

### Steps to reproduce
1. Update Node.js to 11.2.0
2. Run specifications

### Gauge version
```Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.6)
js (2.3.2)
screenshot (0.0.1)
```

**Comment by BugDiver** [comment]
@VoidScroll  This happens after the `nodejs` update. `gauge-js` plugin uses `grpc` which is a native binding. When you install the gauge-js install all the required `npm` modules. Since you have `grpc` cached in `npm` it will install the older one which will not be compatible.

Can you please try to run `npm rebuild` in the `gauge-js` plugin directory?
In your case the dir is `C:\Users\Void Scroll\AppData\Roaming\gauge\plugins\js\2.3.2` (from the stacktrace).

**Comment by VoidScroll** [comment]
I have resolved the issue.
I may have gone overboard, but I removed Node and all its installation files, I removed Gauge on my machine, I have removed NPM, I removed every module in my working directory, and I did a clean reinstall of everything. Good reminder not to update NodeJS

Thanks for the help 👍
