### ISSUE TITLE
Getting Gauge crashed exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1272]
_From @sguptatw on December 7, 2018 3:43_

**Expected behavior**
Should be able to work with Gauge IDE features seamlessly

**Actual behavior**
```
09:08:44.953 request #1: textDocument/codeAction: runtime error: invalid memory address or nil pointer dereference
goroutine 43 [running]:
runtime/debug.Stack(0xc0001b3410, 0xa540e0, 0x106a990)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xae
github.com/getgauge/gauge/api/lang.recoverPanic(0xc0004564b0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:291 +0x5e
panic(0xa540e0, 0x106a990)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1c7
github.com/getgauge/gauge/api/lang.createConceptInfo(0xc0004120f0, 0x46, 0x0, 0x0, 0x1, 0xc0002defc0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:90 +0x25b
github.com/getgauge/gauge/api/lang.getSpecCodeAction(0xc0004120f0, 0x46, 0x0, 0x0, 0x1b, 0x0, 0xc000342840, 0x1, 0x4, 0xc0000aa480, ...)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:52 +0x387
github.com/getgauge/gauge/api/lang.codeActions(0xc0004564b0, 0xb2ca3d, 0x17, 0x1, 0xffffffffffffffff)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:44 +0x169
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0x109c398, 0xbd9ac0, 0xc0000300f8, 0xbd7940, 0xc0004446c0, 0xc0004564b0, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:159 +0x1d44
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0x109c398, 0xbd9ac0, 0xc0000300f8, 0xc0004446c0, 0xc0004564b0, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:72 +0xad
github.com/getgauge/gauge/api/lang.(*LangHandler).handle-fm(0xbd9ac0, 0xc0000300f8, 0xc0004446c0, 0xc0004564b0, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:63 +0x59
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc000057350, 0xbd9ac0, 0xc0000300f8, 0xc0004446c0, 0xc0004564b0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x76
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:67 +0x72
```

**Steps to replicate**
* Create a new `gauge-java` project
* Add a new step. When the step is partially highlighted initiate a code action. 
> The above error can be observed

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-03
Commit Hash: 62a48e5

Plugins
-------
java (0.7.0.nightly-2018-12-04)
```

> Blocks https://github.com/getgauge/gauge-vscode/issues/83

_Copied from original issue: getgauge/gauge-java#206_

**Comment by sguptatw** [comment]
_From @Apoorva-GA on December 7, 2018 8:8_

Unable to replicate the issue, as the unimplemented step is completely highlighted by diagnostics.

**Comment by sguptatw** [comment]
Got this exception again in gauge-js project. This time I was editing a specification. There were couple of unimplemented steps which I made a comment by removing the `*`. Then the following error occurred.
Here are the LSP logs of the same. Hope this helps!

```
12:01:48.688 --> request #0: initialize: {"processId":39516,"rootPath":"c:\\work\\gauge\\FT\\gauge-e2e-taiko","rootUri":"file:///c%!A(MISSING)/work/gauge/FT/gauge-e2e-taiko","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"]}},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true},"implementation":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true}},"saveFiles":true},"trace":"off","workspaceFolders":[{"uri":"file:///c%!A(MISSING)/work/gauge/FT/gauge-e2e-taiko","name":"gauge-e2e-taiko"}]}
12:01:48.688 <-- result #0: initialize: {"capabilities":{"textDocumentSync":1,"completionProvider":{"resolveProvider":true,"triggerCharacters":["*","* ","\"","\u003c",":",","]},"definitionProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentFormattingProvider":true,"renameProvider":true}}
12:01:48.688 --> notif: initialized: {}
12:01:48.688 <-- request #0: client/registerCapability: {"registrations":[{"id":"gauge-fileWatcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"c:/work/gauge/FT/gauge-e2e-taiko/**/*{.cpt,.spec,.md}","kind":5}]}}]}
12:01:48.689 --> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///c%!A(MISSING)/work/gauge/FT/gauge-e2e-taiko/specs/specifications.spec","languageId":"gauge","version":30,"text":"# Specifications with scenarios\r\n\r\n## Passing Scenarios\r\n* create Project with specifications \"data/passingScenarios\" with implementation \"data/language_features\"\r\n* Run Gauge and ensure success\r\n* open Report\r\n* verify project name\r\n* verify specs statistics in html with \r\n\r\n   |totalCount|passCount|failCount|skippedCount|\r\n   |----------|---------|---------|------------|\r\n   |1         |1        |0        |0           |\r\n* verify scenario statistics in html with \r\n\r\n   |totalCount|passCount|failCount|skippedCount|\r\n   |----------|---------|---------|------------|\r\n   |2         |2        |0        |0           |\r\n\r\n* click Specification \"Basic specification with passing scenarios\"\r\n* verify scenario \"Scenario1\" is displayed above scenario \"Scenario2\"\r\nVerify that execution time is displayed for the scenario\r\nVerify that execution time is displayed for every step\r\n\r\n## Pass, Failed and skipped Scenarios\r\n* create Project with specifications \"data/passFailSkipped\" with implementation \"data/language_features\"\r\n* Run Gauge and ensure failure\r\n* open Report\r\n* verify specs statistics in html with \r\n\r\n   |totalCount|passCount|failCount|skippedCount|\r\n   |----------|---------|---------|------------|\r\n   |1         |0        |1        |0           |\r\n* verify scenario statistics in html with \r\n\r\n   |totalCount|passCount|failCount|skippedCount|\r\n   |----------|---------|---------|------------|\r\n   |3         |1        |1        |1           |\r\n* click Specification \"One Pass, one fail and one skipped\"\r\n* verify scenario \"Failing Scenario\" is displayed above scenario \"Skipped Scenario\"\r\n* verify scenario \"Skipped Scenario\" is displayed above scenario \"Passing Scenario\"\r\n* verify Error details are displayed for the failing step\r\n* verify screenshot is displayed for the failing step"}}
12:01:48.691 --> result #0: client/registerCapability: null
12:01:48.691 --> request #1: textDocument/codeAction: {"textDocument":{"uri":"file:///c%!A(MISSING)/work/gauge/FT/gauge-e2e-taiko/specs/specifications.spec"},"range":{"start":{"line":21,"character":0},"end":{"line":21,"character":0}},"context":{"diagnostics":[{"range":{"start":{"line":21,"character":0},"end":{"line":21,"character":56}},"message":"Step implementation not found","severity":1,"code":"step(\"Verify that execution time is displayed for every step\", async function() {\n\tthrow 'Unimplemented Step';\n});"}]}}
12:01:48.700 <-- notif: window/logMessage: {"type":1,"message":"An error occurred. Refer lsp.log for more details."}
12:01:48.703 request #1: textDocument/codeAction: runtime error: invalid memory address or nil pointer dereference
goroutine 62 [running]:
runtime/debug.Stack(0xc000411410, 0xa540e0, 0x106a990)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xae
github.com/getgauge/gauge/api/lang.recoverPanic(0xc000318320)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:291 +0x5e
panic(0xa540e0, 0x106a990)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1c7
github.com/getgauge/gauge/api/lang.createConceptInfo(0xc00032aa00, 0x44, 0x15, 0x0, 0x1, 0xc0002fae40, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:90 +0x25b
github.com/getgauge/gauge/api/lang.getSpecCodeAction(0xc00032aa00, 0x44, 0x15, 0x0, 0x15, 0x0, 0xc00035ef20, 0x1, 0x4, 0x0, ...)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:52 +0x387
github.com/getgauge/gauge/api/lang.codeActions(0xc000318320, 0xb2ca3d, 0x17, 0x1, 0xffffffffffffffff)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/codeAction.go:44 +0x169
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0x109c398, 0xbd9ac0, 0xc000078120, 0xbd7940, 0xc0003024e0, 0xc000318320, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:159 +0x1d44
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0x109c398, 0xbd9ac0, 0xc000078120, 0xc0003024e0, 0xc000318320, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:72 +0xad
github.com/getgauge/gauge/api/lang.(*LangHandler).handle-fm(0xbd9ac0, 0xc000078120, 0xc0003024e0, 0xc000318320, 0x0, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:63 +0x59
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc0003680c0, 0xbd9ac0, 0xc000078120, 0xc0003024e0, 0xc000318320)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x76
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/api/lang/server.go:67 +0x72
```

**Comment by Debashis9012** [comment]
Tried to replicate the above mentioned steps but it does not replicate.
version
```
Gauge version: 1.0.4.nightly-2019-01-22
Commit Hash: 3a9a647

Plugins
-------

java (0.7.0.nightly-2019-01-24)
js (2.3.4.nightly-2018-12-20)
```
