### ISSUE TITLE
Continue on failure not working properly when Running scenario via codelens

### ISSUE THREAD

**Issue by delmaamoun** [getgauge/gauge#1280]
I was wracking my brain as to why "@continue_on_failure" wasn't working when I tried running the scenario until I realized that using the "Run Scenario" codelens link was somehow ignoring the "@continue_on_failure" property. It works fine when the scenario is run from the commandline

Gauge vscode version: 0.07

```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.6)
java (0.6.9)
python (0.3.5.nightly-2018-12-04)
screenshot (0.0.1)
spectacle (0.1.3)
```

**Comment by sriv** [comment]
@delmaamoun - is there a project that you can share where I can see this issue? I believe since vscode's output does not print a step if it succeeds is causing confusion whether the step was executed or not.

If you can verify against the report by clicking on the gauge statistics on the status bar of VSCode post execution, you should see all steps that were executed. 

I realized that `continue_on_failure` was being handled, however it wasn't obvious by looking at the vscode terminal window.

**Comment by NivedhaSenthil** [comment]
https://github.com/delmaamoun/gauge-continue I could replicate it with the example shared by @delmaamoun . In reports if executed from VScode's  codelens I don't see steps following step marked as continue on failure whereas if I execute from command line could those steps being executed in reports.

**Comment by sriv** [comment]
I somehow overlooked the sample project. Apologies.

Checking it now.

**Comment by sriv** [comment]
The `continue_on_failure` seems to work for me, even for https://github.com/delmaamoun/gauge-continue. The problem I see is that the vscode terminal does not show steps executed.

This is because we use `--simple-console` to render the output, and do not use `--verbose`. Hence the output only shows Specs/Scenarios, and brings up step only if there is a failure. Successful steps are not shown in the vscode output.

What VS Code shows on success:

```
Running tool: gauge run /tmp/gauge-continue/specs/example.spec:3 --simple-console --hide-suggestion
# Specification Heading
  ## Vowel counts in single word

Successfully generated html-report to => /tmp/gauge-continue/reports/html-report/index.html
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	0 skipped

Total time taken: 8ms
Success: Tests passed.
```

On failure (with continue on failure):

```
Running tool: gauge run /tmp/gauge-continue/specs/example.spec:3 --simple-console --hide-suggestion
# Specification Heading
  ## Vowel counts in single word
        
        Failed Step: Should Continue
        Specification: /tmp/gauge-continue/specs/example.spec:5
        Error Message: [93m
        
        assert_expectations() called at[0m
        [4m[94m"/tmp/gauge-continue/step_impl/step_impl.py:11"[0m[93m in should_continue()
        
        [91m[4mFailed Expectations : 4
        [0m
        1: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:23[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 1 for index ['1'][0m
            expect(False, f"soft assert 1 for index {num}")
        
        2: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:24[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 2 for index ['1'][0m
            expect(False, f"soft assert 2 for index {num}")
        
        3: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:23[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 1 for index ['2'][0m
            expect(False, f"soft assert 1 for index {num}")
        
        4: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:24[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 2 for index ['2'][0m
            expect(False, f"soft assert 2 for index {num}")
        
        Stacktrace: 
        Traceback (most recent call last):
          File "/home/steam/.local/lib/python3.6/site-packages/getgauge/executor.py", line 31, in execute_method
            func(*params)
          File "/tmp/gauge-continue/step_impl/step_impl.py", line 11, in should_continue
            assert_expectations()
          File "/home/steam/.local/lib/python3.6/site-packages/delayed_assert/delayed_assert.py", line 36, in assert_expectations
            assert False, _report_failures()
        AssertionError: [93m
        
        assert_expectations() called at[0m
        [4m[94m"/tmp/gauge-continue/step_impl/step_impl.py:11"[0m[93m in should_continue()
        
        [91m[4mFailed Expectations : 4
        [0m
        1: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:23[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 1 for index ['1'][0m
            expect(False, f"soft assert 1 for index {num}")
        
        2: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:24[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 2 for index ['1'][0m
            expect(False, f"soft assert 2 for index {num}")
        
        3: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:23[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 1 for index ['2'][0m
            expect(False, f"soft assert 1 for index {num}")
        
        4: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:24[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 2 for index ['2'][0m
            expect(False, f"soft assert 2 for index {num}")
        
        

Successfully generated html-report to => /tmp/gauge-continue/reports/html-report/index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

Total time taken: 127ms
Error: Tests failed.
```

What it could show :

```
Running tool: gauge run /tmp/gauge-continue/specs/example.spec:3 --simple-console --hide-suggestion --verbose
# Specification Heading
  ## Vowel counts in single word
      * Should Continue 
      
         |Count|
         |-----|
         |1    |
         |2    |
        
        Failed Step: Should Continue
        Specification: /tmp/gauge-continue/specs/example.spec:5
        Error Message: [93m
        
        assert_expectations() called at[0m
        [4m[94m"/tmp/gauge-continue/step_impl/step_impl.py:11"[0m[93m in should_continue()
        
        [91m[4mFailed Expectations : 4
        [0m
        1: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:23[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 1 for index ['1'][0m
            expect(False, f"soft assert 1 for index {num}")
        
        2: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:24[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 2 for index ['1'][0m
            expect(False, f"soft assert 2 for index {num}")
        
        3: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:23[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 1 for index ['2'][0m
            expect(False, f"soft assert 1 for index {num}")
        
        4: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:24[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 2 for index ['2'][0m
            expect(False, f"soft assert 2 for index {num}")
        
        Stacktrace: 
        Traceback (most recent call last):
          File "/home/steam/.local/lib/python3.6/site-packages/getgauge/executor.py", line 31, in execute_method
            func(*params)
          File "/tmp/gauge-continue/step_impl/step_impl.py", line 11, in should_continue
            assert_expectations()
          File "/home/steam/.local/lib/python3.6/site-packages/delayed_assert/delayed_assert.py", line 36, in assert_expectations
            assert False, _report_failures()
        AssertionError: [93m
        
        assert_expectations() called at[0m
        [4m[94m"/tmp/gauge-continue/step_impl/step_impl.py:11"[0m[93m in should_continue()
        
        [91m[4mFailed Expectations : 4
        [0m
        1: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:23[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 1 for index ['1'][0m
            expect(False, f"soft assert 1 for index {num}")
        
        2: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:24[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 2 for index ['1'][0m
            expect(False, f"soft assert 2 for index {num}")
        
        3: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:23[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 1 for index ['2'][0m
            expect(False, f"soft assert 1 for index {num}")
        
        4: [91mFailed at "[0m[94m[4m/tmp/gauge-continue/step_impl/step_impl.py:24[0m[91m", in failassert()[1m[4m
        ErrorMessage: soft assert 2 for index ['2'][0m
            expect(False, f"soft assert 2 for index {num}")
        
        
      * Make sure it continues
      * Make sure it continues

Successfully generated html-report to => /tmp/gauge-continue/reports/html-report/index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

Total time taken: 114ms
Error: Tests failed.
```
@delmaamoun  - do you see anything different from what I've noticed?

**Comment by delmaamoun** [comment]
The report generated by vscode doesn't show the following steps being executed. The last step is the failed step
![image](https://user-images.githubusercontent.com/10405347/50150178-7e25ed00-02bd-11e9-8763-6d25b321ea24.png)

**Comment by sriv** [comment]
That is strange. Your screenshot does not look like the html-report generated by vscode. It should be a dark themed one.

I see something like this:
![continue_on_failure](https://user-images.githubusercontent.com/389148/50150697-a3632d00-02b6-11e9-816c-0ef10d8657af.png)

Could you try this with the nightly version of gauge/gauge-python and gauge-vscode?

Gauge Nightly: https://bintray.com/gauge/Gauge/Nightly/1.0.4.nightly-2018-12-14
Gauge VSCode Nightly: https://bintray.com/gauge/gauge-vscode/Nightly/0.0.8.nightly-2018-12-17
Gauge-python Nightly: https://bintray.com/gauge/gauge-python/Nightly/0.3.5.nightly-2018-12-05

**Comment by NivedhaSenthil** [comment]
It works fine with VsCode nightly for me

**Comment by delmaamoun** [comment]
working with vscode nightly.
FYI, the Gauge nightly is getting flagged as a virus for me 🤣

**Comment by sriv** [comment]
@delmaamoun - thanks for confirming. I shall close this issue.

Please comment if you need this reopened.

What antivirus software/operating system are you on? I just ran a scan for the latest nightly, windows-64bit, it came clean: 

- Installer: https://www.virustotal.com/#/url/c40986b6fdc239eb299a8eecf3ead55d634864938071094a1174d212a0eafa33/detection
- Zip: https://www.virustotal.com/#/url/8fe56b12e2de95b571426176556ec946ba41538385c79a8223cbebb6227b03ea/detection
