### ISSUE TITLE
Should be able to install gauge using npm

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1293]
**Expected behavior**
Should be able to install gauge using npm

**Actual behavior**
Getting error
```
λ npm install -g @getgauge/cli
...\npm\gauge -> 
...\node_modules\@getgauge\cli\bin\gauge

@getgauge/cli@1.0.3 install 
...\npm\node_modules\@getgauge\cli
node ./src/index.js

Fetching download url for Gauge version 1.0.3
TypeError: Cannot read property 'assets' of undefined
at Request.request.get [as _callback] (...\npm\node_modules\@getgauge\cli\src\install.js:46:40)
at self.callback (...\npm\node_modules\@getgauge\cli\node_modules\request\request.js:185:22)
at Request.emit (events.js:182:13)
at Request.onRequestError (...\npm\node_modules\@getgauge\cli\node_modules\request\request.js:881:8)
at ClientRequest.emit (events.js:182:13)
at TLSSocket.socketErrorListener (_http_client.js:392:9)
at TLSSocket.emit (events.js:182:13)
at emitErrorNT (internal/streams/destroy.js:82:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
```
**Steps to replicate**
> OS - Windows
* Open powershell
* Ensure gauge is uninstalled
* `npm install @getgauge/cli -g`
> Getting the above error

**Version**
This tries to install the released version of Gauge 1.0.3

**Comment by sguptatw** [comment]
Seems like the issue occurs when there is a problem with network connectivity. Running the command again installed it successfully.

**Comment by jagretz** [comment]
This same message also appears when trying to install behind a company firewall. Connecting to an external source resolved the issue but it took me a good minute to realize that was the issue given the error message.

**Comment by Apoorva-GA** [comment]
Fix available in gauge nightly >= 2/7/19

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed in windows os.
Tested version:
`Gauge version: 1.0.6.nightly-2019-08-26`
