### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: stepValidateRequest.numberOfParameters

### ISSUE THREAD

**Issue by akalaiselvan** [getgauge/gauge#1311]
Iam getting this error while running my spec. i was working fine ... i did few changes in folder structure , after that not even a single step is running ..pls help me out

"C:/Program Files/Gauge/bin/gauge.exe" run --machine-readable --hide-suggestion --simple-console D:/QTPCO/AUTOIT/specs/test.spec:40
Testing started at 5:57 PM ...
com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: stepValidateRequest.numberOfParameters

at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)

at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:72)

at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:196)

at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)

at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)

at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)

at gauge.messages.Messages$Message.parseFrom(Messages.java:21451)

at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:67)

at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)

com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: stepValidateRequest.numberOfParameters

[ValidationError] D:QTPCOAUTOITspecs est.spec:41 Connection closed [127.0.0.1:56307] cause: read tcp 127.0.0.1:56303->127.0.0.1:56307: wsarecv: An existing connection was forcibly closed by the remote host. => 'it prints'Successfully generated html-report to => D:\QTPCO\AUTOIT\reports\html-report\index.html

Specifications: 0 executed 0 passed 0 failed 0 skipped
Scenarios: 0 executed 0 passed 0 failed 0 skipped

Total time taken: 42ms

Process finished with exit code 0

**Comment by sriv** [comment]
looks like an issue with `gauge-java`. Moving it to the right repo.

@akalaiselvan - if you can share a project/steps to reproduce this issue, it will be most useful and help us fix this quickly!
