### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: 1 when running specs folder instead of specific specification in that folder

### ISSUE THREAD

**Issue by SureshRajpurohit85** [getgauge/gauge#1313]
runing specs from intellij : C:\IQBotCICD\GAUGE_HOME\bin\gauge.exe run --machine-readable --hide-suggestion --simple-console C:/Test/UIAutomation/specs
Expected results : should run all the specification inside that folder
Actual results : Test suite get ignored with the exception as 
`java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1963)
	at com.thoughtworks.gauge.processor.ValidateStepProcessor.getMethodName(ValidateStepProcessor.java:76)
	at com.thoughtworks.gauge.processor.ValidateStepProcessor.validateStep(ValidateStepProcessor.java:56)
	at com.thoughtworks.gauge.processor.ValidateStepProcessor.process(ValidateStepProcessor.java:41)
	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:92)
	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:98)
	at com.thoughtworks.gauge.GaugeRuntime.lambda$connectSynchronously$1(GaugeRuntime.java:81)
	at java.lang.Thread.run(Thread.java:748)

java.lang.StringIndexOutOfBoundsException: String index out of range: 1
`

**Comment by Apoorva-GA** [comment]
@SureshRajpurohit85 Running the specs folder works fine with our sample java template(created using `gauge init java`)when run from intelij. 
Please give us a sample project where this issue can be reproduced.
Also please run `gauge -v` and paster the output, Also let us know what version of gauge-inellij plugin are you using.
