### ISSUE TITLE
invalid memory address or nil pointer dereference - when running in Parallel

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#1338]
invalid memory address or nil pointer dereference thrown in middle of the test run.

### Actual behavior
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x901039]

goroutine 297 [running]:
github.com/getgauge/gauge/runner.(*LanguageRunner).EnsureConnected(0xc001efd950, 0x30)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:230 +0x1a9
github.com/getgauge/gauge/runner.(*LanguageRunner).ExecuteAndGetStatus(0xc001efd950, 0xc00225b7c0, 0x1)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:285 +0x2f
github.com/getgauge/gauge/runner.(*MultithreadedRunner).ExecuteAndGetStatus(0xc002caa360, 0xc00225b7c0, 0xc00036e301)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:128 +0x38
github.com/getgauge/gauge/execution.executeHook(0xc00225b7c0, 0xbe71c0, 0xc00036e390, 0xbf2d40, 0xc002caa360, 0xc002d3ef00)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:371 +0x3b
github.com/getgauge/gauge/execution.(*stepExecutor).notifyAfterStepHook(0xc0015f89f0, 0xc00036e390)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/stepExecutor.go:92 +0xa8
github.com/getgauge/gauge/execution.(*stepExecutor).executeStep(0xc0015f89f0, 0xc00030b600, 0xc002ac6cc0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/stepExecutor.go:58 +0x334
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeStep(0xc00263fc70, 0xc00030b600, 0xc001605880, 0xc00039c900, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:172 +0x18e
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeConcept(0xc00263fc70, 0xc001b6e200, 0xc00133e2d0, 0xc00039c900, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:188 +0x3f8
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeStep(0xc00263fc70, 0xc001b6e200, 0xc001605c00, 0xc00039c900, 0xc002ca0000)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:166 +0x6e
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeSteps(0xc00263fc70, 0xc00289e000, 0x8, 0x8, 0xc00289e040, 0x8, 0x8, 0xc00039c900)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:150 +0xa6
github.com/getgauge/gauge/execution.(*scenarioExecutor).execute(0xc00263fc70, 0xbe72e0, 0xc0012271e0, 0xbf3100, 0xc00039c900)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:87 +0x6a2
github.com/getgauge/gauge/execution.(*specExecutor).executeScenario(0xc00065ed20, 0xc0012271e0, 0x8, 0x8, 0x9)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:291 +0x1eb
github.com/getgauge/gauge/execution.(*specExecutor).executeScenarios(0xc00065ed20, 0xc0019a8d80, 0x10, 0x10, 0xc0019a8d80, 0x10, 0x10, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:265 +0x83
github.com/getgauge/gauge/execution.(*specExecutor).execute(0xc00065ed20, 0x10101, 0xc002caa360)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:103 +0x35f
github.com/getgauge/gauge/execution.(*simpleExecution).executeSpecs(0xc002aeb110, 0xc0004c1c50, 0x0, 0x0, 0x0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/simpleExecution.go:130 +0x19e
github.com/getgauge/gauge/execution.(*simpleExecution).execute(0xc002aeb110)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/simpleExecution.go:92 +0x120
github.com/getgauge/gauge/execution.(*parallelExecution).startSpecsExecutionWithRunner(0xc001e81880, 0xc0004c1c50, 0xc000782000, 0xbf2d40, 0xc002caa360, 0x4)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:225 +0x9e
github.com/getgauge/gauge/execution.(*parallelExecution).startMultithreaded(0xc001e81880, 0xbf2d40, 0xc002caa360, 0xc000782000, 0x4)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:180 +0x88
created by github.com/getgauge/gauge/execution.(*parallelExecution).executeMultithreaded
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:171 +0x4d0
```

A similar issue https://github.com/getgauge/gauge-java/issues/232 was raised but was only for a particular version of gauge-java.

### Gauge version
```
Gauge version: 1.0.4

Plugins
-------
flash (0.0.1)
html-report (4.0.6)
java (0.6.9)
js (2.3.4)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

**Comment by BugDiver** [comment]
@haroon-sheikh  Are you still facing this issue?

**Comment by haroon-sheikh** [comment]
@haroon-sheikh Yep, thats intermittently still happening even with upgrading to 0.7.1 of gauge-java.

**Comment by BugDiver** [comment]
@haroon-sheikh Can you give us some more information which can help to replicate the issue?
For example, a sample project, info about your machine environment, no of parallel streams or anything else which you think could be useful.

**Comment by haroon-sheikh** [comment]
@BugDiver I'm not sure whats causing this so cant create a sample project.
I'm using this jdk11 docker image `sitture/docker-gauge-java:latest` to run the tests with 4 or 8 nodes.

**Comment by nehashri** [comment]
@haroon-sheikh were you able to try it out?
