### ISSUE TITLE
Cant install guage/cli 

### ISSUE THREAD

**Issue by pnakhat** [getgauge/gauge#1363]
npm install -g @getgauge/cli

`
/usr/local/lib/node_modules/@getgauge/cli/src/index.js:14
var downloadAndExtract = async function(version) {
                               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @getgauge/cli@1.0.4 install: `node ./src/index.js`
npm ERR! Exit status 1`

**Comment by zabil** [comment]
You need node version 8.0+ to install gauge.
You can find your node version by running the command
```
$ node --version
```
