### ISSUE TITLE
Connection to runner lost.

### ISSUE THREAD

**Issue by xgraffm** [getgauge/gauge#1368]
I am encountering an issue when running on linux (ubuntu) but the same project runs fine on Mac

bundle exec gauge run ./specs/test.spec

Gauge version: 1.0.5
Commit Hash: 48d032f

Plugins
-------
html-report (4.0.6)
ruby (0.5.1)
screenshot (0.0.1)
spectacle (0.1.3)

Error ----------------------------------

Connection to runner with Pid 12634 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:38645->127.0.0.1:35378: use of closed network connection

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

++++++++++++++++++++++++++++++++++++++++++++++++++
/home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/method_cache.rb:84:in `initialize': no implicit conversion of nil into String (TypeError)
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/method_cache.rb:84:in `new'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/method_cache.rb:84:in `relative_filepath'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/processors/execution_handler.rb:43:in `get_filepath'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/processors/execution_handler.rb:49:in `handle_failure'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/processors/execute_step_request_processor.rb:32:in `rescue in process_execute_step_request'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/processors/execute_step_request_processor.rb:29:in `process_execute_step_request'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/message_processor.rb:58:in `call'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/message_processor.rb:58:in `process_message'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/gauge_runtime.rb:56:in `handle_message'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/gauge_runtime.rb:41:in `dispatch_messages'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/gauge_runtime.rb:85:in `<module:Runtime>'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/gauge_runtime.rb:33:in `<module:Gauge>'
	from /home/ubuntu/workspace/src/vendor/bundle/ruby/2.5.0/gems/gauge-ruby-0.5.2/lib/gauge_runtime.rb:31:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'

**Comment by xgraffm** [comment]
I rolled back to gauge 1.0.4 with all the same plugin versions per the working config on my mac and still see the same error.
The plugin versions and gauge 1.0.4 run fine on the mac.

**Comment by xgraffm** [comment]
Issues turned out to be environmental
