### ISSUE TITLE
Panic with specFileCollection while running Gauge

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1421]
There seems to be a panic occuring intermittently while running Gauge. 
Gauge panics while running unable to parse specs.
```
panic: runtime error: index out of range
goroutine 96 [running]:
github.com/getgauge/gauge/parser.(*specFileCollection).Next(0xc000165da0, 0x0, 0x0)
    /Users/admin/Documents/Doga/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/parser/specFileCollection.go:43 +0xbd
github.com/getgauge/gauge/parser.parseSpecFiles.func1(0xc000165da0, 0xc0005a22a0, 0xc000332250, 0xc00031cba0)
    /Users/admin/Documents/Doga/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/parser/parse.go:74 +0x67
created by github.com/getgauge/gauge/parser.parseSpecFiles
    /Users/admin/Documents/Doga/pipelines/Gauge-Nightly/src/github.com/getgauge/gauge/parser/parse.go:72 +0x96
```
This is often seen in some travis ci builds. eg: https://travis-ci.org/getgauge/gauge/jobs/536115699 , https://travis-ci.org/getgauge/gauge-js/jobs/536190314

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Observation: All the build are passing consistently.
Tested version: `	
gauge-1.0.6.nightly-2019-07-02`
