### ISSUE TITLE
Deleting 'specs' folder causes error

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge#144]
_From @timhurkmans on May 13, 2015 14:29_

On gauge-maven-plugin:1.0.1

Create a new folder 'specs2' in the same folder as 'specs'.
Change the specs dir configuration using:

	<specsDir>specs2</specsDir>

Run. Works.
Delete the (now unused) 'specs' folder
Run. Error message:

	[INFO] --- gauge-maven-plugin:1.0.1:execute (default) @ testproject ---
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xc0000005 code=0x0 addr=0x14 pc=0x5097c5]
	
	goroutine 16 [running]:
	github.com/getgauge/gauge/util.func┬À001(0x12a8a690, 0x50, 0x0, 0x0, 0x1b26b8, 0x12afc660, 0x0, 0x0)
	        /tmp/src/github.com/getgauge/gauge/util/finder.go:57 +0x45
	path/filepath.Walk(0x12a8a690, 0x50, 0x12b0df2c, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:392 +0x97
	github.com/getgauge/gauge/util.FindAllNestedDirs(0x12a8a690, 0x50, 0x0, 0x0, 0x0
	)
	        /tmp/src/github.com/getgauge/gauge/util/finder.go:61 +0xaa
	main.(*specInfoGatherer).watchForFileChanges(0x12a86990)
	        /tmp/src/github.com/getgauge/gauge/spec_details.go:103 +0x35c
	created by main.(*specInfoGatherer).makeListOfAvailableSteps
	        /tmp/src/github.com/getgauge/gauge/spec_details.go:51 +0xe7
	
	goroutine 1 [select]:
	main.(*testRunner).kill(0x12af2060, 0x1b3868, 0x12af2190, 0x0, 0x0)
	        /tmp/src/github.com/getgauge/gauge/runner.go:131 +0x363
	main.executeSpecs(0x7e6600)
	        /tmp/src/github.com/getgauge/gauge/gauge.go:260 +0x1ec
	main.main()
	        /tmp/src/github.com/getgauge/gauge/gauge.go:111 +0x323
	
	goroutine 14 [runnable]:
	net.(*pollDesc).Wait(0x12aa8530, 0x72, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x42
	net.(*ioSrv).ExecIO(0x12aa2218, 0x12aa8498, 0x7e5598, 0x7, 0x8c5ac4, 0x26, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:188 +0x265
	net.(*netFD).Read(0x12aa8460, 0x12b04000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:470 +0x11a
	net.(*conn).Read(0x12aa24a0, 0x12b04000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xba
	github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).handleConnectionMessages(0x12af2120, 0x1b3960, 0x12aa24a0)
	        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:106 +0x9c
	created by github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout
	        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:96 +0x287
	
	goroutine 7 [select]:
	github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout(0x12af2120, 0x0, 0x0, 0x0, 0x0)
	        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:91 +0x2c8
	github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).HandleMultipleConnections(0x12af2120)
	        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:139 +0x28
	created by main.startAPIService
	        /tmp/src/github.com/getgauge/gauge/api.go:68 +0x337
	
	goroutine 9 [syscall, locked to thread]:
	syscall.ReadFile(0xc8, 0x12b10000, 0x8000, 0x8000, 0x12aa1eb8, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_windows.go:282 +0xa4
	syscall.Read(0xc8, 0x12b10000, 0x8000, 0x8000, 0x45b3a5, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_windows.go:284 +0x68
	os.(*File).read(0x12aa2588, 0x12b10000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/os/file_windows.go:299 +0x10b
	os.(*File).Read(0x12aa2588, 0x12b10000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x76
	io.Copy(0x1b3900, 0x12af2190, 0x1b25f0, 0x12aa2588, 0x0, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:362 +0x184
	os/exec.func┬À003(0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:221 +0x6b
	os/exec.func┬À004(0x12af2a80)
	        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:328 +0x2b
	created by os/exec.(*Cmd).Start
	[INFO] ------------------------------------------------------------------------
	
	        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:329 +0x996
	[INFO] BUILD FAILURE
	
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time: 5.178 sgoroutine 10 [syscall, locked to thread]:
	
	syscall.WaitForSingleObject(0xec, 0xffffffff, 0x0, 0x0, 0x0)
	[INFO] Finished at: 2015-05-13T16:21:35+02:00   /usr/local/Cellar/go/1.4.2/libex
	ec/src/syscall/zsyscall_windows.go:689 +0x66
	
	os.(*Process).wait(0x12af2040, 0x0, 0x0, 0x0)[INFO] Final Memory: 14M/34M
	
	        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec_windows.go:16 +0x7f[INFO]
	 ------------------------------------------------------------------------
	
	os.(*Process).Wait(0x12af2040, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/os/doc.go:45 +0x38
	os/exec.(*Cmd).Wait(0x12a986e0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:364 +0x19f
	main.func┬À007()
	        /tmp/src/github.com/getgauge/gauge/runner.go:202 +0x37
	created by main.waitAndGetErrorMessage
	        /tmp/src/github.com/getgauge/gauge/runner.go:207 +0xe7[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.0.1:execute (default) on project testproject: Failed to execute gauge specs. null: GaugeExecutionFailedException -> [Help 1]
	
	
	[ERROR] goroutine 15 [IO wait]:
	
	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.net.(*pollDesc).Wait(0x12aa81b0, 0x72, 0x0, 0x0)
	
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.  /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x42
	
	[ERROR] net.(*ioSrv).ExecIO(0x12aa2218, 0x12aa8118, 0x7ebd38, 0x8, 0x12aa25f8, 0x12aa87e0, 0x0, 0x0)
	
	[ERROR] For more information about the errors and possible solutions, please read the following articles:       /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:188 +0x265
	
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionExceptionnet.(*netFD).acceptOne(0x12aa80e0, 0x12aa8700, 0x2, 0x2, 0x12aa8118, 0x0, 0x0, 0x0)
	
	        /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:558 +0x3ee
	net.(*netFD).accept(0x12aa80e0, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:585 +0x119
	net.(*TCPListener).AcceptTCP(0x12aa2228, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:234 +0x48
	net.(*TCPListener).Accept(0x12aa2228, 0x0, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:244 +0x48
	github.com/getgauge/gauge/conn.func┬À002()
	        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:82 +0x39
	created by github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout
	        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:89 +0x17c
	
	goroutine 17 [sleep]:
	main.func┬À006()
	        /tmp/src/github.com/getgauge/gauge/runner.go:123 +0x56
	created by main.(*testRunner).kill
	        /tmp/src/github.com/getgauge/gauge/runner.go:129 +0x164
	
	goroutine 19 [runnable]:
	time.Time.Format(0xcce554ef, 0xe, 0x32e0f060, 0xa03200, 0x86abb1, 0xa, 0x0, 0x0)
	
	        /usr/local/Cellar/go/1.4.2/libexec/src/time/format.go:452 +0x3d2
	github.com/op/go-logging.(*stringFormatter).Format(0x12a8c9c0, 0x6, 0x12b1de50, 0x1b2200, 0x12b49c20, 0x0, 0x0)
	        /tmp/src/github.com/op/go-logging/format.go:266 +0x153
	github.com/op/go-logging.(*Record).Formatted(0x12b1de50, 0x5, 0x0, 0x0)
	        /tmp/src/github.com/op/go-logging/logger.go:61 +0xac
	github.com/op/go-logging.(*LogBackend).Log(0x12aa21d8, 0x1, 0x4, 0x12b1de50, 0x0, 0x0)
	        /tmp/src/github.com/op/go-logging/log.go:52 +0x1f6
	github.com/op/go-logging.(*backendFormatter).Log(0x12a8c580, 0x1, 0x3, 0x12b1de00, 0x0, 0x0)
	        /tmp/src/github.com/op/go-logging/format.go:367 +0xb9
	github.com/op/go-logging.(*moduleLeveled).Log(0x12ad0b60, 0x1, 0x2, 0x12b1de00, 0x0, 0x0)
	        /tmp/src/github.com/op/go-logging/level.go:112 +0xd7

_Copied from original issue: getgauge/gauge-maven-plugin#2_

**Comment by prateekbaheti** [comment]
Looks like a bug with gauge when the ```specs``` directory is deleted.
To reproduce in any gauge project rename specs directory to ```specs2```. Execute ```gauge specs2```
