### ISSUE TITLE
I am unable to run script in gauge

### ISSUE THREAD

**Issue by Yashas0796** [getgauge/gauge#1456]
I have installed gauge and taiko in 2 different windows machine.
I have example.spec file present in specs folder. When I try to run the script, am getting timeout Error.

C:\Users\yashaswini.b\AppData\Roaming\npm\gaugetest>gauge run specs
(node:46624) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead

  Error Message: Error: Timed out
  Stacktrace:
  Error: Timed out
      at Timeout.<anonymous> (C:\Users\yashaswini.b\AppData\Roaming\gauge\plugins\js\2.3.5\src\test.js:43:23)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

Specification:
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)

**Comment by Apoorva-GA** [comment]
@Yashas0796 What version of `taiko` are you on? 
Also can you please share a sample project where we could replicate the issue?

**Comment by Apoorva-GA** [comment]
@Yashas0796 Any update on this?

**Comment by Apoorva-GA** [comment]
Closing this due to inactivity. Feel free to reopen if the issue persists.
