### ISSUE TITLE
Gauge tries parse plugin version from file name instead of `plugin.json` file

### ISSUE THREAD

**Issue by nvborisenko** [getgauge/gauge#1487]
I have plugin in zip file `my_super_plugin_1.0.0-beta.1-win-64.zip`.

```cmd
gauge install mypluginname -f my_super_plugin_1.0.0-beta.1-win-64.zip
```

Error:
```
Panicing : runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc000081750, 0xaa5240, 0x114ea90)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/debug/stack.go:24 +0xa4
main.recoverPanic()
        src/github.com/getgauge/gauge/gauge.go:38 +0x5e
panic(0xaa5240, 0x114ea90)
```

If rename file to `my_super_plugin_1.0.0-beta-win-64.zip` gauge is able to install it.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `104e7eef`

**Comment by nvborisenko** [comment]
This is not fixed in the latest `v1.0.7`

**Comment by sriv** [comment]
This is still an issue. 

Steps:

- ` wget https://github.com/getgauge/html-report/releases/download/v4.0.9/html-report-4.0.9-linux.x86_64.zip -O html-report.zip` (save the file using a diferent name)
- `gauge install html-report -f html-report.zip`
- Note the output: 

```
Failed to install plugin 'html-report'.
Reason: provided plugin is not compatible with OS linux amd64
```
- Observe that the correct package was downloaded, and the install works if I do not rename the file.

The ask here is that rather than depending on the file name convention, gauge can detect presense of and read `plugin.json` inside the archive.

Reopening.

**Comment by shivamgupta1793** [comment]
I'm still facing this issue with verision 1.0.6

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0x88c294]

goroutine 296 [running]:
github.com/getgauge/gauge/runner.(*LanguageRunner).EnsureConnected(0xc000a4e1e0, 0x30)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:232 +0x154
github.com/getgauge/gauge/runner.(*LanguageRunner).ExecuteAndGetStatus(0xc000a4e1e0, 0xc0010b9600, 0x9d)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:287 +0x36
github.com/getgauge/gauge/runner.(*MultithreadedRunner).ExecuteAndGetStatus(0xc00139e210, 0xc0010b9600, 0x1)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:128 +0x3f
github.com/getgauge/gauge/execution.executeHook(0xc0010b9600, 0xc5e900, 0xc0001ee2b0, 0xc75840, 0xc00139e210, 0xc000d8b340)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:403 +0x42
github.com/getgauge/gauge/execution.(*stepExecutor).notifyAfterStepHook(0xc0009c62d0, 0xc0001ee2b0)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/stepExecutor.go:100 +0xaf
github.com/getgauge/gauge/execution.(*stepExecutor).executeStep(0xc0009c62d0, 0xc000a5fc00, 0xc00034a300, 0x0)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/stepExecutor.go:64 +0x342
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeStep(0xc00138cd90, 0xc000a5fc00, 0xc00139a2a0, 0xc0007259a0, 0xc001390000)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:175 +0x1a1
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeSteps(0xc00138cd90, 0xc0013b2850, 0xd, 0xe, 0xc0013b28c0, 0xd, 0xe, 0xc0007259a0)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:153 +0xaf
github.com/getgauge/gauge/execution.(*scenarioExecutor).execute(0xc00138cd90, 0xc5ea20, 0xc0012ce420, 0xc764a0, 0xc0007259a0)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:87 +0x919
github.com/getgauge/gauge/execution.(*specExecutor).executeScenario(0xc0005641e0, 0xc0012ce420, 0xc000006ba8, 0x0, 0x1)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:317 +0x275
github.com/getgauge/gauge/execution.(*specExecutor).executeScenarios(0xc0005641e0, 0xc000006ba8, 0x1, 0x1, 0xc000006ba8, 0x1, 0x1, 0x0, 0x0)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:274 +0x8a
github.com/getgauge/gauge/execution.(*specExecutor).execute(0xc0005641e0, 0x10101, 0xc00139e210)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:109 +0x3d0
github.com/getgauge/gauge/execution.(*simpleExecution).executeSpecs(0xc00132fc00, 0xc0002f9c50, 0xc00010e300, 0x0, 0x0)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/simpleExecution.go:130 +0x19a
github.com/getgauge/gauge/execution.(*simpleExecution).execute(0xc00132fc00)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/simpleExecution.go:92 +0x18c
github.com/getgauge/gauge/execution.(*parallelExecution).startSpecsExecutionWithRunner(0xc001327a70, 0xc0002f9c50, 0xc00145cfc0, 0xc75840, 0xc00139e210, 0x1)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:240 +0xa5
github.com/getgauge/gauge/execution.(*parallelExecution).startMultithreaded(0xc001327a70, 0xc75840, 0xc00139e210, 0xc00145cfc0, 0x1)
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:198 +0x8f
created by github.com/getgauge/gauge/execution.(*parallelExecution).executeMultithreaded
        /Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:189 +0x5d3

**Comment by shivamgupta1793** [comment]
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
flash (0.0.1)
html-report (4.0.7)
java (0.7.2)
json-report (0.3.1)
spectacle (0.1.2)
xml-report (0.2.2)

**Comment by HelderMagalhaes** [comment]
@shivamgupta1793 this definitely this doesn't appear to be the same problem. If this was caused by a `gauge install -f`, please provide the complete command line.
