### ISSUE TITLE
indexOutOfRange in .gauge/plugins/js/2.3.6/node_modules/protobufjs/src/reader.js:94

### ISSUE THREAD

**Issue by kramvan1** [getgauge/gauge#1533]
### Expected behavior
gauge should end properly

### Actual behavior
```
/root/.gauge/plugins/js/2.3.6/node_modules/protobufjs/src/reader.js:94
Nov 21 12:47:05 throw indexOutOfRange(this, 10);
Nov 21 12:47:05 ^
Nov 21 12:47:05 RangeError: index out of range: 37888 + 10 > 37888
Nov 21 12:47:05 at indexOutOfRange (/root/.gauge/plugins/js/2.3.6/node_modules/protobufjs/src/reader.js:13:12)
Nov 21 12:47:05 at BufferReader.read_uint32 [as uint32] (/root/.gauge/plugins/js/2.3.6/node_modules/protobufjs/src/reader.js:94:19)
Nov 21 12:47:05 at Type.StepInfo$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.6/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:8:11)
Nov 21 12:47:05 at Type.ExecutionInfo$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.6/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:17:26)
Nov 21 12:47:05 at Type.StepExecutionEndingRequest$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.6/node_modules/@protobufjs/codegen/index.js:50:33), <anonymou
s>:11:35)
Nov 21 12:47:05 at Type.Message$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.6/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:35:41)
Nov 21 12:47:05 at Type.decodeDelimited (/root/.gauge/plugins/js/2.3.6/node_modules/protobufjs/src/type.js:520:17)
Nov 21 12:47:05 at Socket.messageHandler (/root/.gauge/plugins/js/2.3.6/src/connection.js:20:49)
Nov 21 12:47:05 at Socket.emit (events.js:193:13)
Nov 21 12:47:05 at addChunk (_stream_readable.js:295:12)
Nov 21 12:47:05 Error ----------------------------------
Nov 21 12:47:05 
Nov 21 12:47:05 [Gauge]
Nov 21 12:47:05 Connection to runner with Pid 134 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:35563->127.0.0.1:35824: use of closed network connection
```

### Steps to reproduce
1.   gauge 1.0.6
2.   run a test this was a javascript written test
3.  gauge will crash as noted above

### Gauge version
```
1.0.6
```

**Comment by zabil** [comment]
What version of Node js are you using?

**Comment by kramvan1** [comment]
@zabil 
```
$ node --version

v10.17.0

$ npm --version

6.11.3

$ nvm --version

0.35.1
```
Using latest image ` node:11-alpine`

**Comment by Debashis9012** [comment]
I have tried to replicate the same with gauge 1.0.6 and js plugin 2.3.6.
but it works for me without any error. 
I have followed the below steps:

1. create a sample js project: `gauge init js_simple`
2. execute tests: `gauge run`

Q. Could you please try the same steps and let us know if you are still facing the same issue?

node versions information:
```
➜  ~ node -v
v10.15.3
➜  ~ nvm --version
0.34.0
➜  ~ npm -v
6.4.1
```

**Comment by negiDharmendra** [comment]
@kramvan1  Any updates on this issue?

**Comment by kramvan1** [comment]
@negiDharmendra sorry, have not been able to look into this more, we use the `node:11-alpine` image for this work and don't touch the node/npm versions in there.

**Comment by negiDharmendra** [comment]
@kramvan1 I tried with the `node:11-alpine` image and it works fine.
**My docker file**
```
FROM node:11-alpine
RUN apk update \
    && apk add bash \
    && apk add curl
RUN curl -s https://downloads.gauge.org/stable | sh
RUN gauge init js_simple
RUN gauge install
CMD ["gauge", "run"]
```

**Comment by kramvan1** [comment]
@negiDharmendra   we have a rather complicated env, and this happens just a few times a week.  Don't think I can get you more narrow reproduction details right now.     I would suggest looking at the code where the index is used, it's obviously not bounded/checked properly which should be a simple code fix.

**Comment by negiDharmendra** [comment]
@kramvan1 Yes, that would have been easier if it were happening in `gauge-js` code. The error is comming from `protobufjs`. It would be easer to debug and fix tgis issue with an sample project.

**Comment by kramvan1** [comment]
Still happening, seems like code using the reader needs a tweak.
```
Feb 04 22:02:02 /root/.gauge/plugins/js/2.3.7/node_modules/protobufjs/src/reader.js:94
Feb 04 22:02:02 throw indexOutOfRange(this, 10);
Feb 04 22:02:02 ^
Feb 04 22:02:02 RangeError: index out of range: 16384 + 10 > 16384
Feb 04 22:02:02 at indexOutOfRange (/root/.gauge/plugins/js/2.3.7/node_modules/protobufjs/src/reader.js:13:12)
Feb 04 22:02:02 at BufferReader.read_uint32 [as uint32] (/root/.gauge/plugins/js/2.3.7/node_modules/protobufjs/src/reader.js:94:19)
Feb 04 22:02:02 at Type.StepInfo$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.7/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:8:11)
Feb 04 22:02:02 at Type.ExecutionInfo$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.7/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:17:26)
Feb 04 22:02:02 at Type.StepExecutionEndingRequest$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.7/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:11:35)
Feb 04 22:02:02 at Type.Message$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.7/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:35:41)
Feb 04 22:02:02 at Type.decodeDelimited (/root/.gauge/plugins/js/2.3.7/node_modules/protobufjs/src/type.js:520:17)
Feb 04 22:02:02 at Socket.messageHandler (/root/.gauge/plugins/js/2.3.7/src/connection.js:20:49)
Feb 04 22:02:02 at Socket.emit (events.js:193:13)
Feb 04 22:02:02 at addChunk (_stream_readable.js:295:12)
```

**Comment by negiDharmendra** [comment]
@kramvan1 We have released a new version of Gauge JS which uses [GRPC](https://grpc.io/) to communicate with Gauge. Please upgrade to the latest [Gauge](https://github.com/getgauge/gauge/releases/tag/v1.0.7) and [Gauge JS version](https://github.com/getgauge/gauge-js/releases/tag/v2.3.8)

**Comment by kramvan1** [comment]
@negiDharmendra ok, will give that a go, thx.

**Comment by NivedhaSenthil** [comment]
@kramvan1 may we know if that helped or you are still facing the issue ?

**Comment by zabil** [comment]
The newest release of gauge-js https://github.com/getgauge/gauge-js/releases/tag/v2.3.10
Uses pure javascript grpc. 
Closing this issue for now. Please try the newest version to see if this still happens.

**Comment by kramvan1** [comment]
Updated our pipeline, have not seen the issue recently, so looks good for now.
