### ISSUE TITLE
Quieter console reporting for Gauge

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#1576]
### Current behavior 

The default console report output for e.g. 

For example

```
> gauge init js_simple
> gauge run specs
# Specification Heading
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔

Successfully generated html-report to => index.html
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped

```

is too verbose and difficult to use especially when run in a CI_CD server. When a test suite grows there is a lot of information of text to skim for information.

### Solution 1

Add a `--quiet` flag to report only failures

```
> gauge init js_simple
> gauge run specs --quiet

# Specification Heading
  ## Vowel counts in single word	 ✔ ✘
        Failed Step: The word "gauge" has "3" vowels.
        Specification: specs/example.spec:16
        Error Message: AssertionError [ERR_ASSERTION]: 4 == 3
        Stacktrace: 
        AssertionError [ERR_ASSERTION]: 4 == 3
            at Object.<anonymous> (tests/step_implementation.js:23:10)

Successfully generated html-report to => /Users/zabilcm/Projects/vowels/reports/html-report/index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	2 executed	1 passed	1 failed	0 skipped
```

### Solution 2

Add a dot reporter to easily identify the number of scenarios as a test runs

```
> gauge init js_simple
> gauge run specs --dot

.,!

# Specification Heading
  ## Vowel counts in single word	 ✔ ✘
        Failed Step: The word "gauge" has "3" vowels.
        Specification: specs/example.spec:16
        Error Message: AssertionError [ERR_ASSERTION]: 4 == 3
        Stacktrace: 
        AssertionError [ERR_ASSERTION]: 4 == 3
            at Object.<anonymous> (tests/step_implementation.js:23:10)

Successfully generated html-report to => /Users/zabilcm/Projects/vowels/reports/html-report/index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	2 executed	1 passed	1 failed	1 skipped
```

`.` - Passing scenario
`,` - Skipped scenario
`!` - Failing scenario

**Comment by zabil** [comment]
Closing this to focus on other higher priority items.
