### ISSUE TITLE
[Gauge] [ERROR] notif #0: initialized: current runner is not compatible with gauge LSP

### ISSUE THREAD

**Issue by nischt** [getgauge/gauge#1621]
### Describe the bug
Created a project using "Create new Gauge Project"
Run spec of Default example.spec (vowels)
Python is installed and added to environment variable.

17-04-2020 17:10:41.107 [Gauge] [DEBUG] Unable to connect to runner : Timed out connecting to python
Some of the gauge lsp feature will not work as expected.
17-04-2020 17:10:41.107 [Gauge] [INFO] LangServer: reading on stdin, writing on stdout
17-04-2020 17:10:41.112 [Gauge] [ERROR] notif #0: initialized: current runner is not compatible with gauge LSP

### What command(s) did you run when you found the bug?
Run Spec

```

### Output, stack trace or logs related to the bug 
17-04-2020 17:10:11.105 [Gauge] [DEBUG] Adding specs from xxx\specs\example.spec
17-04-2020 17:10:11.105 [Gauge] [INFO] Initializing steps cache with 1 steps
17-04-2020 17:10:11.106 [Gauge] [INFO] Starting language runner
'"xxx\AppData\Local\Programs\Python\Python38-32\python.exe -m pip install getgauge==0.3.7 --user"' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
File "check_and_install_getgauge.py", line 32, in assert_versions
getgauge_version = pkg_resources.get_distribution('getgauge').version
File "xxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 481, in get_distribution
dist = get_provider(dist)
File "xxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 357, in get_provider
return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
File "xxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 900, in require
needed = self.resolve(parse_requirements(requirements))
File "xxxxAppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'getgauge' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "check_and_install_getgauge.py", line 40, in <module>
assert_versions()
File "check_and_install_getgauge.py", line 36, in assert_versions
install_getgauge("getgauge=="+expected_gauge_version)
File "check_and_install_getgauge.py", line 20, in install_getgauge
check_output([" ".join(install_cmd)], shell=True)
File "xxxx\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 411, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "xxxx\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xxx\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe -m pip install getgauge==0.3.7 --user']' returned non-zero exit status 1.
Traceback (most recent call last):
File "start.py", line 8, in <module>
import grpc
ModuleNotFoundError: No module named 'grpc'
17-04-2020 17:10:41.107 [Gauge] [DEBUG] Unable to connect to runner : Timed out connecting to python
Some of the gauge lsp feature will not work as expected.
17-04-2020 17:10:41.107 [Gauge] [INFO] LangServer: reading on stdin, writing on stdout
17-04-2020 17:10:41.112 [Gauge] [ERROR] notif #0: initialized: current runner is not compatible with gauge LSP

### Versions 
Python Version :3.8
VScode version : 1442.
Gauge Extension Version : 0.0.13

#### Gauge (Output of `gauge -v`)
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
python (0.3.7)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)

#### Node.js/Java/Python/.Net/Ruby version
Python
#### Operating System information
Windows 10 1809 OS build 17763.1098
#### IDE information
Visual studio code 1.44.2

**Comment by sriv** [comment]
can you try with latest gauge and gauge-python (i.e `0.3.9` at the time of writing this)? 

I am able to create a new project using gauge `1.0.8` and gauge-python`0.3.9`.

**Comment by sriv** [comment]
@nischt - are you still facing this issue? Is there a project that I can see this failure -  that'll help investigate better.

PS - There have been new releases, please try upgrading as well.

**Comment by NivedhaSenthil** [comment]
Closing due to inactivity.. feel free to reopen if you are still facing the issue with latest versions
