### ISSUE TITLE
Error on fresh install - when 'Run Spec' on example

### ISSUE THREAD

**Issue by AnthonySGeorge** [getgauge/gauge#1622]
Fresh Project:

Mac - JS template - VSCode
Installed via brew
NPM version 13.13.0

Run `Run Spec` in VSCode on the example.spec

output:
```Running tool: gauge run /Users/XXX/Documents/Projects/gauge/specs/example.spec --simple-console --hide-suggestion
/Users/XXX/.gauge/plugins/js/2.3.10/src/file-util.js:42
function getFileName(dir, counter = 0) {
^
SyntaxError: Unexpected token =
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:414:25)
at Object.Module._extensions..js (module.js:442:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at Object.<anonymous> (/Users/XXX/.gauge/plugins/js/2.3.10/src/step-registry.js:1:78)
at Module._compile (module.js:435:26)
at Object.Module._extensions..js (module.js:442:10)
```

Also getting an error in VSCode:
Current gauge language runner is not compatible with gauge LSP. Some of the editing feature will not work as expected

**Comment by zabil** [comment]
This works on 
```
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E287
node -v
v13.13.0

Gauge version: 1.0.8

Plugins
-------
js (2.3.10)

VS Code Version: 1.43.2
VS Code Gauge plugin 0.0.13
```

Please fill up all the sections mentioned in the issue template for any further help.
Closing this now as we are not able to replicate the issue with the specified information. Will re-open it once all the information is available.
