### ISSUE TITLE
Execution fails for nested concepts

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#173]
Error Stacktrace : 

```
java.lang.NullPointerException at
com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:33)
at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:72)            
at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)            
 java.lang.NullPointerException            
Connection closed [127.0.0.1:52858] cause: EOF
use of closed network connection            
``` 

Gauge is treating nested concept as a step and trying to execute the nested concept as step

**Comment by kashishm** [comment]
Example

Specification : 
```
Specification Heading
=====================

First scenario
--------------

* Concept Heading with "a" and "b"
```
Concept : 
```
# Concept Heading with <a> and <b>
* Says <a>
* Says <a>

# Says <a>
* Write <a>
```
