### ISSUE TITLE
Gettint panicing runtime error when executing gauge run

### ISSUE THREAD

**Issue by tjoooobooo** [getgauge/gauge#1783]
### What command(s) did you run when you found the bug?
gauge run specs (without any tags)

### Output, stack trace or logs related to the bug 
```
[Gauge]
Panicing : runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc000f8d400, 0xacbea0, 0x113fd40)
        /opt/hostedtoolcache/go/1.13.15/x64/src/runtime/debug/stack.go:24 +0x9d
main.recoverPanic()
        /home/runner/work/gauge/gauge/gauge.go:27 +0x57
panic(0xacbea0, 0x113fd40)
        /opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
github.com/getgauge/gauge/runner.(*GrpcRunner).ExecuteMessageWithTimeout(0x0, 0xc0007edb80, 0xc0000d4700, 0xc002fd4fc0, 0x0)
        /home/runner/work/gauge/gauge/runner/grpcRunner.go:195 +0x22
github.com/getgauge/gauge/validation.(*SpecValidator).validateStep(0xc002fd4f40, 0xc000185800, 0xc000038200, 0x10)
        /home/runner/work/gauge/gauge/validation/validate.go:345 +0x19e
github.com/getgauge/gauge/validation.(*SpecValidator).Step(0xc002fd4f40, 0xc000185800)
        /home/runner/work/gauge/gauge/validation/validate.go:313 +0x5f4
github.com/getgauge/gauge/gauge.(*Specification).Traverse(0xc000184100, 0xcb9220, 0xc002fd4f40, 0xc000f8d8d8)
        /home/runner/work/gauge/gauge/gauge/specification.go:261 +0x256
github.com/getgauge/gauge/validation.(*SpecValidator).validate(0xc002fd4f40, 0xc002fd4f40, 0x13, 0x0)
        /home/runner/work/gauge/gauge/validation/validate.go:298 +0x8d
github.com/getgauge/gauge/validation.(*validator).Validate(0xc0005b1a80, 0xcb88c0)
        /home/runner/work/gauge/gauge/validation/validate.go:284 +0x115
github.com/getgauge/gauge/validation.ValidateSpecs(0xc00014ef10, 0x1, 0x1, 0x0, 0x0)
        /home/runner/work/gauge/gauge/validation/validate.go:174 +0x227
github.com/getgauge/gauge/execution.glob..func1(0xc00014ef10, 0x1, 0x1, 0x0)
        /home/runner/work/gauge/gauge/execution/execute.go:107 +0xef
github.com/getgauge/gauge/cmd.execute(0x114a060, 0xc00014ef10, 0x1, 0x1)
        /home/runner/work/gauge/gauge/cmd/run.go:244 +0x241
github.com/getgauge/gauge/cmd.glob..func13(0x114a060, 0xc00014ef10, 0x1, 0x1)
        /home/runner/work/gauge/gauge/cmd/run.go:93 +0x273
github.com/spf13/cobra.(*Command).execute(0x114a060, 0xc00014eed0, 0x1, 0x1, 0x114a060, 0xc00014eed0)
        /home/runner/work/gauge/gauge/vendor/github.com/spf13/cobra/command.go:833 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x114af60, 0x42ca9a, 0x1, 0x114ace0)
        /home/runner/work/gauge/gauge/vendor/github.com/spf13/cobra/command.go:917 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/gauge/gauge/vendor/github.com/spf13/cobra/command.go:867
github.com/getgauge/gauge/cmd.Parse(0xc0001a7f18, 0xc00007e750)
        /home/runner/work/gauge/gauge/cmd/cmd.go:111 +0x3d
main.main()
        /home/runner/work/gauge/gauge/gauge.go:19 +0x4c

```

#### Gauge (Output of `gauge -v`)
```
Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
flash (0.0.2)
html-report (4.0.12)
json-report (0.3.3)
screenshot (0.0.1)
spectacle (0.1.4)
ts (0.1.0)
xml-report (0.2.3)
```
#### Node.js/Java/Python/.Net/Ruby version
node version v12.16.1

#### Operating System information
linux, 1.1.4, c982558

**Comment by zabil** [comment]
Please try the following on a new folder on the same machine

```
gauge init js_simple
gauge run specs
```

Do you see the same error. Also please share the output of the following commands

```
gauge -v
gauge config --list
```

**Comment by tjoooobooo** [comment]
The example is working fine on my machine.

```
-bash-4.2$ gauge run specs
# Specification Heading
  ## Vowel counts in single word         ✔ ✔
  ## Vowel counts in multiple word       ✔ ✔

Successfully generated html-report to => /home/ths/Runners/test/reports/html-report/index.html

Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      2 executed      2 passed        0 failed        0 skipped

Total time taken: 442ms
```

gauge -v output: 
```
Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
flash (0.0.2)
html-report (4.0.12)
json-report (0.3.3)
screenshot (0.0.1)
spectacle (0.1.4)
ts (0.1.0)
xml-report (0.2.3)
```

gauge config --list output: 
```
Key                             Value
------------------------------------------------------------------
allow_insecure_download         false
check_updates                   false
gauge_repository_url            https://downloads.gauge.org/plugin
ide_request_timeout             30000
plugin_connection_timeout       10000
plugin_kill_timeout             4000
runner_connection_timeout       30000
runner_request_timeout          30000
```

**Comment by BugDiver** [comment]
@tjoooobooo Are you facing this issue with the `typescript` plugin? If you yes do see this error happening on a newly created project (gauge init ts)?

**Comment by tjoooobooo** [comment]
Yes I am using the typescript plugin but if i use a fresh project it also works fine.

**Comment by BugDiver** [comment]
@tjoooobooo is there any compilation error (syntax error) in the project where you are seeing this error? If yes please try to fix that and then run the project?

**Comment by tjoooobooo** [comment]
I only get this before the output mentioned above:
```
Error: connect ECONNREFUSED 127.0.0.1
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
```

Does this message somehow help?

**Comment by BugDiver** [comment]
Not sure why It's would be coming, I have not seen this before. Can you give us more details, about you environment where you are seeing the error. May be you could share a project where it's replicable.

**Comment by tjoooobooo** [comment]
When creating an example project i found the error. I recently updated npm and gauge with the typescript plugin. At this moment something must have gone wrong with the configuration. But now with a fresh project everything is working again.
Thanks for your help
