### ISSUE TITLE
Exception occured in gauge plugin

### ISSUE THREAD

**Issue by esvet** [getgauge/gauge#1793]
Hi,
I got an error notification while executing a gauge scenario but execution was not affected by and the link is wrong furthermore leads to an archived gh project..

„Please log an issue in https://github.com/getgauge/intellij-plugin with following details: #### gauge process exited with code 2

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x154f5ba]

goroutine 19 [running]:
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).deleteFromConceptDictionary(0xc00018c1c0, 0xc000169f20, 0x52)
	/private/tmp/gauge-20201103-18148-1khvwv1/gauge-1.1.5/api/infoGatherer/specDetails.go:239 +0xda
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).OnConceptFileModify(0xc00018c1c0, 0xc000169f20, 0x52)
	/private/tmp/gauge-20201103-18148-1khvwv1/gauge-1.1.5/api/infoGatherer/specDetails.go:334 +0x13a
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).onFileModify(0xc00018c1c0, 0xc0001120c0, 0xc000169f20, 0x52)
	/private/tmp/gauge-20201103-18148-1khvwv1/gauge-1.1.5/api/infoGatherer/specDetails.go:391 +0xb0
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).handleEvent(0xc00018c1c0, 0xc000169f20, 0x52, 0x2, 0xc0001120c0)
	/private/tmp/gauge-20201103-18148-1khvwv1/gauge-1.1.5/api/infoGatherer/specDetails.go:422 +0x19a
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges.func1(0xc0001120c0, 0xc00018c1c0)
	/private/tmp/gauge-20201103-18148-1khvwv1/gauge-1.1.5/api/infoGatherer/specDetails.go:445 +0x18c
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges
	/private/tmp/gauge-20201103-18148-1khvwv1/gauge-1.1.5/api/infoGatherer/specDetails.go:441 +0x165

Gauge daemon initialized and listening on port: 53648
Idea version: 2020.2.3
API version: IU-202.7660.26
Plugin version: 0.4.0
Gauge version: 1.1.5“

**Comment by zabil** [comment]
0.4.0 is an old version of the plugin.
Can you try updating the intellij plugin to a release after 0.4.0? I quikly checked the source at https://github.com/JetBrains/intellij-plugins/tree/master/gauge to see that they have updated the references.

You can refer https://plugins.jetbrains.com/plugin/7535-gauge/versions

If you still see this issue after updating your plugin please raise an issue at https://youtrack.jetbrains.com/issues/IDEA

**Comment by sriv** [comment]
The stacktrace is from gauge, specifically

https://github.com/getgauge/gauge/blob/master/api/infoGatherer/specDetails.go#L239

It looks like Gauge was unable to persist/sync a reference to a concept. But it is a bit difficult to identify the cause just by looking at the stacktrace.

@esvet- would you be able to share a sample project where you see this issue?

**Comment by sriv** [comment]
Reopening this issue to investigate potential issue in gauge.

**Comment by esvet** [comment]
> 0.4.0 is an old version of the plugin.
> Can you try updating the intellij plugin to a release after 0.4.0? I quikly checked the source at https://github.com/JetBrains/intellij-plugins/tree/master/gauge to see that they have updated the references.
> 
> You can refer https://plugins.jetbrains.com/plugin/7535-gauge/versions
> 
> If you still see this issue after updating your plugin please raise an issue at https://youtrack.jetbrains.com/issues/IDEA

In Intellij Prefs/plugins I have no upgrade button for Gauge plugin; if I download it from the link you provided
i receive a gauge/lib directory. How do you suggest to proceed updating this plugin? but copying it to somewhere manually?? never updated an intelliJ plugin outside of the IDE prefs/plugins workflow and why isnt't it showing up there ???

**Comment by esvet** [comment]
> The stacktrace is from gauge, specifically
> 
> https://github.com/getgauge/gauge/blob/master/api/infoGatherer/specDetails.go#L239
> 
> It looks like Gauge was unable to persist/sync a reference to a concept. But it is a bit difficult to identify the cause just by looking at the stacktrace.
> 
> @esvet- would you be able to share a sample project where you see this issue?

Its unfortunately a customer project, sorry cant publish this project. however gauge executable works as stated
