### ISSUE TITLE
grpc error is occurring

### ISSUE THREAD

**Issue by Tyler-Wayman** [getgauge/gauge#1906]
When running scripts in a project I get the error below.  It was occurring in an older project 1.0.8.  I updated the projects software.  Gauge version, extensions....  Tried slightly older versions of gauge also.  Tried following other issues that I  saw on the net related to grpc.  Nothing has resolved the issue thus far.

The example scenario will run.  Any of my scripts fail on the first step of all scenarios.  The USB and Bluetooth errors are not of concern. They occur when the example scenario for the project is run and do not seem to affect anything.

Gauge Versions:
Gauge version: 1.1.7
Commit Hash: 5d86b72

Plugins
-------
dotnet (0.3.1)
html-report (4.0.12)
java (0.7.13)
js (2.3.15)
python (0.3.14)
ruby (0.5.4)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

**Error:**
 ## Scenario 2 - Verify that the Update Draft Button works on the Generate Report page when the report has text present        fail
: Grpc.AspNetCore.Server.ServerCallHandler[6]
Error when executing service method 'ExecuteStep'.
 FSystem.NullReferenceException: Object reference not set to an instance of an object.
at Gauge.Dotnet.StepExecutor.Execute(GaugeMethod gaugeMethod, String[] args) in /home/runner/work/gauge-dotnet/gauge-dotnet/src/StepExecutor.cs:line 55
at Gauge.Dotnet.ExecutionOrchestrator.ExecuteStep(GaugeMethod method, String[] args) in /home/runner/work/gauge-dotnet/gauge-dotnet/src/ExecutionOrchestrator.cs:line 45
at Gauge.Dotnet.Processors.ExecuteStepProcessor.Process(ExecuteStepRequest request) in /home/runner/work/gauge-dotnet/gauge-dotnet/src/Processors/ExecuteStepProcessor.cs:line 56
at Gauge.Dotnet.ExecutableRunnerServiceHandler.<>c__DisplayClass17_0.<ExecuteStep>b__0() in /home/runner/work/gauge-dotnet/gauge-dotnet/src/ExecutableRunnerServiceHandler.cs:line 54
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
[9544:20048:0212/131318.338:ERROR:device_event_log_impl.cc(211)] [13:13:18.338] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[9544:20048:0212/131318.387:ERROR:device_event_log_impl.cc(211)] [13:13:18.387] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[9544:20048:0212/131318.390:ERROR:device_event_log_impl.cc(211)] [13:13:18.390] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[9544:20048:0212/131318.464:ERROR:device_event_log_impl.cc(211)] [13:13:18.464] Bluetooth: bluetooth_adapter_winrt.cc:1203 Getting Radio failed. Chrome will be unable to change the power state by itself.
[9544:20048:0212/131318.502:ERROR:device_event_log_impl.cc(211)] [13:13:18.502] Bluetooth: bluetooth_adapter_winrt.cc:1281 OnPoweredRadioAdded(), Number of Powered Radios: 1
[9544:20048:0212/131318.513:ERROR:device_event_log_impl.cc(211)] [13:13:18.513] Bluetooth: bluetooth_adapter_winrt.cc:1296 OnPoweredRadiosEnumerated(), Number of Powered Radios: 1

        Failed Step: Set the Screenshot Level for this Scenario to "3"
        Specification: specs\PageObjectSpecs\GenerateReportPage\GenRptPage_UpdateDraftButton.spec:7
        Error Message: Exception was thrown by handler.
        Stacktrace:

**Comment by stephenicus** [comment]
I'm having the exact same issue after porting a .NetFramework Gauge project to a .NetCore Gauge project. The stacktrace error points to the file: /home/runner/work/gauge-dotnet/gauge-dotnet/src/StepExecutor.cs:line 55 as being the cause of the issue, which, as I understand it, tells me that a disconnect is occurring between the spec files and step implementation.

**Comment by stephenicus** [comment]
I resolved the issue by setting all the access modifiers for steps to public.
