### ISSUE TITLE
Chrome is not launching when i upgrade to the latest taiko version

### ISSUE THREAD

**Issue by poornadeem** [getgauge/gauge#2125]
I have upgraded my taiko version from 1.0.3 to 1.2.7 . also updated before scenario as
beforeScenario(async () => {

    if (process.env.host === "local") {
        await openBrowser({ headless: false, ignoreCertificateErrors: true, args: ['--no-sandbox', '--start-fullscreen', '--disable-web-security', '--disable-RendererCodeIntegrity'] })
        await setConfig({navigationTimeout : 3000000})
        await deleteCookies();
    } else if (process.env.host === "docker") {
        await openBrowser({ headless_chrome: true, ignoreCertificateErrors: true, args: ['--disable-setuid-sandbox','--no-sandbox','--start-fullscreen', '--disable-web-security'] })
        await deleteCookies();
    }
    
});

even then i see this issue as:
Error Message: Error: Chromium revision is not downloaded. Provide TAIKO_BROWSER_PATH or Install taiko again to download bundled chromium.
    Stacktrace:
    Error: Chromium revision is not downloaded. Provide TAIKO_BROWSER_PATH or Install taiko again to download bundled chromium.
        at BrowserFetcher.getExecutablePath (node_modules\taiko\lib\browserFetcher.js:237:13)
        at launchBrowser (node_modules\taiko\lib\browserLauncher.js:324:44)
        at module.exports.openBrowser (node_modules\taiko\lib\taiko.js:95:65)
        at module.exports.(anonymous function) (node_modules\taiko\lib\taiko.js:2622:36)
        at Object.beforeScenario (step_implementations\ui\browser.js:11:15)

Any suggestions on this?

**Comment by poornadeem** [comment]
@sriv  This issue is fixed. Thanks
