### ISSUE TITLE
Runner is not alive

### ISSUE THREAD

**Issue by poornadeem** [getgauge/gauge#2165]
When we run the scripts in gauge with js langauge we do see this issue as "runner is not alive" and tests are getting skipped

Version:
Gauge version: 1.4.1
Commit Hash: a82478a 

Plugins
-------
html-report (4.1.2)  
js (2.3.17)
json-report (0.3.6)  
reportportal (1.12.0)
screenshot (0.1.0)   
xml-report (0.2.3)   

Taiko version:
Version: 1.2.7 (Chromium: 88.0.4314.0) RELEASE

**Comment by sriv** [comment]
My guess is that something caused an error during the script run, which went unhandled causing the runner to crash.

Do you see anything in the log that might give a hint?

There isn't much info here to delve any deeper.

**Comment by poornadeem** [comment]
@sriv  Thanks for your reply. Please check this info and also attached the  gauge.log
 I see this error message when i run from local also.
Error:
Error Message: error reading from server: read tcp 127.0.0.1:57616->127.0.0.1:57615: wsarecv: An existing connection was forcibly closed by the remote host.
        Stacktrace: 
        
    Error Message: Runner is not Alive
    Stacktrace: 
    
  Error Message: Runner is not Alive
  Stacktrace: 
  

  Error Message: Runner is not Alive
  Stacktrace: 
  
Successfully generated html-report to => d:\latestframe\reports\html-report\index.html

Successfully generated json-report to => d:\latestframe\reports\json-report

Failed to kill Runner: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:57615: connectex: No connection could be made because the target machine actively refused it."
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

Total time taken: 7m53.061s
Updates are available. Run `gauge update -c` for more info.
Error: Tests failed.

**Comment by poornadeem** [comment]
[gauge.log](https://github.com/getgauge/gauge/files/7580587/gauge.log)

**Comment by poornadeem** [comment]
@sriv @NivedhaSenthil  can anyone have a look at this?.. due to this issue we were not able to proceed and blocked!. Thanks in Advance

**Comment by sriv** [comment]
From the logs, this is the error thrown from taiko:

```
Error: WebSocket is not open: readyState 3 (CLOSED)
```

This is a bit tricky to debug without a project where we can replicate this issue. Is there a sample project that you can share? I can try and replicate this issue.

**Comment by poornadeem** [comment]
@sriv  I will try to share the sample one.
By looking at this error await we should use before any action i checked my framework it looks good. any suggestion why we get this error as Error: WebSocket is not open: readyState 3 (CLOSED).

browser.js looks like:
beforeScenario(async () => {
    if (process.env.api_test_run === 'false') {
        await setConfig({ navigationTimeout: parseInt(process.env.test_timeout) });

        if (process.env.host === "local") {
            await openBrowser({ headless: headlessChrome, ignoreCertificateErrors: true, args: ['--no-sandbox', '--start-fullscreen', '--disable-web-security', '--disable-RendererCodeIntegrity'] })
            await deleteCookies();
        } else if (process.env.host === "docker") {
            await openBrowser({ headless_chrome: true, ignoreCertificateErrors: true, args: ['--disable-setuid-sandbox', '--no-sandbox', '--start-fullscreen', '--disable-web-security'] })
            await deleteCookies();
        }
    }
});

afterScenario(async () => {
    if (process.env.api_test_run === 'false') {
        await closeBrowser();
    }

});

beforeSpec(async () => {
    gauge.message(`Environment: ${process.env.environment}, SiteName: ${process.env.siteName}`);
});

gauge.customScreenshotWriter = async () => {
    const screenshotFilePath = path.join(process.env['gauge_screenshots_dir'], `screenshot-${process.hrtime.bigint()}.png`);
    await screenshot({ path: screenshotFilePath });
    return path.basename(screenshotFilePath);
};

afterStep(async () => {
    if (process.env.api_test_run === 'false') {
        gauge.screenshot();
    }
});

Any suggestions

**Comment by sankarasai18-gauge** [comment]
I am also facing this issue and blocked with using the automated tests with the below versions. Please help me to fix this issue ASAP.

`gauge -v
Gauge version: 1.2.1
Commit Hash: fa7918b

Plugins
-------
html-report (4.0.12)
js (2.3.17)
json-report (0.3.6)
reportportal (1.12.0)
screenshot (0.1.0)
taiko -v
Version: 1.2.5 (Chromium: 88.0.4314.0) RELEASE`

**Comment by zabil** [comment]
> I am also facing this issue and blocked with using the automated tests with the below versions. Please help me to fix this issue ASAP.

Is there any other info you can provide. Like when you started seeing this error? After an upgrade? How do you run these tests? What os are you using.

**Comment by sankarasai18-gauge** [comment]
Thanks @zabil for taking a looking this issue. Please find the below requested details.

ok sure, I have been using old versions of gauge (1.0.5) and used to get this issue and then it might be due to the old version so I upgraded to 1.2.1 and still facing the same issue.
I am trying to run the specs through jenkins which is setup in ubuntu box and also directly through the terminal. If I run the individual specs I don't get this issue and when I try to run a group of specs through sets (which has around 5-10 specs) or by passing all the 10 specs file through command line I get this issue.

Below are the errors I get in the terminal and in gauge.log

**Terminal Errors**
`Specification: specs/S47.spec
        Error Message: error reading from server: EOF
        Stacktrace: 
[runner: 1]         Error Message: Runner is not Alive
        Stacktrace: 
[runner: 1]     Error Message: Runner is not Alive
    Stacktrace: 
[runner: 1]   Error Message: Runner is not Alive
  Stacktrace: 
[runner: 1] 
Failed to kill runner. rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:33111: connect: connection refused"`

**gauge.log**
`26-11-2021 09:41:57.813 [js] [ERROR] at WebSocket.emit (node:events:369:20)
26-11-2021 09:41:57.813 [js] [ERROR] at Receiver.receiverOnMessage (/var/lib/jenkins/workspace/TestProject1/node_modules/ws/lib/websocket.js:970:20)
26-11-2021 09:41:57.813 [js] [ERROR] at Receiver.emit (node:events:369:20)
26-11-2021 09:41:57.813 [js] [ERROR] at Receiver.dataMessage (/var/lib/jenkins/workspace/TestProject1/node_modules/ws/lib/receiver.js:517:14)
26-11-2021 09:41:57.813 [js] [ERROR] at /var/lib/jenkins/workspace/TestProject1/node_modules/ws/lib/receiver.js:468:23
26-11-2021 09:41:57.813 [js] [ERROR] at /var/lib/jenkins/workspace/TestProject1/node_modules/ws/lib/permessage-deflate.js:308:9
26-11-2021 09:41:57.826 [Gauge] [ERROR] 
Failed Step: Click "Selecr" button
26-11-2021 09:41:57.826 [Gauge] [ERROR] Specification: specs/S47.spec
26-11-2021 09:41:57.826 [Gauge] [ERROR] Error Message: error reading from server: EOF
26-11-2021 09:41:57.826 [Gauge] [ERROR] Stacktrace: 
26-11-2021 09:41:57.826 [Gauge] [ERROR] Error Message: Runner is not Alive
26-11-2021 09:41:57.826 [Gauge] [ERROR] Stacktrace: 
26-11-2021 09:41:57.827 [Gauge] [ERROR] Error Message: Runner is not Alive
26-11-2021 09:41:57.827 [Gauge] [ERROR] Stacktrace: 
26-11-2021 09:41:57.827 [Gauge] [ERROR] Error Message: Runner is not Alive
26-11-2021 09:41:57.827 [Gauge] [ERROR] Stacktrace: 
26-11-2021 09:41:57.829 [Gauge] [ERROR] Failed to kill runner. rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:33111: connect: connection refused"
26-11-2021 09:43:33.330 [Gauge] [ERROR] `

**Comment by sriv** [comment]
@sankarasai18-gauge - something has caused the gauge-js runner to crash. It is not clear what, so it is a bit difficult to suggest what is a fix here, without having access to a sample project.

@poornadeem - I put your code in a fresh `js` project, and I see it is working ok. So I am afraid I need more information to suggest a workaround

One thing is clear though, this is not an isolated incident, and has been a point of concern for some time now. I'd like to fix the root cause - 

1. gauge-js (or any runner) should not crash when there is an error in user code.
2. in case of a crash, the cause of the error should be reported, rather than a generic stacktrace.

For the above case, I'd need help from the users - if you have some time, please try and provide cases where you see this occurring. This is something that would help immensely.

**Comment by zabil** [comment]
> in case of a crash, the cause of the error should be reported, rather than a generic stacktrace.

Adding to this. 

It's likely to be a problem with the page being tested. If it's a specific test that fails all the time it will be filtering it with a tag and running all the tests except that one to see if this happens.

**Comment by sankarasai18-gauge** [comment]
Thanks @sriv @zabil , Its randomly failing in different tests and pages and not always in the same pages/tests. Since its an internal project I am unable to share it here.

I came across thread (https://github.com/puppeteer/puppeteer/issues/4428#issuecomment-500178290) about **_browser.on('disconnected')_** and not sure whether this will fix the runner issue? 

There is  a similar issue (https://github.com/getgauge/taiko/discussions/1879#discussioncomment-484646) and got fixed by switching to headless mode.  But I am running the tests in headless mode through jenkins/terminal.

**Comment by poornadeem** [comment]
@zabil @sriv  found that whenever we see an timeout issue, after that seeing as "runner is not alive". we tried adding more time for elements and tried out.For navigation used as below:
await setConfig({navigationTimeout : 3000000})

For elements we use like:
await waitFor(
    $(`${departFlightPage.resultFlight()}`),
    process.env.test_timeout
  );
process.env.test_timeout =3000000 externally we give as.

I would like to get a suggestion when the timeout occurs why the runner is getting closed,any suggestions would be an great help?

**Comment by sankarasai18-gauge** [comment]
@zabil @sriv I tried with the below versions of gauge and taiko (1.0.7/1.0.5) and got a different error this time as below and not the above one **_Runner is not Alive_**. 
So any idea whats the root cause of the below issue?. Looks like **_Runner is not Alive_** is specific to latest versions of gauge/taiko and not the scripts 🤔 

> gauge -v
Gauge version: 1.0.7
Commit Hash: ed7b4fd6
Plugins
-------
html-report (4.0.12)
js (2.3.17)
json-report (0.3.6)
screenshot (0.1.0)
xml-report (0.2.3)
taiko -v
Version: 1.0.5 (Chromium: 81.0.3994.0) RELEASE

**gauge.log**
29-11-2021 09:40:53.923 [Gauge] [ERROR] Specification: specs/TR/scenarios/tr_s1.spec:18
29-11-2021 09:40:53.923 [Gauge] [ERROR] Error Message: rpc error: code = Unavailable desc = transport is closing
29-11-2021 09:40:53.923 [Gauge] [ERROR] Stacktrace: 
29-11-2021 09:40:53.924 [Gauge] [ERROR] Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:33185: connect: connection refused"
29-11-2021 09:40:53.924 [Gauge] [ERROR] Stacktrace: 
29-11-2021 09:40:53.924 [Gauge] [ERROR] Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:33185: connect: connection refused"
29-11-2021 09:40:53.924 [Gauge] [ERROR] Stacktrace:

**Comment by sriv** [comment]
The error message indicating that "Runner is not alive" was added later to explain the "rpc errors". The underlying cause is still the same, I believe.

**Comment by yicaifeitian** [comment]
Is this problem solved？ I use Python，also have this problem. Before this, it never appear. I try restart/shut off the mathine,it does not help.
qa@qadeMac-mini cedarhd-workplus-android-test % gauge run specs
Python: 3.8.9
Error occurred while waiting for runner process to finish.
Error : exit status 1

  Error Message: error reading from server: EOF
  Stacktrace: 
  

  Error Message: Runner is not Alive
  Stacktrace: 
  
Successfully generated html-report to => /Users/qa/Project/py/cedarhd-workplus/cedarhd-workplus-android-test/reports/html-report/index.html

Failed to kill Runner: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50546: connect: connection refused"
Specifications: 0 executed      0 passed        0 failed        0 skipped
Scenarios:      0 executed      0 passed        0 failed        0 skipped

Total time taken: 291ms

**Comment by poornadeem** [comment]
@yicaifeitian we still see this issue.

**Comment by reka18** [comment]
I am seeing this issue when running Java projects as well. `

`Failed to kill Runner: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:35303: connect: connection refused"`

![image](https://user-images.githubusercontent.com/30000481/157332898-e27086f5-67a6-4373-ab96-915662855014.png)

**Comment by Shil-Patil** [comment]
I was also facing the same issue.
But now resolved some mistake in step implementation.  Later resolved.
node version: v16.13.1
taiko: 1.2.8

Old code:
const headless = process.env.headless_chrome.toLowerCase() === 'true';
beforesuit(async () => {
    await openBrowser({
        headless: headless
    })
});
afterSuite(async () => {
    await closeBrowser();
});
Error:
![image](https://user-images.githubusercontent.com/68562735/158534029-e4f7981c-8fa9-4861-b34a-a43111183b49.png)

Solution: changed spelling of "beforeSuite "

**Comment by singhverse** [comment]
Experiencing the same issue here on my mac while using gauge-js.

Anyone got a workaround or a temporary fix?
