### ISSUE TITLE
WARN "could not create Dir using" message when the project is run from Reflections

### ISSUE THREAD

**Issue by AhmetRufai** [getgauge/gauge#2427]
When the project is run with gauge, the following warning message appears:
`17:04:27.017 [ForkJoinPool.commonPool-worker-1] WARN org.reflections.Reflections -- could not create Dir using com.thoughtworks.gauge.scan.ClasspathScanner$1@35e07ec4 from url file:/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home!/jdk.zipfs. skipping.
java.lang.NullPointerException: Cannot invoke "java.io.File.isDirectory()" because "file" is null
	at com.thoughtworks.gauge.scan.ClasspathScanner$1.createDir(ClasspathScanner.java:48)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:103)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:95)
	at org.reflections.Reflections.lambda$scan$2(Reflections.java:176)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
17:04:27.017 [ForkJoinPool.commonPool-worker-5] WARN org.reflections.Reflections -- could not create Dir using com.thoughtworks.gauge.scan.ClasspathScanner$1@35e07ec4 from url file:/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home!/java.compiler. skipping.
java.lang.NullPointerException: Cannot invoke "java.io.File.isDirectory()" because "file" is null
	at com.thoughtworks.gauge.scan.ClasspathScanner$1.createDir(ClasspathScanner.java:48)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:103)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:95)
	at org.reflections.Reflections.lambda$scan$2(Reflections.java:176)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)`

I have shared only a few of the WARNs. I see many WARN messages like this one.

Is Gauge not compatible with java version 17?

Some of the versions I use:
Java: 17.0.5
Gauge: 1.5.6
Gauge java: 0.10.3
Spring boot: 3.1.5
gauge-maven-plugin: 1.6.1
maven-compiler-plugin: 3.11.0

Note: WARN messages do not prevent me from running my tests

**Comment by haroon-sheikh** [comment]
Hi @AhmetRufai The issue is not related to gauge or Java version you’re running on. And as you’ve described it shouldn’t affect running of gauge tests. 

This is to do with the reflections dependency and reported issue here https://github.com/ronmamo/reflections/issues/80

There are a couple of workarounds mentioned in the thread above but the simplest is change the log level for reflections package  https://github.com/ronmamo/reflections/issues/80#issuecomment-369310174

Or if you want to disable all the logs you can simply add this nop dependency to your maven project. 

```xml
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-nop</artifactId>
    <version>2.0.9</version>
    <scope>test</scope>
</dependency>
```

**Comment by AhmetRufai** [comment]
Thank you so much @haroon-sheikh

**Comment by AhmetRufai** [comment]
Thank you so much @haroon-sheikh
