### ISSUE TITLE
gauge fails to generate HTML report

### ISSUE THREAD

**Issue by rajiesh** [getgauge/gauge#246]
While running our go cd functional tests observed an issue in gauge failing to generate the HTML report, below exception noticed in the logs

```
21:43:11.825 [Html Report Plugin] : runtime: checkdead: find g 1 in status 1
21:43:11.825 [Html Report Plugin] : fatal error: checkdead: runnable g
21:43:11.825 [Html Report Plugin] : 
21:43:11.825 [Html Report Plugin] : runtime stack:
21:43:11.825 [Html Report Plugin] : runtime.throw(0x8b4e1c)
21:43:11.825 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:491 +0xad
21:43:11.826 [Html Report Plugin] : checkdead()
21:43:11.826 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:2828 +0x287
21:43:11.826 [Html Report Plugin] : mput(0x8c08a0)
21:43:11.826 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:3175 +0x47
21:43:11.826 [Html Report Plugin] : stopm()
21:43:11.826 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:1176 +0xea
21:43:11.826 [Html Report Plugin] : findrunnable(0xc208012000)
21:43:11.826 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:1487 +0x562
21:43:11.826 [Html Report Plugin] : schedule()
21:43:11.826 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:1575 +0x151
21:43:11.826 [Html Report Plugin] : runtime.park_m(0xc208000120)
21:43:11.827 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:1654 +0x113
21:43:11.827 [Html Report Plugin] : runtime.mcall(0x432dd4)
21:43:11.827 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:186 +0x5a
21:43:11.827 [Html Report Plugin] : 
21:43:11.827 [Html Report Plugin] : goroutine 1 [runnable]:
21:43:11.827 [Html Report Plugin] : net.(*pollDesc).Wait(0xc208010450, 0x72, 0x0, 0x0)
21:43:11.827 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
21:43:11.827 [Html Report Plugin] : net.(*pollDesc).WaitRead(0xc208010450, 0x0, 0x0)
21:43:11.827 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
21:43:11.827 [Html Report Plugin] : net.(*netFD).Read(0xc2080103f0, 0xc20805e000, 0x2000, 0x2000, 0x0, 0x7f9973b52a70, 0xc20808f638)
21:43:11.827 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
21:43:11.827 [Html Report Plugin] : net.(*conn).Read(0xc208032018, 0xc20805e000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
21:43:11.827 [Html Report Plugin] : 	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
21:43:11.827 [Html Report Plugin] : github.com/getgauge/html-report/listener.(*GaugeListener).Start(0xc20801e7c0)
21:43:11.827 [Html Report Plugin] : 	/tmp/src/github.com/getgauge/html-report/listener/gaugeListener.go:54 +0xc7
21:43:11.828 [Html Report Plugin] : main.createExecutionReport()
21:43:11.828 [Html Report Plugin] : 	/Applications/Go Agent.app/pipelines/html-report/htmlReport.go:87 +0x1d4
21:43:11.828 [Html Report Plugin] : main.main()
21:43:11.828 [Html Report Plugin] : 	/Applications/Go Agent.app/pipelines/html-report/main.go:28 +0xd2
21:43:24.224 [ERROR] Unable to connect to plugin Html Report 1.1.0. [Warning] Failed to send message to plugin: %!d(string=html-report)  write tcp 127.0.0.1:37158: connection reset by peer
21:43:24.224 
21:43:24.224 [ERROR] Failed to kill plugin Html Report 1.1.0. os: process already finished
21:43:24.224 
```

Please check this link for the failed build
https://build.go.cd/go/tab/build/detail/acceptance-gauge/61/RunAcceptanceSpecs-priority/1/firefox-split-runInstance-6

Issue is intermittent, could not be reproduced consistently, report generated successfully after rerun of the tests

**Comment by mahendrakariya** [comment]
@rajiesh Are you still facing this issue after updating to Gauge v0.3.2 and html reports v2.0.0?

**Comment by rajiesh** [comment]
No @mahendrakariya have not observed the issue after the upgrade, should be good to close this issue.

**Comment by mahendrakariya** [comment]
Cool. Thanks!
