### ISSUE TITLE
invalid memory address error thrown on linux

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#275]
I'm getting the following error when attempting to run the gauge tests. `gauge specs/`

```bash
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x693b7f]

goroutine 14 [running]:
gopkg.in/fsnotify%2ev1.(*Watcher).isClosed(0x0, 0x0)
	/tmp/src/gopkg.in/fsnotify.v1/inotify.go:64 +0x1f
gopkg.in/fsnotify%2ev1.(*Watcher).Close(0x0, 0x0, 0x0)
	/tmp/src/gopkg.in/fsnotify.v1/inotify.go:73 +0x3a
gopkg.in/fsnotify%2ev1.(*Watcher).isClosed(0x0, 0x28)
	/tmp/src/gopkg.in/fsnotify.v1/inotify.go:64 +0x1f
gopkg.in/fsnotify%2ev1.(*Watcher).Add(0x0, 0xc208064630, 0x28, 0x0, 0x0)
	/tmp/src/gopkg.in/fsnotify.v1/inotify.go:92 +0x83
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).addDirToFileWatcher(0xc20809e240, 0x0, 0xc208064630, 0x28)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:316 +0x4d
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges(0xc20809e240)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:309 +0x627
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).MakeListOfAvailableSteps
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:46 +0x32

goroutine 1 [select]:
github.com/getgauge/gauge/execution.startApi(0xc2080a2090)
	/tmp/src/github.com/getgauge/gauge/execution/execute.go:70 +0x372
github.com/getgauge/gauge/execution.ExecuteSpecs(0xc20800a000, 0xc20800a010, 0x1, 0x1)
	/tmp/src/github.com/getgauge/gauge/execution/execute.go:26 +0x114
main.main()
	/Applications/Go Agent.app/pipelines/Packaging/gauge.go:132 +0x6b7

goroutine 6 [chan receive]:
github.com/getgauge/gauge/parser.ParseSpecFiles(0xc208074500, 0xa, 0x10, 0xc208098d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:38 +0x279
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).getParsedSpecs(0xc20809e240, 0xc208074500, 0xa, 0x10, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:130 +0x136
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).initSpecsCache(0xc20809e240)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:61 +0x199
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).MakeListOfAvailableSteps(0xc20809e240, 0xc208098a20)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:52 +0x83
github.com/getgauge/gauge/api.StartAPIService(0x0, 0xc2080998c0)
	/tmp/src/github.com/getgauge/gauge/api/api.go:72 +0x521
created by github.com/getgauge/gauge/execution.startApi
	/tmp/src/github.com/getgauge/gauge/execution/execute.go:69 +0x13c

goroutine 7 [select]:
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout(0xc2080998e0, 0x0, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:91 +0x329
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).HandleMultipleConnections(0xc2080998e0)
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:139 +0x28
created by github.com/getgauge/gauge/api.StartAPIService
	/tmp/src/github.com/getgauge/gauge/api/api.go:66 +0x487

goroutine 8 [syscall]:
syscall.Syscall(0x0, 0x6, 0xc2080a8000, 0x8000, 0x1, 0x8000, 0x40e56f)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x6, 0xc2080a8000, 0x8000, 0x8000, 0xbbc6e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x6, 0xc2080a8000, 0x8000, 0x8000, 0x7bc140, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc208046058, 0xc2080a8000, 0x8000, 0x8000, 0xc2080a8000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc208046058, 0xc2080a8000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x91
io.Copy(0x2b75de187b78, 0xbb2468, 0x2b75de185c20, 0xc208046058, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:362 +0x1f6
os/exec.func·003(0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc208098620)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:329 +0xb6d

goroutine 9 [chan receive]:
github.com/getgauge/gauge/runner.func·002()
	/tmp/src/github.com/getgauge/gauge/runner/runner.go:183 +0x59
created by github.com/getgauge/gauge/runner.startRunner
	/tmp/src/github.com/getgauge/gauge/runner/runner.go:186 +0x5cd

goroutine 10 [syscall]:
syscall.Syscall6(0x3d, 0xc82, 0xc20801ad3c, 0x0, 0xc20805c1b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0xc82, 0xc20801ad3c, 0x0, 0xc20805c1b0, 0x90, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0xc82, 0xc20801ad84, 0x0, 0xc20805c1b0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc2080989c0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc2080989c0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc208084000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:364 +0x23c
github.com/getgauge/gauge/runner.func·003()
	/tmp/src/github.com/getgauge/gauge/runner/runner.go:211 +0x44
created by github.com/getgauge/gauge/runner.waitAndGetErrorMessage
	/tmp/src/github.com/getgauge/gauge/runner/runner.go:216 +0x11c

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc2080a03e0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080a03e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080a0380, 0x0, 0x2b75de185c70, 0xc208032b58)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208046488, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208046488, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:244 +0x4c
github.com/getgauge/gauge/conn.func·002()
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:82 +0x3f
created by github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:89 +0x1b1

goroutine 15 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc208062b90, 0x45, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 16 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc208062cd0, 0x4b, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 17 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc208062e60, 0x41, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 18 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc20803f780, 0x39, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 19 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc20803f840, 0x39, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 20 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc20803f900, 0x3c, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 21 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc208063090, 0x43, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 22 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc20803f9c0, 0x3b, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 23 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc20803fac0, 0x38, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 24 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc20803fb80, 0x3d, 0xc208098d80, 0xc208036660, 0xc2080364e0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 25 [runnable]:
github.com/getgauge/gauge/api/infoGatherer.func·001()
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:291
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:300 +0x270
```

**Comment by haroon-sheikh** [comment]
looks related to issue https://github.com/getgauge/gauge/issues/242

**Comment by mahendrakariya** [comment]
Could you please give us details about which Linux distro you are using? On running what command did you get this error?

**Comment by haroon-sheikh** [comment]
CentOS release 5.9 (Final)
and running `gauge specs/` throws the above error.

**Comment by mahendrakariya** [comment]
Could you please tell us the output of the command `ulimit -a`?

**Comment by haroon-sheikh** [comment]
```bash
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

**Comment by mahendrakariya** [comment]
This seems to be similar to #222.

Can you please increase the open file limits by running the command `ulimit -n 2048` and then try `gauge specs`?

**Comment by haroon-sheikh** [comment]
@mahendrakariya Ive done that and still the same error.

**Comment by mahendrakariya** [comment]
@haroon-sheikh Are you still facing this issue with Gauge v0.3.2?

**Comment by mahendrakariya** [comment]
Thanks a lot @haroon-sheikh!!
