### ISSUE TITLE
Fatal error in Intellij IDEA 15.0.2

### ISSUE THREAD

**Issue by xpavlic4** [getgauge/gauge#283]
Stacktrace:

Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 337,4,main] 7100350
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 15.0.2#IU-143.1184.17, eap:false,6,main] 23119223
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1047)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:178)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:794)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:268)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:259)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.getQualifiedName(PsiAnnotationImpl.java:96)
	at com.thoughtworks.gauge.util.StepUtil.isGaugeAnnotation(StepUtil.java:198)
	at com.thoughtworks.gauge.util.StepUtil.getGaugeStepAnnotationValues(StepUtil.java:178)
	at com.thoughtworks.gauge.util.StepUtil.getGaugeStepAnnotationValues(StepUtil.java:160)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.shouldFindUsages(ReferenceSearch.java:58)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:42)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:38)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.psi.search.QuerySearchRequest.runQuery(QuerySearchRequest.java:58)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.a(PsiSearchHelperImpl.java:626)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:587)
	at com.intellij.find.findUsages.FindUsagesManager$2.generate(FindUsagesManager.java:394)
	at com.intellij.find.findUsages.FindUsagesManager$1$1.run(FindUsagesManager.java:292)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.find.findUsages.FindUsagesManager$1.run(FindUsagesManager.java:288)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by mahendrakariya** [comment]
@xpavlic4 Thanks for reporting this. 
There are a few issues with IntelliJ 15 and we are working on it. We will be releasing the IntelliJ 15 compatible Gauge plugin soon.

**Comment by mahendrakariya** [comment]
@xpavlic4 We have released [v0.1.0](https://plugins.jetbrains.com/plugin/7535?pr=idea) of Gauge plugin with support for IntelliJ version 15. Please update the plugin. 

Please update Gauge as well. We have also released [v0.3.0](https://groups.google.com/forum/#!topic/getgauge/qEhw1pcDE3Y).

I will close this issue for now. Feel free to reopen in case it's not working for you.
