### ISSUE TITLE
Null Pointer Exception while executing the spec

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#324]
null
java.lang.NullPointerException
at com.thoughtworks.gauge.util.GaugeUtil.moduleDirPath(GaugeUtil.java:100)
at com.thoughtworks.gauge.util.GaugeUtil.moduleDir(GaugeUtil.java:96)
at com.thoughtworks.gauge.execution.GaugeRunConfiguration.addFlags(GaugeRunConfiguration.java:124)
at com.thoughtworks.gauge.execution.GaugeRunConfiguration.access$000(GaugeRunConfiguration.java:54)
at com.thoughtworks.gauge.execution.GaugeRunConfiguration$1.startProcess(GaugeRunConfiguration.java:97)
at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:389)
at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:161)
at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:346)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Expected behavior
Should be able to run without an exception

### Actual behavior
Getting a null pointer exception

### Steps to reproduce
1. Opened the issues project in IDE and on running Specifications I get the above error

### Gauge version
```
0.4.0
```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#133
