### ISSUE TITLE
Nullpointer exception with Java Gauge plugin in IntelliJ on changing a step

### ISSUE THREAD

**Issue by kbangur** [getgauge/gauge#377]
### Expected behavior
A parse error should be shown if step is incorrectly implemented

### Actual behavior
Getting null pointer exception

### Steps to reproduce
1. Create a spec as follows-
```
Login as Admin
=============

Scenario 1
----------
* TitleIs "ABC"

2. Implementation

@com.thoughtworks.gauge.Step("TitleIs <title>")
public void titleIs(String title) throws Exception {
	...
}
```
3. Change Step from upper case to lower case in Scenario 1 as below and try to save
```
Scenario 1
----------
* titleIs "ABC"
```
4. Here is the error stack trace : 
```
java.lang.NullPointerException
	at com.thoughtworks.gauge.util.StepUtil.isMatch(StepUtil.java:139)
	at com.thoughtworks.gauge.util.StepUtil.findStepImplementationMethod(StepUtil.java:122)
	at com.thoughtworks.gauge.util.StepUtil.findStepReference(StepUtil.java:62)
	at com.thoughtworks.gauge.util.StepUtil.findStepImpl(StepUtil.java:55)
	at com.thoughtworks.gauge.util.StepUtil.isImplementedStep(StepUtil.java:213)
	at com.thoughtworks.gauge.annotator.StepAnnotator.createWarning(StepAnnotator.java:44)
	at com.thoughtworks.gauge.annotator.StepAnnotator.annotate(StepAnnotator.java:35)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:162)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:354)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

### Gauge version
```
Gauge version: 0.4.0

Plugins
-------
html-report (2.1.0)
java (0.4.0)
```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#149
