### ISSUE TITLE
Duplicate concept definition throws exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#381]
**Expected Behavior**
Should give a parse error of duplicate definition

**Actual Behavior**
Throws an exception along with the parse error.
The same exception also occurs for `[ParseError] /Users/sswaroop/work/issue_samples/java/specs/concepts/one.cpt:1: Concept should have atleast one step`

**Steps to reproduce**
1. Create a spec
```
one
===

In between
----------
* Concept Heading
```

2. Create a concept
```
# Concept Heading
* step1
* step2 "1"
* step2 "2"

# step2 <something>
* step1
* step4 <something>
```

3. Create another concept
```
# step2 <something>
* step1
* step4 <something>
```

4. Run the spec
5. One would get the following exception.
```
[ParseError] /Users/sswaroop/work/issue_samples/java/specs/concepts/two.cpt:1: Duplicate concept definition found => 'step2 <something>'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x267ec8]

goroutine 49 [running]:
panic(0x64e4a0, 0x820b8e090)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/getgauge/gauge/gauge.(*Specification).processConceptStep(0x820ec4100, 0x820dfc8c0, 0x0)
	/tmp/src/github.com/getgauge/gauge/gauge/specification.go:81 +0x48
github.com/getgauge/gauge/gauge.(*Specification).ProcessConceptStepsFrom(0x820ec4100, 0x0)
	/tmp/src/github.com/getgauge/gauge/gauge/specification.go:72 +0x154
github.com/getgauge/gauge/parser.(*SpecParser).CreateSpecification(0x820d9f540, 0x820d91f80, 0x4, 0x4, 0x0, 0x4, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/specparser.go:248 +0x717
github.com/getgauge/gauge/parser.(*SpecParser).Parse(0x820d9f540, 0x820d9f500, 0x31, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/specparser.go:72 +0xb6
github.com/getgauge/gauge/parser.parseSpec(0x7fff5fbff036, 0x46, 0x0, 0x820dd09c0, 0x820dd0960)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:54 +0x2ea
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x19b
```

**Comment by kashishm** [comment]
Available in nightly > 26/05/2016
