### ISSUE TITLE
Negative spec count in exec summary causes Invalid Protocol Buffer exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#394]
### Expected behavior
Scenario count should be positive with no exception appearing to the user

### Actual behavior
Scenario count is -ve with exception

### Steps to reproduce
Do not know how to replicate this. Please find the stack trace
```
/usr/local/bin/gauge --simple-console /Users/sswaroop/work/gauge-test-apps/projects/web-apps-e2e/specs/spring-mvc/simple.spec
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:70)
	at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1082)
	at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:1149)
	at com.google.protobuf.CodedInputStream.readRawVarint64SlowPath(CodedInputStream.java:778)
	at com.google.protobuf.CodedInputStream.readRawVarint64(CodedInputStream.java:770)
	at com.thoughtworks.gauge.connection.GaugeConnection.getMessageLength(GaugeConnection.java:51)
	at com.thoughtworks.gauge.connection.GaugeConnection.getAPIResponse(GaugeConnection.java:150)
	at com.thoughtworks.gauge.connection.GaugeConnection.getStepValue(GaugeConnection.java:190)
	at com.thoughtworks.gauge.connection.GaugeConnection.getStepValue(GaugeConnection.java:176)
	at com.thoughtworks.gauge.scan.StepsScanner.buildStepRegistry(StepsScanner.java:47)
	at com.thoughtworks.gauge.scan.StepsScanner.scan(StepsScanner.java:39)
	at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:39)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
Exception in thread "main" java.lang.NullPointerException
	at com.thoughtworks.gauge.registry.StepRegistry.addStepImplementation(StepRegistry.java:29)
	at com.thoughtworks.gauge.scan.StepsScanner.buildStepRegistry(StepsScanner.java:48)
	at com.thoughtworks.gauge.scan.StepsScanner.scan(StepsScanner.java:39)
	at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:39)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
[ValidationError] /Users/sswaroop/work/gauge-test-apps/projects/web-apps-e2e/specs/spring-mvc/simple.spec:5: Connection closed [127.0.0.1:63346] cause: EOF => 'Demo of concpet "simple"'
[ValidationError] /Users/sswaroop/work/gauge-test-apps/projects/web-apps-e2e/specs/spring-mvc/simple.spec:6: write tcp 127.0.0.1:63343->127.0.0.1:63346: use of closed network connection => 'to replicate goto "http://localhost:8080/spring-mvc-showcase/#simple"'
[ValidationError] /Users/sswaroop/work/gauge-test-apps/projects/web-apps-e2e/specs/spring-mvc/simple.spec:7: write tcp 127.0.0.1:63343->127.0.0.1:63346: use of closed network connection => 'click "GET/simple"'
process /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/bin/java with pid 15441 quit unexpectedly. exit status 1
  Failed to initialize suite datastore. Error: write tcp 127.0.0.1:63343->127.0.0.1:63346: use of closed network connection
Successfully generated html-report to => /Users/sswaroop/work/gauge-test-apps/projects/web-apps-e2e/reports/html-report
Specifications:	-1 executed	-1 passed	0 failed	1 skipped
Scenarios:	0 executed	0 passed	0 failed	1 skipped

Total time taken: 28ms

Process finished with exit code 1

```

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-09

Plugins
-------
html-report (2.1.1.nightly-2016-05-10)
java (0.4.0.nightly-2016-05-09)
ruby (0.2.0.nightly-2016-05-09)
xml-report (0.1.2.nightly-2016-05-09)
```

**Comment by mahendrakariya** [comment]
Spec / scenario count in execution summary should never be negative. #439 addresses this. Since that issue is fixed, this issue is not valid anymore.

**Comment by mahendrakariya** [comment]
@sguptatw I am closing this for now since its not valid. Feel free to reopen in case you see this again.
