### ISSUE TITLE
Getting a null pointer exception, after gauge process died

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#429]
### Expected behavior
After Gauge process dies, if we try to implement a step, should get a more meaningful message and the step should not be implemented.

### Actual behavior
```
null
java.lang.NullPointerException
	at com.thoughtworks.gauge.util.StepUtil.isMatch(StepUtil.java:136)
	at com.thoughtworks.gauge.util.StepUtil.findStepImplementationMethod(StepUtil.java:119)
	at com.thoughtworks.gauge.util.StepUtil.findStepReference(StepUtil.java:59)
	at com.thoughtworks.gauge.util.StepUtil.findStepImpl(StepUtil.java:52)
	at com.thoughtworks.gauge.util.StepUtil.isImplementedStep(StepUtil.java:212)
	at com.thoughtworks.gauge.annotator.StepAnnotator.createWarning(StepAnnotator.java:47)
	at com.thoughtworks.gauge.annotator.StepAnnotator.annotate(StepAnnotator.java:35)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:135)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:99)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```
### Steps to reproduce
1. Create a spec
```
Something
=========

     ||
     |-------|
     |       |
Scenario Heading
----------------
* Step that takes a table1 <dynamic>
* s"abc"
* s"def"
```
2. execute the spec. Get an exception
3. Now try various operations and would get a null pointer

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-30

Plugins
-------
html-report (2.1.1.nightly-2016-05-30)
java (0.4.1.nightly-2016-05-30)
```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#154
