### ISSUE TITLE
Getting the following exception when hooks are executed with execution context in debug mode

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#445]
### Expected behavior
I should be able to execute the hooks without an exception

### Actual behavior
Getting the following exception while debugging
```
Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@60d2f22a Current thread: Thread[ApplicationImpl pooled thread 18,4,Idea Thread Group] 402854534 SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.1.2#IC-145.972.3 IDEA, eap:false, os:Mac OS X 10.10.5, java-version:JetBrains s.r.o 1.8.0_76-release-b162,6,main] 1238596953

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1115)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1099)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1091)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:600)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:354)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:183)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:44)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:40)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
	at com.intellij.find.findUsages.FindUsagesHandler.findReferencesToHighlight(FindUsagesHandler.java:174)
	at com.intellij.find.findUsages.JavaFindUsagesHandler.findReferencesToHighlight(JavaFindUsagesHandler.java:245)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:156)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:144)
	at com.intellij.debugger.impl.DebuggerContextUtil.findNearest(DebuggerContextUtil.java:102)
	at com.intellij.debugger.engine.DefaultSourcePositionProvider.getSourcePositionForLocalVariable(DefaultSourcePositionProvider.java:157)
	at com.intellij.debugger.engine.DefaultSourcePositionProvider.computeSourcePosition(DefaultSourcePositionProvider.java:57)
	at com.intellij.debugger.engine.SourcePositionProvider.getSourcePosition(SourcePositionProvider.java:44)
	at com.intellij.debugger.engine.JavaValue$4$1.run(JavaValue.java:450)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
	at com.intellij.debugger.engine.JavaValue$4.contextAction(JavaValue.java:442)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Steps to reproduce
1. Create a spec
2. Add hooks with execution context
```
    @AfterScenario
    public void AfterScenario1(ExecutionContext context) throws Exception {
        String scenarioName = context.getCurrentScenario().getName().toString();
        Gauge.writeMessage("after scenario "+scenarioName);
    }
```
3. Execute the spec in debug mode.
4. We get the exception.

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by mahendrakariya** [comment]
This issue was moved to getgauge/Intellij-Plugin#158
