### ISSUE TITLE
Getting an exception when navigating to the definition of a step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#449]
**Expected behavior**
Should be able to navigate without an exception

**Actual behavior**
```
String index out of range: 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.thoughtworks.gauge.findUsages.StepCollector.cleanText(StepCollector.java:55)
	at com.thoughtworks.gauge.findUsages.StepCollector.getSteps(StepCollector.java:47)
	at com.thoughtworks.gauge.findUsages.StepCollector.collect(StepCollector.java:34)
	at com.thoughtworks.gauge.findUsages.ImplUsageProvider.isImplicitUsage(ImplUsageProvider.java:21)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isImplicitUsage(UnusedSymbolUtil.java:53)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isMethodReferenced(UnusedSymbolUtil.java:145)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.processMethod(PostHighlightingVisitor.java:446)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.processIdentifier(PostHighlightingVisitor.java:260)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.collectHighlights(PostHighlightingVisitor.java:197)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl$3.run(HighlightVisitorImpl.java:185)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:306)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Steps to replicate**
1. Create a concept
```
This is a concept file with following syntax for each concept.
# Concept Heading
* step1
* step1
This is a concept file with following syntax for each concept.
# Concept Heading1sdf
* step1
* to
```
2. with implementation
```
    @Step("step1")
    public void implementation2() throws Exception {
        throw new Exception("ghjsdf");
    }
```
3. From the spec file use `cmd b` and goto the definition. one would get the exception.

**Version**
```
Gauge version: 0.4.1.nightly-2016-06-08

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by BugDiver** [comment]
This issue was moved to getgauge/Intellij-Plugin#161

**Comment by BugDiver** [comment]
This issue was moved to getgauge/Intellij-Plugin#162
