### ISSUE TITLE
Gauge process is getting killed when NumberFormatException is thrown

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#455]
**Expected Behavior**
Even if an exception is thrown gauge process should not get killed.

**Actual Behavior**
```
# spec else

     |something|
     |---------|
     |a        |
  ## here
java.lang.NumberFormatException: For input string: "a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.thoughtworks.gauge.execution.StringToIntegerConverter.convert(TypeConverter.java:30)
	at com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:96)
	at com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:80)
	at com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:61)
	at com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
	at com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:42)
	at com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:31)
	at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:34)
	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:72)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)
java.lang.NumberFormatException: For input string: "a"
            
            Failed Step: fail if 5<something>
            Specification: specs/aSpec.spec
            Error Message: Connection closed [127.0.0.1:55273] cause: EOF
            Stacktrace: 
            
            Error Message: write tcp 127.0.0.1:55270->127.0.0.1:55273: use of closed network connection
            Stacktrace: 
            
    Error Message: write tcp 127.0.0.1:55270->127.0.0.1:55273: use of closed network connection
    Stacktrace: 
    
  Error Message: write tcp 127.0.0.1:55270->127.0.0.1:55273: use of closed network connection
  Stacktrace: 
  

Failed to initialize spec datastore. Error: write tcp 127.0.0.1:55270->127.0.0.1:55273: use of closed network connection
# Specification Heading

Failed to initialize spec datastore. Error: write tcp 127.0.0.1:55270->127.0.0.1:55273: use of closed network connection
# one

# ppp
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:55270->127.0.0.1:55273: use of closed network connection

  Error Message: write tcp 127.0.0.1:55270->127.0.0.1:55273: use of closed network connection
  Stacktrace: 
  
Unable to connect to plugin Html Report 2.1.1. proto: required field "SuiteExecutionResult.SuiteResult.SpecResults.ProtoSpec.Items.TableDrivenScenario.Scenarios.ScenarioItems.Concept.Steps.Step.StepExecutionResult.PostHookFailure.StackTrace" not set

Specifications:	1 executed	0 passed	1 failed	3 skipped
Scenarios:	1 executed	0 passed	1 failed	8 skipped

Total time taken: 122ms

Process finished with exit code 1

```

**Steps to replicate**
1. Create a spec
```
spec else
=========
tags: top head

|something|
|--|
|a|

here
----

tags: scenario3 ppp a b c d e f g h i j k l m n o p q r s t u v w x y z
* Concept to fail<something>

This is the second scenario in this specification

Here's a step that takes a table
```
2. Create a concept
```
This is a concept file with following syntax for each concept.
# Concept Heading
* step1
* step1
This is a concept file with following syntax for each concept.
# Concept Heading1sdf
* step1
* to
# Concept to fail<something>
* fail if 5<something>
```
3. Give the implementation
```
    @Step("fail if 5<something>")
    public void implementation7(int arg0) throws Exception {
        if (arg0 == 5)
            throw new Exception("it is 5");
    }
```
4. Run the specs 
5. Getting the above exception.

**Version**
```
Gauge version: 0.5.1.nightly-2016-06-14

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-14)
```

**Comment by apoorvam** [comment]
This issue was moved to getgauge/gauge-java#58
