### ISSUE TITLE
running gauge --docs m2h is giving an exception

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge#464]
_From @sguptatw on June 20, 2016 8:58_

**Expected behavior**
If the user specifies `gauge --docs m2h` then it should take a default specs folder.

**Actual behavior**
It is throwing an exception
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x2c4d]

goroutine 1 [running]:
panic(0x65a5e0, 0x820ba40b0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
main.main()
	/Users/stechops/Library/Application Support/Go Agent/pipelines/Gauge-Nightly/gauge.go:152 +0xc0d
```
**Version**
```
Gauge version: 0.5.1.nightly-2016-06-16

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-16)
m2h (0.0.1)
xml-report (0.1.2.nightly-2016-05-27)
```

_Copied from original issue: getgauge/M2H#1_

**Comment by BugDiver** [comment]
@sguptatw ```gauge --docs m2h``` takes ```specs``` directory as default. The above ```panic error``` was because of issue unhandled in gauge-core. It's fixed in https://github.com/getgauge/gauge/commit/e101bff979ac58f25738eae118b8a46ab5a3b2e0.
Fix should be availabe in nightly >= 22-06-2016.
