### ISSUE TITLE
Gauge process getting killed when editing a concept

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#466]
**Expected behavior**
Should not get an exception

**Actual behavior**
Getting the following exception
```
:42:02 PM Exception occurred in Gauge plugin: Please log an issue here with the following details and reload the project.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x28ecb3]

goroutine 8 [running]:
panic(0x65a5e0, 0x820ba2090)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/getgauge/gauge/parser.(*ConceptParser).processConceptStep(0x820f51ca0, 0x820f29b00, 0x82118d9f0, 0x4a, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:166 +0x3a3
github.com/getgauge/gauge/parser.(*ConceptParser).createConcepts(0x820f51ca0, 0x820dcc5c0, 0x8, 0x8, 0x82118d9f0, 0x4a, 0x0, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:84 +0xa70
github.com/getgauge/gauge/parser.(*ConceptParser).Parse(0x820f51ca0, 0x82118dc70, 0x4c, 0x82118d9f0, 0x4a, 0x0, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:42 +0x144
github.com/getgauge/gauge/parser.(*ConceptParser).ParseFile(0x820f51ca0, 0x82118d9f0, 0x4a, 0x0, 0x0, 0x0, 0x82118da32)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:51 +0x36c
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).onConceptFileModify(0x820d40870, 0x82118d9f0, 0x4a)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:191 +0x1bf
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).onFileModify(0x820d40870, 0x820bec7e0, 0x82118d9f0, 0x4a)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:238 +0x9a
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).onFileAdd(0x820d40870, 0x820bec7e0, 0x82118d9f0, 0x4a)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:231 +0x83
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).handleEvent(0x820d40870, 0x82118d9f0, 0x4a, 0x1, 0x820bec7e0)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:267 +0x28e
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges.func1(0x820bec7e0, 0x820d40870)
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:292 +0x124
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges
	/tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:297 +0x1e2
```
* Idea version: 2016.1.2
* API version: IC-145.972
* Plugin version: 0.2.1
* Gauge version: 0.5.1.nightly-2016-06-22
```

**Steps to replicate**
1. Create a spec with a few steps
2. Create a concept with newline in the first step
```

# Concept Headin7<a>
* step2

* step2

# testinghjk "sdf"

* step1
* step1
```
3. Save and we get the following exception

**Comment by kashishm** [comment]
If the text in the concept file is

```
# Concept Heading37a
* step1
* step2

# testinghjk
|sdfsdf|
|----|
|wer|

* Vowels in English language are "aeiou".
* step1

sdfsdfsdf
```
then we get the following error

```
panic: runtime error: index out of range

goroutine 19 [running]:
github.com/getgauge/gauge/parser.(*ConceptParser).processTableHeader(0xc8201fdca0, 0xc820154d80)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/parser/conceptParser.go:178 +0x170
github.com/getgauge/gauge/parser.(*ConceptParser).createConcepts(0xc8201fdca0, 0xc820166400, 0x9, 0x10, 0xc82030d380, 0x3d, 0x0, 0x0, 0x0, 0x0)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/parser/conceptParser.go:95 +0xf0d
github.com/getgauge/gauge/parser.(*ConceptParser).Parse(0xc8201fdca0, 0xc820166300, 0x7d, 0xc82030d380, 0x3d, 0x0, 0x0, 0x0, 0x0)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/parser/conceptParser.go:42 +0x144
github.com/getgauge/gauge/parser.(*ConceptParser).ParseFile(0xc8201fdca0, 0xc82030d380, 0x3d, 0x0, 0x0, 0x0, 0x0)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/parser/conceptParser.go:51 +0x36b
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).onConceptFileModify(0xc820180050, 0xc82030d380, 0x3d)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:191 +0x1bf
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).onFileModify(0xc820180050, 0xc8201541e0, 0xc82030d380, 0x3d)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:238 +0x9a
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).onFileAdd(0xc820180050, 0xc8201541e0, 0xc82030d380, 0x3d)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:231 +0x83
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).handleEvent(0xc820180050, 0xc82030d380, 0x3d, 0x1, 0xc8201541e0)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:267 +0x28e
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges.func1(0xc8201541e0, 0xc820180050)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:292 +0x123
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:297 +0x1f1

goroutine 1 [select, 3 minutes]:
github.com/getgauge/gauge/api.runAPIServiceIndefinitely(0xdcc1, 0xc82013b940, 0x1, 0x1)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/api.go:92 +0x454
github.com/getgauge/gauge/api.RunInBackground(0x0, 0x0, 0xc82013b940, 0x1, 0x1)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/api.go:129 +0x219
main.main()
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/gauge.go:139 +0xa31

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 22 [IO wait]:
net.runtime_pollWait(0xf40da8, 0x72, 0xc820014150)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201b6300, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201b6300, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201b62a0, 0xc8202f2000, 0x2000, 0x2000, 0x0, 0xf00120, 0xc820014150)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820138180, 0xc8202f2000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/net.go:172 +0xe4
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).handleConnectionMessages(0xc82012cac0, 0xf801e0, 0xc820138180)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/conn/connectionHandler.go:103 +0xac
created by github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/conn/connectionHandler.go:93 +0x1dd

goroutine 8 [chan receive, 3 minutes]:
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges(0xc820180050)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:312 +0x661
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).MakeListOfAvailableSteps
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:48 +0x39

goroutine 18 [syscall]:
syscall.Syscall6(0x16b, 0x4, 0x0, 0x0, 0xc8202f4e60, 0xa, 0xa8fb10, 0x42, 0xc82018f9e0, 0x4f4720)
	/usr/local/Cellar/go/1.5.3/libexec/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.kevent(0x4, 0x0, 0x0, 0xc8202f4e60, 0xa, 0xa8fb10, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/syscall/zsyscall_darwin_amd64.go:202 +0x77
syscall.Kevent(0x4, 0x0, 0x0, 0x0, 0xc8202f4e60, 0xa, 0xa, 0xa8fb10, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/syscall/syscall_bsd.go:447 +0x94
gopkg.in/fsnotify%2ev1.read(0x4, 0xc8202f4e60, 0xa, 0xa, 0xa8fb10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/kashishm/Documents/go/src/gopkg.in/fsnotify.v1/kqueue.go:453 +0x8d
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc8201541e0)
	/Users/kashishm/Documents/go/src/gopkg.in/fsnotify.v1/kqueue.go:262 +0x199
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/Users/kashishm/Documents/go/src/gopkg.in/fsnotify.v1/kqueue.go:61 +0x33f

goroutine 11 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/time.go:59 +0xf9
github.com/getgauge/gauge/api.checkParentIsAlive(0xc8200d3e20)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/api.go:109 +0x18a
created by github.com/getgauge/gauge/api.runAPIServiceIndefinitely
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/api.go:89 +0x1d5

goroutine 20 [select, 3 minutes]:
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout(0xc82012cac0, 0x0, 0x0, 0x0, 0x0)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/conn/connectionHandler.go:88 +0x21f
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).HandleMultipleConnections(0xc82012cac0)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/conn/connectionHandler.go:136 +0x21
created by github.com/getgauge/gauge/api.startAPIService
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/api/api.go:59 +0x55a

goroutine 36 [chan receive, 3 minutes]:
github.com/getgauge/gauge/runner.startRunner.func1(0xc82001ca20, 0xc820296140)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/runner/runner.go:218 +0x44
created by github.com/getgauge/gauge/runner.startRunner
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/runner/runner.go:221 +0x4a6

goroutine 23 [IO wait, 3 minutes]:
net.runtime_pollWait(0xf410a8, 0x72, 0xc820014150)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201b6140, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201b6140, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201b60e0, 0x0, 0xf80000, 0xc82012cda0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820138148, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820138148, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/tcpsock_posix.go:264 +0x3d
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout.func1(0xc82012cac0, 0xc8201543c0, 0xc820154420)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/conn/connectionHandler.go:79 +0x28
created by github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/conn/connectionHandler.go:86 +0xbd
```
* Idea version: 2016.1.3
* API version: IU-145.1617
* Plugin version: 0.2.1.nightly-2016-06-07
* Gauge version: 0.5.1
