### ISSUE TITLE
panic: Accessing an invalid parameter

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#535]
**spec**
```
Specification Heading
=====================

Vowel counts in single word
---------------------------

* concept "dsfsdfds"
```
**concept**
```
# concept <user>
* concept "dsf"
```
**Exception**
```
panic: Accessing an invalid parameter (user)

goroutine 1 [running]:
panic(0x4ec4a0, 0xc420185480)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/getgauge/gauge/gauge.(*ArgLookup).AddArgValue(0xc42001ab88, 0xc420184e88, 0x4, 0xc42020c700)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/gauge/arg.go:55 +0x1b9
github.com/getgauge/gauge/gauge.(*ConceptDictionary).UpdateLookupForNestedConcepts(0xc420184e60)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/gauge/concept.go:83 +0x248
github.com/getgauge/gauge/parser.AddConcepts(0xc4201ce340, 0x38, 0xc420184e60, 0x0, 0xc420195e30, 0xc420184e50)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/parser/conceptParser.go:252 +0x297
github.com/getgauge/gauge/parser.CreateConceptsDictionary(0xc420193af8, 0x13fd38)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/parser/conceptParser.go:222 +0x42f
github.com/getgauge/gauge/parser.ParseConcepts(0xc420195710, 0x0)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/parser/parse.go:59 +0x22
github.com/getgauge/gauge/validation.ValidateSpecs(0xc42000c210, 0x1, 0x1, 0x0, 0xc420011a80)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/validation/validate.go:129 +0x6b
github.com/getgauge/gauge/execution.ExecuteSpecs(0xc42000c210, 0x1, 0x1, 0x0)
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/execution/execute.go:90 +0xa1
main.main()
	/Users/kashishm/Documents/go/src/github.com/getgauge/gauge/gauge.go:151 +0x7e4
```

**Gauge version**: 0.6.3

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-12-15
