### ISSUE TITLE
Getting a panic runtime error when concept heading has a static parameter

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#552]
**Expected behavior**
I should get a parse error.

**Actual behavior**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x24b6e7]

goroutine 1 [running]:
panic(0x512a60, 0x420946070)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/getgauge/gauge/parser.(*ConceptParser).createConcepts(0x420ac5848, 0x420ab4400, 0x14, 0x20, 0x420b1a320, 0x4f, 0x14, 0x20, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:118 +0x15c7
github.com/getgauge/gauge/parser.(*ConceptParser).Parse(0x420ac5848, 0x420ad8900, 0x238, 0x420b1a320, 0x4f, 0x0, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:41 +0x148
github.com/getgauge/gauge/parser.(*ConceptParser).ParseFile(0x420ac5848, 0x420b1a320, 0x4f, 0x58, 0x60, 0x420b539e0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:50 +0x2be
github.com/getgauge/gauge/parser.AddConcepts(0x420b1a320, 0x4f, 0x420a917f0, 0x0, 0x420abdd70, 0x420ab8600)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:239 +0x72
github.com/getgauge/gauge/parser.CreateConceptsDictionary(0x4, 0x5f8fd8)
	/tmp/src/github.com/getgauge/gauge/parser/conceptParser.go:222 +0x42f
github.com/getgauge/gauge/parser.ParseConcepts(0x420abd7a0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:59 +0x22
github.com/getgauge/gauge/validation.ValidateSpecs(0x42093a2c0, 0x1, 0x1, 0x0, 0x420aeefa0)
	/tmp/src/github.com/getgauge/gauge/validation/validate.go:148 +0x6b
github.com/getgauge/gauge/execution.ExecuteSpecs(0x42093a2c0, 0x1, 0x1, 0x0)
	/tmp/src/github.com/getgauge/gauge/execution/execute.go:90 +0xa1
main.main()
	/Users/stechops/Library/Application Support/Go Agent/pipelines/Gauge-Nightly/gauge.go:151 +0x80e
```
**Steps to replicate**
1. Create a spec
```
Specification Heading1
==================
Scenario Heading
---------------
* some "abc"
* Concept with step using tables and use it in some spec "RED"
```
2. Create a concept
```
# Criaçãosdf
* The word "Criação, Você," has "6" vowels.

# Concept with step using tables and use it in "some" spec <param>
* just display <param>




//* Almost all words have vowels
//     |Word  |Vowel Count|
//     |------|-----------|
//     |Gauge |3          |
//     |Mingle|2          |
//     |Snap  |1          |
//     |GoCD  |1          |
//     |Rhythm|0          |

     |Word  |Vowel Count|
     |------|-----------|
     |Gauge |3          |
     |Mingle|2          |
     |Snap  |1          |
     |GoCD  |1          |
     |Rhythm|0          |
```
3. Give the implementation
```
import com.thoughtworks.gauge.*;

import java.util.HashSet;


public class StepImplementation1 {
    @Step("some <param>")
    public void implementation5(Object arg0) {
        System.out.println();

    }

}
```
4. Run the specs and find the above error

**Version**
```
Gauge version: 0.7.1.nightly-2017-01-06

Plugins
-------
html-report (3.0.1.nightly-2017-01-11)
java (0.5.2.nightly-2016-12-20)
ruby (0.3.2.nightly-2016-12-16)
xml-report (0.1.4.nightly-2017-01-13)
```

**Comment by sriv** [comment]
Unable to reproduce on:

```
Gauge version: 0.7.1

Plugins
-------
html-report (3.0.1)
java (0.5.2)
```
Output:

```
[ParseError] /tmp/foo/specs/concept.cpt:4 Concept heading can have only Dynamic Parameters => 'Concept with step using tables and use it in "some" spec <param>'
[ParseError] /tmp/foo/specs/concept.cpt:5 Step is not defined inside a concept heading => 'just display <param>'
[ParseError] /tmp/foo/specs/concept.cpt:19 Table doesn't belong to any step => '     |Word  |Vowel Count|'
[ValidationError] /tmp/foo/specs/example.spec:6 Step implementation not found => 'Concept with step using tables and use it in some spec "RED"'
```
