### ISSUE TITLE
Getting an exception on running specs without reporting plugins

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#560]
```
Test Name:	Vowel counts in multiple word
Test Outcome:	Failed
Result StandardOutput:	
Gauge.CSharp.Runner.SandboxBuilder Creating a Sandbox in: Z:\Documents\Visual Studio 2015\Projects\GaugeProject9\GaugeProject9\bin\Debug\
Unable to start plugin html-report. Plugin html-report is not installed. To install, run `gauge --install html-report`.
# Specification Heading
  ## Vowel counts in multiple word

Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Proxies.RemotingProxy.CallProcessMessage(IMessageSink ms, IMessage reqMsg, ArrayWithSize proxySinks, Thread currentThread, Context currentContext, Boolean bSkippingContextChain)
   at System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke(IMethodCallMessage reqMcmMsg, Boolean useDispatchMessage, Int32 callType)
   at System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(IMessage reqMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Gauge.CSharp.Runner.ISandbox.ExecuteMethod(GaugeMethod gaugeMethod, String[] args)
   at Gauge.CSharp.Runner.MethodExecutor.Execute(GaugeMethod method, String[] args) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\MethodExecutor.cs:line 47
   at Gauge.CSharp.Runner.Processors.ExecuteStepProcessor.Process(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\ExecuteStepProcessor.cs:line 62
   at Gauge.CSharp.Runner.GaugeListener.PollForMessages() in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\GaugeListener.cs:line 49
   at Gauge.CSharp.Runner.StartCommand.Execute() in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\StartCommand.cs:line 53
   at Gauge.CSharp.Runner.Program.Main(String[] args) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Program.cs:line 33
        
        Failed Step: Almost all words have vowels
        Specification: specs\example.spec:30
        Error Message: Connection closed [127.0.0.1:51019] cause: read tcp 127.0.0.1:51017->127.0.0.1:51019: wsarecv: An existing connection was forcibly closed by the remote host.
        Stacktrace: 
        
        Error Message: write tcp 127.0.0.1:51017->127.0.0.1:51019: use of closed network connection
        Stacktrace: 
        
    Error Message: write tcp 127.0.0.1:51017->127.0.0.1:51019: use of closed network connection
    Stacktrace: 
    
  Error Message: write tcp 127.0.0.1:51017->127.0.0.1:51019: use of closed network connection
  Stacktrace: 
  

  Error Message: write tcp 127.0.0.1:51017->127.0.0.1:51019: use of closed network connection
  Stacktrace: 
  
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

Total time taken: 424ms
```
**Version**
```
Gauge version: 0.8.0.nightly-2017-02-06

Plugins
-------
csharp (0.9.3.nightly-2017-01-30)
```

**Comment by shreyapandey** [comment]
getting exactly same exception.Please help.
