### ISSUE TITLE
Screenshot for failed gauge tests are not captured

### ISSUE THREAD

**Issue by jyotisingh** [getgauge/gauge#583]
Capturing screenshots on failure is enabled : `screenshot_on_failure = true`, but it wasn't captured when the test failed. 

### Expected behavior
Expected the screenshot to be available as a part of the html report

### Actual behavior
Capturing screenshot failed with the following error:

```
goroutine 1 [running]:
21:15:13.943 panic(0x556a40, 0xc420014120)
21:15:13.943 	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
21:15:13.943 image.(*RGBA).Opaque(0xc4200ba200, 0x62e340)
21:15:13.944 	/usr/local/Cellar/go/1.7.3/libexec/src/image/image.go:141 +0xc3
21:15:13.944 image/png.opaque(0x62e340, 0xc4200ba200, 0x62c240)
21:15:13.944 	/usr/local/Cellar/go/1.7.3/libexec/src/image/png/writer.go:60 +0x162
21:15:13.944 image/png.(*Encoder).Encode(0xc4205f8000, 0x62c5c0, 0xc4200380a0, 0x62e340, 0xc4200ba200, 0xc42035e000, 0xc4200982c0)
21:15:13.944 	/usr/local/Cellar/go/1.7.3/libexec/src/image/png/writer.go:508 +0x505
21:15:13.945 image/png.Encode(0x62c5c0, 0xc4200380a0, 0x62e340, 0xc4200ba200, 0xc4200ba200, 0x0)
21:15:13.945 	/usr/local/Cellar/go/1.7.3/libexec/src/image/png/writer.go:476 +0x6a
21:15:13.945 github.com/getgauge/screenshot/capture.CaptureScreen(0x7ffe925203cb, 0x13, 0x0, 0x0)
21:15:13.945 	/tmp/src/github.com/getgauge/screenshot/capture/capture_linux.go:60 +0x195
21:15:13.945 main.main()
21:15:13.946 	/tmp/src/github.com/getgauge/gauge_screenshot/main.go:32 +0x101
```

### Gauge version
```
0.7.0
```

If it helps, the build ran on a GoCD docker agent (centos6 box):
Docker image used : gocdcontrib/gocd-dev-build:v1.0.8 (https://hub.docker.com/r/gocdcontrib/gocd-dev-build/)

Let me know if you need more info.

**Comment by jyotisingh** [comment]
Didn't see this after upgrading to 0.9.7, so closing the issue.
