### ISSUE TITLE
Unable to create a ruby project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#590]
**Steps to replicate**
1. Install gauge, with only html-report plugin 
2. gauge --init ruby
is giving an error.

[!] There was an error parsing `Gemfile`: Illformed requirement ["~>"]. Bundler cannot continue.

 #  from /Users/sswaroop/java/Gemfile:4
 #  -------------------------------------------
 #  gem 'test-unit', group: [:development, :test]
 >  gem 'gauge-ruby', '~>', group: [:development, :test]
 #  -------------------------------------------
3. Running the gauge specs gives error too.
```
 (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: Illformed requirement ["~>"]. Bundler cannot continue.

 #  from /Users/sswaroop/java/Gemfile:4
 #  -------------------------------------------
 #  gem 'test-unit', group: [:development, :test]
 >  gem 'gauge-ruby', '~>', group: [:development, :test]
 #  -------------------------------------------
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:131:in `block in initialize'
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:131:in `map!'
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:131:in `initialize'
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:59:in `new'
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:59:in `create'
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:59:in `initialize'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/dependency.rb:75:in `initialize'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/dsl.rb:94:in `new'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/dsl.rb:94:in `gem'
	from /Users/sswaroop/java/Gemfile:4:in `eval_gemfile'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/dsl.rb:41:in `instance_eval'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/dsl.rb:41:in `eval_gemfile'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/dsl.rb:11:in `evaluate'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:33:in `build'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler.rb:127:in `definition'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler.rb:93:in `setup'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/setup.rb:20:in `<top (required)>'
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Ruby runner Failed. Reason: exit status 1
Failed to start gauge API: Runner with pid 4388 quit unexpectedly(exit status 1).
```

**Version**
```
Gauge version: 0.8.2.nightly-2017-03-10

Plugins
-------
html-report (3.1.0)
```

**Comment by sguptatw** [comment]
Try `gauge --init ruby` without gauge-ruby installed. This will give the same error.
