### ISSUE TITLE
Unable to run gauge ruby specs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#591]
**Expected behavior**
should be able to run gauge specs from command line

**Actual behavior**
Getting a protobuff exception

**Steps to replicate**
1. Install Gauge and html-report only
2. Use gauge --init ruby
> This initializes project, downloads and installs gauge-ruby
3. After successful installation, run `bundle exec gauge specs`
4. This gives the following exception
```
bundle exec gauge specs
[ValidationError] /home/sswaroop/rubyTest/specs/example.spec:12 Step implementation not found => 'Vowels in English language are "aeiou".'
[ValidationError] /home/sswaroop/rubyTest/specs/example.spec:19 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /home/sswaroop/rubyTest/specs/example.spec:29 Step implementation not found => 'Almost all words have vowels <table>'

  Error Message: Connection closed [127.0.0.1:45004] cause: EOF
  Stacktrace: 
  

  Error Message: write tcp 127.0.0.1:44273->127.0.0.1:45004: use of closed network connection
  Stacktrace: 
  
/var/lib/gems/2.3.0/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/decoder.rb:86:in `decode': invalid message (ProtocolBuffers::DecodeError)
	from /var/lib/gems/2.3.0/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:290:in `parse'
	from /var/lib/gems/2.3.0/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:296:in `parse'
	from /var/lib/gems/2.3.0/gems/gauge-ruby-0.2.1/lib/gauge_runtime.rb:36:in `dispatch_messages'
	from /var/lib/gems/2.3.0/gems/gauge-ruby-0.2.1/lib/gauge_runtime.rb:76:in `<module:Runtime>'
	from /var/lib/gems/2.3.0/gems/gauge-ruby-0.2.1/lib/gauge_runtime.rb:29:in `<module:Gauge>'
	from /var/lib/gems/2.3.0/gems/gauge-ruby-0.2.1/lib/gauge_runtime.rb:27:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
Ruby runner Failed. Reason: exit status 1
Successfully generated html-report to => /home/sswaroop/rubyTest/reports/html-report
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 82ms
```
**Version**
```
Gauge version: 0.8.2.nightly-2017-03-13

Plugins
-------
csharp (0.10.0)
html-report (3.1.0)
java (0.6.1)
ruby (0.4.0)
```

**Comment by sriv** [comment]
For some reason, your project is using gauge-ruby `0.2.1` (from the stack trace). Can you check what the `Gemfile` looks like?

**Comment by sguptatw** [comment]
```
 source "https://rubygems.org"

    gem 'test-unit', :group => [:development, :test]
    gem 'gauge-ruby' , :group => [:development, :test]
```

**Comment by sguptatw** [comment]
This works after doing `bundle update`
