### ISSUE TITLE
gauge --init java_maven is initializing with an old Gauge-java and giving a Protobuf exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#614]
**Expected behavior**
I should be able to run the tests without an error.

```
mvn clean test

[INFO] Scanning for projects...

[INFO]                                                                         

[INFO] ------------------------------------------------------------------------

[INFO] Building art1 1.0-SNAPSHOT

[INFO] ------------------------------------------------------------------------

[INFO] 

[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ art1 ---

[INFO] 

[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ art1 ---

[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!

[INFO] skip non existing resourceDirectory /Users/<username>/work/test/art1/src/main/resources

[INFO] 

[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ art1 ---

[INFO] No sources to compile

[INFO] 

[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ art1 ---

[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!

[INFO] skip non existing resourceDirectory /Users/<username>/work/test/art1/src/test/resources

[INFO] 

[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ art1 ---

[INFO] Changes detected - recompiling the module!

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!

[INFO] Compiling 1 source file to /Users/<username>/work/test/art1/target/test-classes

[INFO] 

[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ art1 ---

[INFO] 

[INFO] --- gauge-maven-plugin:1.1.0:execute (default) @ art1 ---

[ValidationError] /Users/<username>/work/test/art1/specs/example.spec:11 Step implementation not found => 'Vowels in English language are "aeiou".'

[ValidationError] /Users/<username>/work/test/art1/specs/example.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'

[ValidationError] /Users/<username>/work/test/art1/specs/example.spec:28 Step implementation not found => 'Almost all words have vowels <table>'

com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: messageType

at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)

at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71)

at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)

at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)

at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)

at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)

at gauge.messages.Messages$Message.parseFrom(Messages.java:21442)

at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:67)

at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)

com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: messageType



  Error Message: Connection closed [127.0.0.1:50336] cause: EOF

  Stacktrace: 

  



  Error Message: write tcp 127.0.0.1:50332->127.0.0.1:50336: use of closed network connection

  Stacktrace: 

  

Successfully generated html-report to => /Users/<username>/work/test/art1/reports/html-report

Specifications:	0 executed	0 passed	0 failed	0 skipped

Scenarios:	0 executed	0 passed	0 failed	0 skipped



Total time taken: 144ms

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 4.584 s

[INFO] Finished at: 2017-03-27T08:39:06+05:30

[INFO] Final Memory: 16M/213M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.1.0:execute (default) on project art1: Gauge Specs execution failed -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR] 

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
**Observation**
The template generates pom file dependency with old gauge-java
```
        <dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>0.3.4</version>
            <scope>test</scope>
        </dependency>
```

**Comment by haroon-sheikh** [comment]
@sguptatw can we retest this please? I've just created a new template and its point to 0.6.0 which should work with 0.8+.
