### ISSUE TITLE
Getting a panic runtime error while capturing screenshot

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#723]
**Expected behavior**
We should be able to capture the screenshot on failure

**Actual behavior**
Getting a panic runtime error

**Steps to replicate**
https://travis-ci.org/getgauge-examples/gauge-active-admin-example-ruby/builds/254357113
```
bundle exec gauge specs
panic: empty display string
goroutine 1 [running]:
main.main()
	/tmp/src/github.com/getgauge/gauge_screenshot/main.go:34 +0x11d
panic: empty display string
goroutine 1 [running]:
main.main()
	/tmp/src/github.com/getgauge/gauge_screenshot/main.go:34 +0x11d
  Error Message: unknown error: Chrome failed to start: exited abnormally
    (Driver info: chromedriver=2.9.248304,platform=Linux 3.13.0-115-generic x86_64)
  Stacktrace: 
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:85:in `new'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/http/common.rb:63:in `call'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/bridge.rb:669:in `raw_execute'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/bridge.rb:108:in `create_session'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/remote/bridge.rb:69:in `initialize'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/chrome/bridge.rb:42:in `initialize'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/common/driver.rb:61:in `new'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver/common/driver.rb:61:in `for'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/selenium-webdriver-3.1.0/lib/selenium/webdriver.rb:82:in `for'
  /home/travis/build/getgauge-examples/gauge-active-admin-example-ruby/step_implementations/utils/driver.rb:13:in `block in <module:Driver>'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/executor.rb:46:in `call'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/executor.rb:46:in `block in execute_hooks'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/executor.rb:44:in `each'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/executor.rb:44:in `execute_hooks'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/processors/execution_handler.rb:26:in `handle_hooks_execution'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/processors/execution_hook_processors.rb:26:in `process_execution_start_request'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/message_processor.rb:52:in `call'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/message_processor.rb:52:in `process_message'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:53:in `handle_message'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:37:in `dispatch_messages'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:76:in `<module:Runtime>'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:29:in `<module:Gauge>'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:27:in `<top (required)>'
  -e:1:in `require'
  -e:1:in `<main>'
  
  Error Message: uninitialized class variable @@driver in Driver
  Stacktrace: 
  /home/travis/build/getgauge-examples/gauge-active-admin-example-ruby/step_implementations/utils/driver.rb:6:in `driver'
  /home/travis/build/getgauge-examples/gauge-active-admin-example-ruby/step_implementations/utils/driver.rb:18:in `block in <module:Driver>'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/executor.rb:46:in `call'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/executor.rb:46:in `block in execute_hooks'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/executor.rb:44:in `each'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/executor.rb:44:in `execute_hooks'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/processors/execution_handler.rb:26:in `handle_hooks_execution'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/processors/execution_hook_processors.rb:30:in `process_execution_end_request'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/message_processor.rb:52:in `call'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/message_processor.rb:52:in `process_message'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:53:in `handle_message'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:37:in `dispatch_messages'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:76:in `<module:Runtime>'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:29:in `<module:Gauge>'
  /home/travis/.rvm/gems/ruby-2.2.6/gems/gauge-ruby-0.4.0/lib/gauge_runtime.rb:27:in `<top (required)>'
  -e:1:in `require'
  -e:1:in `<main>'
```

**Comment by yolinas** [comment]
Having the same issue with CircleCI. Currently failing our end to end test, any ideas for a workaround?

Tried disabling screenshots but does not seem to work. Our default.properties file:

```
gauge_reports_dir=../../build/end-to-end
overwrite_reports=true
screenshot_enabled=false
```

Please advice?

**Comment by sriv** [comment]
@yolinas - is there a stacktrace that you can share please?

**Comment by sriv** [comment]
@sguptatw - considering that [this build](https://travis-ci.org/getgauge-examples/ruby-selenium) is passing, I can not replicate this issue.

**Comment by sguptatw** [comment]
Please feel free to re-open this issue if you face the issue again.
