### ISSUE TITLE
Remove duplicate checks for `no scenarios/steps found`

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#789]
Duplicate checks are present for `No scenarios found in spec` and `No steps found in scenario` in `parser` and `execution` packages. We can remove the above checks from the `execution`.

* **No scenarios found in spec**
https://github.com/getgauge/gauge/blob/7321d9552894c5acb5a0ffcc24b65d06617d56d7/execution/specExecutor.go#L93
https://github.com/getgauge/gauge/blob/7321d9552894c5acb5a0ffcc24b65d06617d56d7/parser/specparser.go#L550

* **No steps found in scenario**
https://github.com/getgauge/gauge/blob/7321d9552894c5acb5a0ffcc24b65d06617d56d7/execution/scenarioExecutor.go#L63
https://github.com/getgauge/gauge/blob/7321d9552894c5acb5a0ffcc24b65d06617d56d7/parser/specparser.go#L554

**Comment by kashishm** [comment]
Duplicate checks have been removed via e573988a8fd8ed193af7b9c5557e87eda1f3e37a. Functional tests are passing.

@sguptatw Can you verify if `No scenarios found in spec` and `No steps found in scenario` parse errors are working as expected?

**Comment by sguptatw** [comment]
Getting an exception Running from an IDE with no scenario heading
```
[ParseError] /Users/sswaroop/work/gauge/getgauge-examples/java-maven-selenium/specs/one.spec:1 Spec heading not found => ''
[ParseError] /Users/sswaroop/work/gauge/getgauge-examples/java-maven-selenium/specs/one.spec:7 Scenario should be defined after the spec heading => 'Scenario Heading'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061) on port 28846
Only local connections are allowed.
Aug 31, 2017 8:58:55 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Aug 31, 2017 8:58:56 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x421d695b0, 0x15ec8a0, 0x199ecf0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:24 +0x79
github.com/getgauge/gauge/execution.recoverPanic()
	src/github.com/getgauge/gauge/execution/execute.go:128 +0x57
panic(0x15ec8a0, 0x199ecf0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/getgauge/gauge/execution.newSpecExecutor(0x421be0900, 0x1979ae0, 0x421acfbc0, 0x19718c0, 0x421bc81b0, 0x421e31aa0, 0x0, 0x0)
	src/github.com/getgauge/gauge/execution/specExecutor.go:51 +0x9d
github.com/getgauge/gauge/execution.(*simpleExecution).executeSpecs(0x421d1e070, 0x421bfc4e0, 0xed1397970, 0x1b111191, 0x19b10a0)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:129 +0x160
github.com/getgauge/gauge/execution.(*simpleExecution).execute(0x421d1e070)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:91 +0x125
github.com/getgauge/gauge/execution.(*simpleExecution).run(0x421d1e070, 0x196d340)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:70 +0x39
github.com/getgauge/gauge/execution.ExecuteSpecs(0x421c76db0, 0x1, 0x3, 0x0)
	src/github.com/getgauge/gauge/execution/execute.go:123 +0x9b0
github.com/getgauge/gauge/cmd.execute(0x421c76db0, 0x1, 0x3)
	src/github.com/getgauge/gauge/cmd/run.go:113 +0x15a
github.com/getgauge/gauge/cmd.glob..func11(0x19a8ca0, 0x421c76db0, 0x1, 0x3)
	src/github.com/getgauge/gauge/cmd/run.go:54 +0x9c
github.com/spf13/cobra.(*Command).execute(0x19a8ca0, 0x421c76d20, 0x3, 0x3, 0x19a8ca0, 0x421c76d20)
	src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0x19a7760, 0x421c2d580, 0x169ec01, 0x421c05dc0)
	src/github.com/spf13/cobra/command.go:726 +0x339
github.com/getgauge/gauge/cmd.Parse(0x16a446f, 0xa, 0x0)
	src/github.com/getgauge/gauge/cmd/cmd.go:95 +0xa3
main.main()
	src/github.com/getgauge/gauge/gauge.go:88 +0x68


Process finished with exit code 1

```

**Comment by kashishm** [comment]
should be available in nightly >= 31-08-2017

**Comment by sguptatw** [comment]
The following are the various types of parse errors
- [x] Step is not defined inside a concept heading
- [x] Table doesn’t belong to any step
- [ ] Scenario heading is not allowed in concept file
- [ ] Concept should have at least one step
     - [ ] Does not show this parse error even with no step in the concept
```
This is a concept file with following syntax for each concept.
# Concept <Heading>

# Concept1 <Heading>
* step1 <Heading>
* step2
```
- [x] Concept heading can only have dynamic parameters
- [ ] Duplicate concept definition found
Not getting the implementation suggestion for one of the concept steps. What should be the expected behavior?
```
This is a concept file with following syntax for each concept.
# Concept1 <Heading>
* unimplemented1

# Concept1 <Heading>
* unimplemented2
```
- [x] Teardown should have at least three underscore characters
- [x] Table location not specified
- [x] Scenario heading should have at least one character
- [x] Table header should be not blank
- [x] Table header cannot have repeated column values
- [x] Multiple spec headings found in the same file
- [x] Scenario should be defined after the spec heading
- [x] Could not resolve table from file
- [ ] Spec does not have any element
   - [ ] This is throwing null pointer exception while execution
- [ ] Spec heading not found
- [x] Spec heading should have at least one character
- [x] Data table should at least have 1 data row
- [x] Dynamic param could not be resolved
- [ ] Step should not be blank
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1963)
	at com.thoughtworks.gauge.processor.ValidateStepProcessor.getMethodName(ValidateStepProcessor.java:72)
	at com.thoughtworks.gauge.processor.ValidateStepProcessor.validateStep(ValidateStepProcessor.java:53)
	at com.thoughtworks.gauge.processor.ValidateStepProcessor.process(ValidateStepProcessor.java:38)
	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:91)
	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:105)
	at com.thoughtworks.gauge.GaugeRuntime.access$100(GaugeRuntime.java:37)
	at com.thoughtworks.gauge.GaugeRuntime$2.run(GaugeRuntime.java:86)
	at java.lang.Thread.run(Thread.java:745)
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
[ValidationError] /Users/sswaroop/Downloads/untitled 2/specs/example.spec:20 Connection closed [127.0.0.1:50872] cause: EOF => ''
[ValidationError] /Users/sswaroop/Downloads/untitled 2/specs/example.spec:30 write tcp 127.0.0.1:50868->127.0.0.1:50872: use of closed network connection => 'Almost all words have vowels <table>'
[ValidationError] /Users/sswaroop/Downloads/untitled 2/specs/example1.spec:3 write tcp 127.0.0.1:50868->127.0.0.1:50872: use of closed network connection => 'unimplemented1'
[ValidationError] /Users/sswaroop/Downloads/untitled 2/specs/example1.spec:21 write tcp 127.0.0.1:50868->127.0.0.1:50872: use of closed network connection => 'sdf "def"'
[ValidationError] /Users/sswaroop/Downloads/untitled 2/specs/example1.spec:23 write tcp 127.0.0.1:50868->127.0.0.1:50872: use of closed network connection => 'sdfsdf'
[ValidationError] /Users/sswaroop/Downloads/untitled 2/specs/example1.spec:31 write tcp 127.0.0.1:50868->127.0.0.1:50872: use of closed network connection => 'Almost all words have vowels <table>'
  Failed to initialize suite datastore. Error: write tcp 127.0.0.1:50868->127.0.0.1:50872: use of closed network connection
```
- [x] Circular reference found in concept
- [x] Duplicate scenario definition found in the same specification

**Comment by sguptatw** [comment]
For spec should have at least one element try with an empty spec.
Is this parse error expected in any other scenario as well?

**Comment by kashishm** [comment]
Fix will be available in Gauge nightly >= 01-09-2017 and Gauge Java nightly >= 01-09-2017

**Comment by Apoorva-GA** [comment]
Except the case when there are duplicate concept definitions - Validation error and implementation suggestion are not shown for one of the concept steps, which is being tracked [here](https://github.com/getgauge/gauge/issues/797). 

All the other cases works fine.
