### ISSUE TITLE
Print execution result in machine readable format

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#799]
**Command**

```
gauge run -m specs
gauge run --machine-readable specs/
```

**Output Format**

```
executionEvent: {
	type # SuiteStart | SpecStart | ScenarioStart | ScenarioEnd | SpecEnd | SuiteEnd
        id
	parentId
	name
	filename
	line
	stream
	result: {
                status
                time
                out
                errors []<executionError>
                beforeHookFailure <executionError>
                afterHookFailure <executionError>
                table: {
                	text
	                rowIndex
                }
	}
}

executionError {
	text
	filename
	message
	lineNo
	stackTrace
}
```
**Sample Output**
```
{"type":"suiteStart"}
{"type":"specStart","id":"<path>/specs/example.spec","name":"Specification Heading","filename":"<path>/specs/example.spec","line":1}
{"type":"scenarioStart","id":"<path>/specs/example.spec:13","parentId":"<path>/specs/example.spec","name":"Vowel counts in single word","filename":"<path>/specs/example.spec","line":13,"result":{"time":0}}
{"type":"scenarioEnd","id":"<path>/specs/example.spec:13","parentId":"<path>/specs/example.spec","name":"Vowel counts in single word","filename":"<path>/specs/example.spec","line":13,"result":{"status":"pass","time":1}}
{"type":"specEnd","id":"<path>/specs/example.spec","name":"Specification Heading","filename":"<path>/specs/example.spec","line":1,"result":{"status":"pass","time":0}}
{"type":"suiteEnd","result":{"status":"pass","time":0}}
Successfully generated html-report to => <path>/reports/html-report
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	0 skipped

Total time taken: 37ms
```
The parse/validation errors and summary will be shown as it is.

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 05-09-2017

**Comment by kashishm** [comment]
**Command**
```
gauge run specs/example.spec:1
```
Getting exception when giving a wrong line number for scenario execution.
```
{"type":"suiteStart"}
panic: runtime error: index out of range

goroutine 12 [running]:
github.com/getgauge/gauge/reporter.(*jsonConsole).SpecStart(0xc4202d8180, 0xc42011ab00, 0x19c1ce0, 0xc4204baa80)
	src/github.com/getgauge/gauge/reporter/jsonConsole.go:127 +0x27b
github.com/getgauge/gauge/reporter.ListenExecutionEvents.func1(0xc4202de480, 0xc4202e1b00, 0xc4201666e0)
	src/github.com/getgauge/gauge/reporter/reporter.go:143 +0x184
created by github.com/getgauge/gauge/reporter.ListenExecutionEvents
	src/github.com/getgauge/gauge/reporter/reporter.go:135 +0x113
```

**Comment by BugDiver** [comment]
Fix should be available in nightly >=  06-09-2017
