### ISSUE TITLE
Getting a panic runtime exception while executing specs

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#808]
_From @sguptatw on September 14, 2017 6:47_

Getting a runtime exception while executing
gauge run --machine-readable --hide-suggestion --simple-console --tags sdfsdf "specs/example.spec:3"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/getgauge/gauge/parser.getAllSpecFiles(0x421b99080, 0x1, 0x6, 0x0, 0x421cd1778, 0x1010497, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/parser/parse.go:121 +0x540
github.com/getgauge/gauge/parser.parseSpecsInDirs(0x421b8bf40, 0x421b99080, 0x1, 0x6, 0x421cf96c0, 0x1010bf8, 0x20, 0x1621ea0, 0x1)
	src/github.com/getgauge/gauge/parser/parse.go:98 +0x5a
github.com/getgauge/gauge/parser.ParseSpecs(0x421b99080, 0x1, 0x6, 0x421b8bf40, 0x421cf96c0, 0x0, 0x421cd1870, 0x15d34c0, 0x1051d70)
	src/github.com/getgauge/gauge/parser/parse.go:66 +0x5a
github.com/getgauge/gauge/validation.ValidateSpecs(0x421b99080, 0x1, 0x6, 0x8010100, 0x1)
	src/github.com/getgauge/gauge/validation/validate.go:152 +0x430
github.com/getgauge/gauge/execution.ExecuteSpecs(0x421b99080, 0x1, 0x6, 0x0)
	src/github.com/getgauge/gauge/execution/execute.go:100 +0x9e
github.com/getgauge/gauge/cmd.execute(0x421b99080, 0x1, 0x6)
	src/github.com/getgauge/gauge/cmd/run.go:108 +0x152
github.com/getgauge/gauge/cmd.glob..func12(0x1a05ce0, 0x421b99080, 0x1, 0x6)
	src/github.com/getgauge/gauge/cmd/run.go:50 +0x97
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0x1a05ce0, 0x421b98fc0, 0x6, 0x6, 0x1a05ce0, 0x421b98fc0)
	src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x23d
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a047a0, 0x421cf90a0, 0x0, 0x421cd1de8)
	src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x2fe
github.com/getgauge/gauge/cmd.Parse(0x169d9a2, 0xa, 0x0)
	src/github.com/getgauge/gauge/cmd/cmd.go:107 +0x8c
main.main()
	src/github.com/getgauge/gauge/gauge.go:87 +0x63

Process finished with exit code 2

[test 2.zip](https://github.com/getgauge/Intellij-Plugin/files/1301961/test.2.zip)

**Version**
```
Gauge version: 0.9.3.nightly-2017-09-13
Commit Hash: c3160bc

Plugins
-------
csharp (0.10.2.nightly-2017-07-25)
html-report (4.0.2.nightly-2017-08-07)
java (0.6.6.nightly-2017-09-13)
```
Gauge IntelliJ 0.3.7.nightly-2017-09-14

_Copied from original issue: getgauge/Intellij-Plugin#295_

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2017-09-14
