### ISSUE TITLE
[Error] The langserver server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge#858]
_From @sguptatw on October 9, 2017 15:54_

**Expected behavior**
I should be able to work with VSCode seamlessly

**Actual behavior**
Getting the error `The langserver server crashed 5 times in the last 3 minutes. The server will not be restarted.`

**Steps to replicate**
* Open this project in VSCode
* Open a couple of specs
[parse-errors.zip](https://github.com/getgauge/gauge-vscode/files/1369101/parse-errors.zip)
* We get this error

**Version**
```
Gauge version: 0.9.4

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.1)
ruby (0.4.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

_Copied from original issue: getgauge/gauge-vscode#11_

**Comment by Apoorva-GA** [comment]
_From @BugDiver on October 10, 2017 6:56_

Should be fixed through this [PR](https://github.com/getgauge/gauge/pull/835) in gauge core.

**Comment by Apoorva-GA** [comment]
_From @sguptatw on November 7, 2017 10:44_

This error still occurs for duplicate concept definitions
```
# Concept1
* Concept2

# Concept1
* Concept2
```

**Comment by Apoorva-GA** [comment]
_From @sguptatw on November 7, 2017 11:21_

This also occurs for circular reference of concepts
```
# Concept1
* Concept2

# Concept2
* Concept1
```

```
panic: runtime error: index out of range

goroutine 44 [running]:
github.com/getgauge/gauge/api/lang.(*files).line(0xc876d0, 0xc0421060e0, 0x64, 0xffffffffffffffff, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/file.go:51 +0xfc
github.com/getgauge/gauge/api/lang.getLine(0xc0421060e0, 0x64, 0xffffffffffffffff, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/file.go:88 +0x52
github.com/getgauge/gauge/api/lang.createDiagnostic(0xc0421ae1e0, 0xe5, 0xffffffffffffffff, 0x1, 0xc0421060e0, 0x64, 0x0, 0x0, 0x0, 0x0, ...)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/diagnostic.go:43 +0x8f
github.com/getgauge/gauge/api/lang.createDiagnosticsFrom(0xc04208f770, 0xc0421060e0, 0x64, 0x5a, 0xc04208f770, 0x518e8f)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/diagnostic.go:31 +0x196
github.com/getgauge/gauge/api/lang.createDiagnostics(0xc0421060e0, 0x64, 0xf0, 0x8d4700, 0xc0420433c0)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/diagnostic.go:17 +0xc6
github.com/getgauge/gauge/api/lang.publishDiagnostics(0xc4d520, 0xc04204e0b8, 0xc4b720, 0xc0423dcc00, 0xc042162a50)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:144 +0xba
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0xca6428, 0xc4d520, 0xc04204e0b8, 0xc4b720, 0xc0423dcc00, 0xc042162a50, 0xc04240a000, 0x35, 0x40, 0xc0420341d0)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:112 +0xc74
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0xca6428, 0xc4d520, 0xc04204e0b8, 0xc0423dcc00, 0xc042162a50, 0x0, 0xc04214a0d0, 0x0, 0xc04213bef8)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:74 +0x6d
github.com/getgauge/gauge/api/lang.(*LangHandler).(github.com/getgauge/gauge/api/lang.handle)-fm(0xc4d520, 0xc04204e0b8, 0xc0423dcc00, 0xc042162a50, 0x79a453, 0xc042037380, 0xc042398000, 0x98e)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:66 +0x59
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc0423fcff0, 0xc4d520, 0xc04204e0b8, 0xc0423dcc00, 0xc042162a50)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x76
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:70 +0x72
[Error - 4:49:27 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by Apoorva-GA** [comment]
_From @sguptatw on November 8, 2017 6:53_

Another scenario is when I move a concept from specs\con.cpt to specs\concepts\con.cpt
I get the following error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x71ac3d]

goroutine 1 [running]:
github.com/getgauge/gauge/util.FindConceptFilesIn.func1(0xc042008630, 0x22, 0x0, 0x0, 0x7)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:103 +0x2d
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir.func1(0xc042008630, 0x22, 0x0, 0x0, 0xc4e220, 0xc042144420, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:170 +0x74
path/filepath.walk(0xc04200c680, 0x1a, 0xc57560, 0xc04203ac60, 0xc042002280, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:377 +0x2f2
path/filepath.walk(0xc04200c640, 0x11, 0xc57560, 0xc04203ab40, 0xc042002280, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:381 +0x3a1
path/filepath.walk(0xc04200e1e0, 0xb, 0xc57560, 0xc04203a660, 0xc042002280, 0x0, 0x20)
	C:/Program Files/Go/src/path/filepath/path.go:381 +0x3a1
path/filepath.Walk(0xc04200e1e0, 0xb, 0xc042002280, 0xc04200e190, 0xb)
	C:/Program Files/Go/src/path/filepath/path.go:403 +0x124
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir(0xc04200e1e0, 0xb, 0x9d2c78, 0x9d2c68, 0x0, 0x0, 0x9)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:169 +0xb1
github.com/getgauge/gauge/util.findFilesIn(0xc04200e190, 0xb, 0x9d2c78, 0x9d2c68, 0xb, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:83 +0x68
github.com/getgauge/gauge/util.FindConceptFilesIn(0xc04200e190, 0xb, 0xc04200e190, 0xb, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:102 +0x59
github.com/getgauge/gauge/util.GetConceptFiles(0x913640, 0x0, 0xc04206b940)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:175 +0x102
github.com/getgauge/gauge/parser.CreateConceptsDictionary(0x43dc50, 0x7dd66d)
	C:/work/gopath/src/github.com/getgauge/gauge/parser/conceptParser.go:222 +0xcb
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).getParsedConcepts(0xc0421b8000, 0x9d3a08)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:299 +0x2d
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).initConceptsCache(0xc0421b8000)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:153 +0x96
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).Init(0xc0421b8000)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:92 +0x68
github.com/getgauge/gauge/api/lang.Server(0xc58100, 0xc0421b8000, 0x2)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:57 +0x5b
github.com/getgauge/gauge/cmd.glob..func4(0xc8a5e0, 0xc0420d6be0, 0x0, 0x2)
	C:/work/gopath/src/github.com/getgauge/gauge/cmd/daemon.go:43 +0x109
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0xc8a5e0, 0xc0420d6b80, 0x2, 0x2, 0xc8a5e0, 0xc0420d6b80)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x244
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8a1a0, 0xd, 0xc04211a0e0, 0xc0420f64b0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x305
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8a1a0, 0x9b76d2, 0x17)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:685 +0x32
github.com/getgauge/gauge/cmd.Parse(0xc04206bf70, 0x88c6b0)
	C:/work/gopath/src/github.com/getgauge/gauge/cmd/cmd.go:97 +0x44
main.main()
	C:/work/gopath/src/github.com/getgauge/gauge/gauge.go:27 +0x29
[Info  - 12:21:23 PM] Connection to server got closed. Server will restart.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x71ac3d]

goroutine 1 [running]:
github.com/getgauge/gauge/util.FindConceptFilesIn.func1(0xc04206d0e0, 0x22, 0x0, 0x0, 0x7)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:103 +0x2d
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir.func1(0xc04206d0e0, 0x22, 0x0, 0x0, 0xc4e220, 0xc04220a000, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:170 +0x74
path/filepath.walk(0xc04204f160, 0x1a, 0xc57560, 0xc0420eba40, 0xc0420d6e80, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:377 +0x2f2
path/filepath.walk(0xc04204f120, 0x11, 0xc57560, 0xc0420eb920, 0xc0420d6e80, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:381 +0x3a1
path/filepath.walk(0xc042050db0, 0xb, 0xc57560, 0xc0420eb440, 0xc0420d6e80, 0x0, 0x20)
	C:/Program Files/Go/src/path/filepath/path.go:381 +0x3a1
path/filepath.Walk(0xc042050db0, 0xb, 0xc0420d6e80, 0xc042050d70, 0xb)
	C:/Program Files/Go/src/path/filepath/path.go:403 +0x124
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir(0xc042050db0, 0xb, 0x9d2c78, 0x9d2c68, 0x0, 0x0, 0x9)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:169 +0xb1
github.com/getgauge/gauge/util.findFilesIn(0xc042050d70, 0xb, 0x9d2c78, 0x9d2c68, 0xb, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:83 +0x68
github.com/getgauge/gauge/util.FindConceptFilesIn(0xc042050d70, 0xb, 0xc042050d70, 0xb, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:102 +0x59
github.com/getgauge/gauge/util.GetConceptFiles(0x913640, 0x0, 0xc04206b940)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:175 +0x102
github.com/getgauge/gauge/parser.CreateConceptsDictionary(0x43dc50, 0x7dd66d)
	C:/work/gopath/src/github.com/getgauge/gauge/parser/conceptParser.go:222 +0xcb
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).getParsedConcepts(0xc0421ea000, 0x9d3a08)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:299 +0x2d
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).initConceptsCache(0xc0421ea000)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:153 +0x96
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).Init(0xc0421ea000)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:92 +0x68
github.com/getgauge/gauge/api/lang.Server(0xc58100, 0xc0421ea000, 0x2)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:57 +0x5b
github.com/getgauge/gauge/cmd.glob..func4(0xc8a5e0, 0xc0420d6c20, 0x0, 0x2)
	C:/work/gopath/src/github.com/getgauge/gauge/cmd/daemon.go:43 +0x109
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0xc8a5e0, 0xc0420d6bc0, 0x2, 0x2, 0xc8a5e0, 0xc0420d6bc0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x244
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8a1a0, 0xd, 0xc04211a0e0, 0xc0420f64b0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x305
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8a1a0, 0x9b76d2, 0x17)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:685 +0x32
github.com/getgauge/gauge/cmd.Parse(0xc04206bf70, 0x88c6b0)
	C:/work/gopath/src/github.com/getgauge/gauge/cmd/cmd.go:97 +0x44
main.main()
	C:/work/gopath/src/github.com/getgauge/gauge/gauge.go:27 +0x29
[Info  - 12:21:23 PM] Connection to server got closed. Server will restart.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x71ac3d]

goroutine 1 [running]:
github.com/getgauge/gauge/util.FindConceptFilesIn.func1(0xc042008690, 0x22, 0x0, 0x0, 0x7)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:103 +0x2d
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir.func1(0xc042008690, 0x22, 0x0, 0x0, 0xc4e220, 0xc042142510, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:170 +0x74
path/filepath.walk(0xc04200c700, 0x1a, 0xc57560, 0xc04203ac00, 0xc0420021c0, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:377 +0x2f2
path/filepath.walk(0xc04200c6c0, 0x11, 0xc57560, 0xc04203aae0, 0xc0420021c0, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:381 +0x3a1
path/filepath.walk(0xc04200e1e0, 0xb, 0xc57560, 0xc04203a600, 0xc0420021c0, 0x0, 0x20)
	C:/Program Files/Go/src/path/filepath/path.go:381 +0x3a1
path/filepath.Walk(0xc04200e1e0, 0xb, 0xc0420021c0, 0xc04200e190, 0xb)
	C:/Program Files/Go/src/path/filepath/path.go:403 +0x124
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir(0xc04200e1e0, 0xb, 0x9d2c78, 0x9d2c68, 0x0, 0x0, 0x9)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:169 +0xb1
github.com/getgauge/gauge/util.findFilesIn(0xc04200e190, 0xb, 0x9d2c78, 0x9d2c68, 0xb, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:83 +0x68
github.com/getgauge/gauge/util.FindConceptFilesIn(0xc04200e190, 0xb, 0xc04200e190, 0xb, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:102 +0x59
github.com/getgauge/gauge/util.GetConceptFiles(0x913640, 0x0, 0xc04206b940)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:175 +0x102
github.com/getgauge/gauge/parser.CreateConceptsDictionary(0x43dc50, 0x7dd66d)
	C:/work/gopath/src/github.com/getgauge/gauge/parser/conceptParser.go:222 +0xcb
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).getParsedConcepts(0xc0421ec000, 0x9d3a08)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:299 +0x2d
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).initConceptsCache(0xc0421ec000)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:153 +0x96
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).Init(0xc0421ec000)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:92 +0x68
github.com/getgauge/gauge/api/lang.Server(0xc58100, 0xc0421ec000, 0x2)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:57 +0x5b
github.com/getgauge/gauge/cmd.glob..func4(0xc8a5e0, 0xc0420d6c20, 0x0, 0x2)
	C:/work/gopath/src/github.com/getgauge/gauge/cmd/daemon.go:43 +0x109
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0xc8a5e0, 0xc0420d6bc0, 0x2, 0x2, 0xc8a5e0, 0xc0420d6bc0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x244
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8a1a0, 0xd, 0xc04211a0e0, 0xc0420f64b0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x305
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8a1a0, 0x9b76d2, 0x17)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:685 +0x32
github.com/getgauge/gauge/cmd.Parse(0xc04206bf70, 0x88c6b0)
	C:/work/gopath/src/github.com/getgauge/gauge/cmd/cmd.go:97 +0x44
main.main()
	C:/work/gopath/src/github.com/getgauge/gauge/gauge.go:27 +0x29
[Info  - 12:21:24 PM] Connection to server got closed. Server will restart.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x71ac3d]

goroutine 1 [running]:
github.com/getgauge/gauge/util.FindConceptFilesIn.func1(0xc042008630, 0x22, 0x0, 0x0, 0x7)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:103 +0x2d
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir.func1(0xc042008630, 0x22, 0x0, 0x0, 0xc4e220, 0xc0421443f0, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:170 +0x74
path/filepath.walk(0xc04200c640, 0x1a, 0xc57560, 0xc04203ac00, 0xc0420021c0, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:377 +0x2f2
path/filepath.walk(0xc04200c600, 0x11, 0xc57560, 0xc04203aae0, 0xc0420021c0, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:381 +0x3a1
path/filepath.walk(0xc04200e190, 0xb, 0xc57560, 0xc04203a600, 0xc0420021c0, 0x0, 0x20)
	C:/Program Files/Go/src/path/filepath/path.go:381 +0x3a1
path/filepath.Walk(0xc04200e190, 0xb, 0xc0420021c0, 0xc04200e150, 0xb)
	C:/Program Files/Go/src/path/filepath/path.go:403 +0x124
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir(0xc04200e190, 0xb, 0x9d2c78, 0x9d2c68, 0x0, 0x0, 0x9)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:169 +0xb1
github.com/getgauge/gauge/util.findFilesIn(0xc04200e150, 0xb, 0x9d2c78, 0x9d2c68, 0xb, 0x0, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:83 +0x68
github.com/getgauge/gauge/util.FindConceptFilesIn(0xc04200e150, 0xb, 0xc04200e150, 0xb, 0x0)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:102 +0x59
github.com/getgauge/gauge/util.GetConceptFiles(0x913640, 0x0, 0xc04206b940)
	C:/work/gopath/src/github.com/getgauge/gauge/util/fileUtils.go:175 +0x102
github.com/getgauge/gauge/parser.CreateConceptsDictionary(0x43dc50, 0x7dd66d)
	C:/work/gopath/src/github.com/getgauge/gauge/parser/conceptParser.go:222 +0xcb
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).getParsedConcepts(0xc0421a6000, 0x9d3a08)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:299 +0x2d
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).initConceptsCache(0xc0421a6000)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:153 +0x96
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).Init(0xc0421a6000)
	C:/work/gopath/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:92 +0x68
github.com/getgauge/gauge/api/lang.Server(0xc58100, 0xc0421a6000, 0x2)
	C:/work/gopath/src/github.com/getgauge/gauge/api/lang/server.go:57 +0x5b
github.com/getgauge/gauge/cmd.glob..func4(0xc8a5e0, 0xc0420d6c20, 0x0, 0x2)
	C:/work/gopath/src/github.com/getgauge/gauge/cmd/daemon.go:43 +0x109
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0xc8a5e0, 0xc0420d6bc0, 0x2, 0x2, 0xc8a5e0, 0xc0420d6bc0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x244
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8a1a0, 0xd, 0xc04211a0e0, 0xc0420f64b0)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x305
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8a1a0, 0x9b76d2, 0x17)
	C:/work/gopath/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:685 +0x32
github.com/getgauge/gauge/cmd.Parse(0xc04206bf70, 0x88c6b0)
	C:/work/gopath/src/github.com/getgauge/gauge/cmd/cmd.go:97 +0x44
main.main()
	C:/work/gopath/src/github.com/getgauge/gauge/gauge.go:27 +0x29
[Error - 12:21:24 PM] Connection to server got closed. Server will not be restarted.

```

**Comment by Apoorva-GA** [comment]
_From @sguptatw on November 8, 2017 10:48_

When I re-open the project with the concept moved to a different location, Gauge crashes

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 14-11-17

**Comment by sguptatw** [comment]
This issue is occuring again.
Open project https://github.com/getgauge/gauge-lsp-tests.git

**Comment by sguptatw** [comment]
Can't create files named con in windows - https://stackoverflow.com/questions/448438/windows-and-renaming-folders-the-con-issue. 

Closing the issue

**Comment by sguptatw** [comment]
**Issue List**
* https://github.com/getgauge/gauge/issues/892
