### ISSUE TITLE
Getting a null pointer exception while executing tests

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#868]
_From @sguptatw on November 20, 2017 13:50_

**Expected behavior**
Should be able to execute gauge tests

**Actual behavior**
Getting a null pointer exception
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x71fe1d]

goroutine 1 [running]:
github.com/getgauge/gauge/util.FindConceptFilesIn.func1(0xc04213c690, 0x28, 0x0, 0x0, 0xc042129500)
        src/github.com/getgauge/gauge/util/fileUtils.go:103 +0x2d
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir.func1(0xc04213c690, 0x28, 0x0, 0x0, 0xc29020, 0xc04213c6f0, 0x0, 0x0)
        src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:170 +0x71
path/filepath.walk(0xc0420fa940, 0x20, 0xc321a0, 0xc0421290e0, 0xc0420fa720, 0x0, 0x0)
        /usr/local/Cellar/go/1.8.3/libexec/src/path/filepath/path.go:372 +0x305
path/filepath.walk(0xc0420fa6e0, 0x1a, 0xc321a0, 0xc0421283c0, 0xc0420fa720, 0x0, 0x20)
        /usr/local/Cellar/go/1.8.3/libexec/src/path/filepath/path.go:376 +0x41b
path/filepath.Walk(0xc0420fa6e0, 0x1a, 0xc0420fa720, 0xc0420fa6e0, 0x1a)
        /usr/local/Cellar/go/1.8.3/libexec/src/path/filepath/path.go:398 +0x153
github.com/getgauge/gauge/vendor/github.com/getgauge/common.FindFilesInDir(0xc0420fa6e0, 0x1a, 0x9e17e0, 0x9e17d0, 0x0, 0x0, 0x9)
        src/github.com/getgauge/gauge/vendor/github.com/getgauge/common/common.go:177 +0xe9
github.com/getgauge/gauge/util.findFilesIn(0xc0420fa600, 0x1a, 0x9e17e0, 0x9e17d0, 0x1a, 0x0, 0x0)
        src/github.com/getgauge/gauge/util/fileUtils.go:83 +0x68
github.com/getgauge/gauge/util.FindConceptFilesIn(0xc0420fa600, 0x1a, 0xc0420fa600, 0x1a, 0x0)
        src/github.com/getgauge/gauge/util/fileUtils.go:108 +0x59
github.com/getgauge/gauge/util.GetConceptFiles(0x926bc0, 0x0, 0xc0420857d8)
        src/github.com/getgauge/gauge/util/fileUtils.go:175 +0x111
github.com/getgauge/gauge/parser.CreateConceptsDictionary(0xc0421281e0, 0x0)
        src/github.com/getgauge/gauge/parser/conceptParser.go:222 +0xcb
github.com/getgauge/gauge/parser.ParseConcepts(0xc0420e9b00, 0x0)
        src/github.com/getgauge/gauge/parser/parse.go:93 +0x29
github.com/getgauge/gauge/validation.ValidateSpecs(0xc04203b7c0, 0x1, 0x1, 0x0, 0x0)
        src/github.com/getgauge/gauge/validation/validate.go:189 +0x177
github.com/getgauge/gauge/execution.ExecuteSpecs(0xc04203b7c0, 0x1, 0x1, 0x0)
        src/github.com/getgauge/gauge/execution/execute.go:122 +0xb4
github.com/getgauge/gauge/cmd.execute(0xc04203b7c0, 0x1, 0x1)
        src/github.com/getgauge/gauge/cmd/run.go:110 +0x15c
github.com/getgauge/gauge/cmd.glob..func10(0xc5e380, 0xc04203b7c0, 0x1, 0x1)
        src/github.com/getgauge/gauge/cmd/run.go:50 +0xab
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0xc5e380, 0xc04203b780, 0x1, 0x1, 0xc5e380, 0xc04203b780)
        src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x241
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc5d280, 0xd, 0xc0420544e8, 0xc0420ce4b0)
        src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x340
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).Execute(0xc5d280, 0x0, 0x17)
        src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:685 +0x32
github.com/getgauge/gauge/cmd.Parse(0xc04201c000, 0xc04201c000)
        src/github.com/getgauge/gauge/cmd/cmd.go:97 +0x44
main.main()
```
**Steps to replicate**
* Checkout project https://github.com/getgauge/gauge-lsp-tests.git
* Add con.cpt under specs
```
# Concept13
* asdf234
```
* Execute the specs
```
gauge run specs
```
> This gives the error

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-20
Commit Hash: c49041d

Plugins
-------
js (2.0.3.nightly-2017-11-16)
```

_Copied from original issue: getgauge/gauge-vscode#47_

**Comment by nehashri** [comment]
@sguptatw please have a look at https://stackoverflow.com/questions/448438/windows-and-renaming-folders-the-con-issue. You can't create files named `con` in windows.
