### ISSUE TITLE
External CSV is not working when there is a data table inside a scenario

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge#875]
_From @osandadeshan on November 7, 2017 4:22_

[attachment.zip](https://github.com/getgauge/gauge-java/files/1448668/attachment.zip)

### External CSV should work when there is a data table inside a scenario
When there are many parameters in my method. The parameter count is dynamic. It will change according to the user. As the test data for that method I have input a csv. It should run row by row when it is executed.

### External CSV is not working when there is a data table inside a scenario
When there are many parameters in my method. The parameter count is dynamic. It will change according to the user. As the test data for that method I have input a csv. But It gives an error in Gauge.

### Steps to reproduce
1. Provide a data csv in the setup step.
2. Create a scenario.
3. Inside that scenario add a data table.
I have attached an screenshot of my spec file, .spec file and the csv file I used.
![capture](https://user-images.githubusercontent.com/9147189/32477013-3d9f65ec-c3a1-11e7-9ffd-4c4dcf5f4339.PNG)

### Gauge version
Gauge version: 0.9.3
Commit Hash: 724e6d3

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
java (0.6.5)
ruby (0.4.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

_Copied from original issue: getgauge/gauge-java#112_

**Comment by BugDiver** [comment]
_From @nehashri on November 7, 2017 4:32_

@osandadeshan can you give a sample step implementation and error you are facing?

**Comment by BugDiver** [comment]
_From @nehashri on November 7, 2017 6:3_

@osandadeshan I see you are trying to use values from csv in your datatable as such. 
```
Create Question Specification
======================
table: /resources/data_driven_test_csv/create_question.csv
Create a question
------------------
* When the user set the request attributes as follows
     |Attribute Value In JSON Template|Attribute Value To Be Set          |
     |----------------------------------|-------------------------------|
     |#creatorId                                       |<creatorId>                                 |

```
* `creatorId` is a dynamic parameter defined in csv /resources/data_driven_test_csv/create_question.csv

Tables in a step do not accept dynamic parameter values.
This feature is not yet supported in gauge.

**Comment by BugDiver** [comment]
_From @osandadeshan on November 7, 2017 6:26_

Below is the error log....


```
"C:\Program Files\Gauge\bin\gauge.exe" run --machine-readable --hide-suggestion --simple-console "C:/Users/UnimaOs/IdeaProjects/Smart-Flashcards-API-Testing-Framework/specs/07. Create Question.spec:20"
Testing started at 11:55 AM ...
Accessing an invalid parameter (creatorId)
goroutine 1 [running]:
runtime/debug.Stack(0xc042030e68, 0x9a57c0, 0xc04212a8e0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/debug/stack.go:24 +0xae
github.com/getgauge/gauge/execution.recoverPanic()
	src/github.com/getgauge/gauge/execution/execute.go:130 +0x5e
panic(0x9a57c0, 0xc04212a8e0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x291
github.com/getgauge/gauge/gauge.(*ArgLookup).GetArg(0xc042252fe0, 0xc04232c5e1, 0x9, 0xc04209c400)
	src/github.com/getgauge/gauge/gauge/arg.go:68 +0x179
github.com/getgauge/gauge/parser.(*ParamResolver).createProtoStepTable(0xc042031198, 0xc042416490, 0xc042252fe0, 0xe14430)
	src/github.com/getgauge/gauge/parser/resolver.go:104 +0x2d4
github.com/getgauge/gauge/parser.(*ParamResolver).GetResolvedParams(0xc042031198, 0xc0420df3b0, 0x0, 0xc042252fe0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/parser/resolver.go:79 +0x345
github.com/getgauge/gauge/execution.(*specExecutor).resolveToProtoStepItem(0xc042200900, 0xc0420df3b0, 0x7e29c7)
	src/github.com/getgauge/gauge/execution/specExecutor.go:188 +0x85
github.com/getgauge/gauge/execution.(*specExecutor).resolveToProtoItem(0xc042200900, 0xdaa780, 0xc0420df3b0, 0x0)
	src/github.com/getgauge/gauge/execution/specExecutor.go:154 +0x11b
github.com/getgauge/gauge/execution.(*specExecutor).resolveItems(0xc042200900, 0xc0421f8800, 0x5, 0x8, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/execution/specExecutor.go:140 +0xfc
github.com/getgauge/gauge/execution.(*specExecutor).addAllItemsForScenarioExecution(0xc042200900, 0xc04218b340, 0xc042004358)
	src/github.com/getgauge/gauge/execution/specExecutor.go:317 +0x29e
github.com/getgauge/gauge/execution.(*specExecutor).executeScenario(0xc042200900, 0xc04218b340, 0x8f1c7e)
	src/github.com/getgauge/gauge/execution/specExecutor.go:305 +0x148
github.com/getgauge/gauge/execution.(*specExecutor).executeScenarios(0xc042200900, 0xc042132390, 0x1, 0x1, 0xc0425de500, 0x0, 0xc0420386c0)
	src/github.com/getgauge/gauge/execution/specExecutor.go:292 +0xb1
github.com/getgauge/gauge/execution.(*specExecutor).execute(0xc042200900, 0x10101, 0xc0422c0030)
	src/github.com/getgauge/gauge/execution/specExecutor.go:103 +0x496
github.com/getgauge/gauge/execution.(*simpleExecution).executeSpecs(0xc0425de070, 0xc04214c360, 0xbe78725478cc161c, 0x44034634c, 0xdf62c0)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:129 +0x1a8
github.com/getgauge/gauge/execution.(*simpleExecution).execute(0xc0425de070)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:91 +0x123
github.com/getgauge/gauge/execution.(*simpleExecution).run(0xc0425de070, 0xdaa440)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:70 +0x40
github.com/getgauge/gauge/execution.ExecuteSpecs(0xc04212db80, 0x1, 0x4, 0x0)
	src/github.com/getgauge/gauge/execution/execute.go:125 +0x927
github.com/getgauge/gauge/cmd.execute(0xc04212db80, 0x1, 0x4)
	src/github.com/getgauge/gauge/cmd/run.go:108 +0x159
github.com/getgauge/gauge/cmd.glob..func11(0xdecf80, 0xc04212db80, 0x1, 0x4)
	src/github.com/getgauge/gauge/cmd/run.go:50 +0x9e
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0xdecf80, 0xc04212db40, 0x4, 0x4, 0xdecf80, 0xc04212db40)
	src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x244
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xdebc60, 0xc042183220, 0x0, 0xc04205bde8)
	src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x305
github.com/getgauge/gauge/cmd.Parse(0xa95cae, 0xa, 0x0)
	src/github.com/getgauge/gauge/cmd/cmd.go:107 +0x93
main.main()
	src/github.com/getgauge/gauge/gauge.go:87 +0x6a


Process finished with exit code 1
"C:\Program Files\Gauge\bin\gauge.exe" run --machine-readable --hide-suggestion --simple-console "C:/Users/UnimaOs/IdeaProjects/Smart-Flashcards-API-Testing-Framework/specs/07. Create Question.spec:20"
Testing started at 11:55 AM ...
Accessing an invalid parameter (creatorId)
goroutine 1 [running]:
runtime/debug.Stack(0xc042030e68, 0x9a57c0, 0xc04212a8e0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/debug/stack.go:24 +0xae
github.com/getgauge/gauge/execution.recoverPanic()
	src/github.com/getgauge/gauge/execution/execute.go:130 +0x5e
panic(0x9a57c0, 0xc04212a8e0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x291
github.com/getgauge/gauge/gauge.(*ArgLookup).GetArg(0xc042252fe0, 0xc04232c5e1, 0x9, 0xc04209c400)
	src/github.com/getgauge/gauge/gauge/arg.go:68 +0x179
github.com/getgauge/gauge/parser.(*ParamResolver).createProtoStepTable(0xc042031198, 0xc042416490, 0xc042252fe0, 0xe14430)
	src/github.com/getgauge/gauge/parser/resolver.go:104 +0x2d4
github.com/getgauge/gauge/parser.(*ParamResolver).GetResolvedParams(0xc042031198, 0xc0420df3b0, 0x0, 0xc042252fe0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/parser/resolver.go:79 +0x345
github.com/getgauge/gauge/execution.(*specExecutor).resolveToProtoStepItem(0xc042200900, 0xc0420df3b0, 0x7e29c7)
	src/github.com/getgauge/gauge/execution/specExecutor.go:188 +0x85
github.com/getgauge/gauge/execution.(*specExecutor).resolveToProtoItem(0xc042200900, 0xdaa780, 0xc0420df3b0, 0x0)
	src/github.com/getgauge/gauge/execution/specExecutor.go:154 +0x11b
github.com/getgauge/gauge/execution.(*specExecutor).resolveItems(0xc042200900, 0xc0421f8800, 0x5, 0x8, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/execution/specExecutor.go:140 +0xfc
github.com/getgauge/gauge/execution.(*specExecutor).addAllItemsForScenarioExecution(0xc042200900, 0xc04218b340, 0xc042004358)
	src/github.com/getgauge/gauge/execution/specExecutor.go:317 +0x29e
github.com/getgauge/gauge/execution.(*specExecutor).executeScenario(0xc042200900, 0xc04218b340, 0x8f1c7e)
	src/github.com/getgauge/gauge/execution/specExecutor.go:305 +0x148
github.com/getgauge/gauge/execution.(*specExecutor).executeScenarios(0xc042200900, 0xc042132390, 0x1, 0x1, 0xc0425de500, 0x0, 0xc0420386c0)
	src/github.com/getgauge/gauge/execution/specExecutor.go:292 +0xb1
github.com/getgauge/gauge/execution.(*specExecutor).execute(0xc042200900, 0x10101, 0xc0422c0030)
	src/github.com/getgauge/gauge/execution/specExecutor.go:103 +0x496
github.com/getgauge/gauge/execution.(*simpleExecution).executeSpecs(0xc0425de070, 0xc04214c360, 0xbe78725478cc161c, 0x44034634c, 0xdf62c0)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:129 +0x1a8
github.com/getgauge/gauge/execution.(*simpleExecution).execute(0xc0425de070)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:91 +0x123
github.com/getgauge/gauge/execution.(*simpleExecution).run(0xc0425de070, 0xdaa440)
	src/github.com/getgauge/gauge/execution/simpleExecution.go:70 +0x40
github.com/getgauge/gauge/execution.ExecuteSpecs(0xc04212db80, 0x1, 0x4, 0x0)
	src/github.com/getgauge/gauge/execution/execute.go:125 +0x927
github.com/getgauge/gauge/cmd.execute(0xc04212db80, 0x1, 0x4)
	src/github.com/getgauge/gauge/cmd/run.go:108 +0x159
github.com/getgauge/gauge/cmd.glob..func11(0xdecf80, 0xc04212db80, 0x1, 0x4)
	src/github.com/getgauge/gauge/cmd/run.go:50 +0x9e
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0xdecf80, 0xc04212db40, 0x4, 0x4, 0xdecf80, 0xc04212db40)
	src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x244
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xdebc60, 0xc042183220, 0x0, 0xc04205bde8)
	src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x305
github.com/getgauge/gauge/cmd.Parse(0xa95cae, 0xa, 0x0)
	src/github.com/getgauge/gauge/cmd/cmd.go:107 +0x93
main.main()
	src/github.com/getgauge/gauge/gauge.go:87 +0x6a


Process finished with exit code 1
```

**Comment by BugDiver** [comment]
_From @osandadeshan on November 7, 2017 6:28_

Please add that feature as well since it will much needed for Quality engineers when maintaining test data sets.

Thanks.

**Comment by BugDiver** [comment]
_From @zabil on November 7, 2017 9:30_

Thanks for the suggestion, will take look at this. 
Not easy to implement but we see the use case.

**Comment by BugDiver** [comment]
_From @osandadeshan on November 7, 2017 9:43_

@zabil @nehashri 
Thanks. Actually It will be a mandatory need in testing aspect. Because it will majorly helps to do data driven tests very easily for the dynamic count of parameters.
I am using Gauge as the test automation framework since 2016 (Almost 2 years now). I have used this for Web, Mobile and API test automation. This was a feature which I needed from the initial stage.
 
Hope you'll understand this requirement.

Thank You.

**Comment by BugDiver** [comment]
_From @nehashri on November 7, 2017 10:29_

@osandadeshan This seems to be a bug in the implementation.
A workaround seems to be to use one of the csv table headers in the context steps. 
Example : 
```
Specification Heading
=====================
table: some-data.csv

* Vowels in English language are "aeiou".
* Print <word>
Vowel counts in single word
---------------------------
* Almost all words have vowels 

   |Word  |Vowel Count|
   |------|-----------|
   |<word>|<vowels>   |

```
Executing the spec with the dummy step `Print <word>` seems to work. 
But removing the step `Print <word>` seems to fail.

**Comment by BugDiver** [comment]
_From @osandadeshan on November 7, 2017 11:1_

Thanks @nehashri it worked well after the workaround. Please fix this issue.

Thanks again for the help

**Comment by BugDiver** [comment]
Fix should be available in nightly >=   24 -11-  2017
