### ISSUE TITLE
LSP Shut down method not responding

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#915]
_From @sguptatw on January 12, 2018 7:51_

**Expected behavior**
Shut down should respond after processing

**Actual behavior**
Shut down does not respond

**Steps to replicate**
* Run LSP tests https://github.com/getgauge/gauge-lsp-tests

**Version**
```
Gauge version: 0.9.8
Commit Hash: 1c656c4

Plugins
-------
html-report (4.0.4)
js (2.1.1)
```

_Copied from original issue: getgauge/taiko#23_

**Comment by sguptatw** [comment]
**Observation**
Shutdown and exit LSP requests are honored a couple of times before it stops responding.
Refer - https://build.getgauge.io/go/tab/build/detail/JS-LSP-Tests/232/tests/1/linux

**Comment by sriv** [comment]
Logs from https://build.getgauge.io/go/tab/build/detail/JS-LSP-Tests/232/tests/1/linux

```
[go] Job Started: 2018-01-12 07:44:06 UTC

[go] Start to prepare JS-LSP-Tests/232/tests/1/linux on dac910975854 [/go]
[go] Cleaning working directory "/go/pipelines/JS-LSP-Tests" since stage is configured to clean working directory
[go] Start to update materials.

[go] Start updating files at revision 3661905f4fcfcf27b619adfe44701ad5be3b183e from https://github.com/getgauge/gauge-lsp-tests
STDERR: Cloning into '/go/pipelines/JS-LSP-Tests'...
[GIT] Fetching changes
[GIT] Performing git gc
[GIT] Reset working directory pipelines/JS-LSP-Tests
[GIT] Cleaning all unversioned files in working copy
[GIT] Cleaning submodule configurations in .git/config
[GIT] Updating working copy to revision 3661905f4fcfcf27b619adfe44701ad5be3b183e
HEAD is now at 3661905 message for analysis
[GIT] Removing modified files in submodules
[GIT] Cleaning all unversioned files in working copy
[go] Done.

[go] overriding environment variable 'GO_SERVER_URL' with value '<redacted>'
[go] setting environment variable 'GO_TRIGGER_USER' to value 'changes'
[go] setting environment variable 'GO_PIPELINE_NAME' to value 'JS-LSP-Tests'
[go] setting environment variable 'GO_PIPELINE_COUNTER' to value '232'
[go] setting environment variable 'GO_PIPELINE_LABEL' to value '232'
[go] setting environment variable 'GO_STAGE_NAME' to value 'tests'
[go] setting environment variable 'GO_STAGE_COUNTER' to value '1'
[go] setting environment variable 'GO_JOB_NAME' to value 'linux'
[go] setting environment variable 'GO_REVISION' to value '3661905f4fcfcf27b619adfe44701ad5be3b183e'
[go] setting environment variable 'GO_TO_REVISION' to value '3661905f4fcfcf27b619adfe44701ad5be3b183e'
[go] setting environment variable 'GO_FROM_REVISION' to value '0cd7362d6d5b1112e6134ceb497343202a7b098e'
[go] setting environment variable 'GO_DEPENDENCY_LABEL_GAUGE_PACKAGE' to value '563'
[go] setting environment variable 'GO_DEPENDENCY_LOCATOR_GAUGE_PACKAGE' to value 'Gauge-Package/563/sign/1'
[go] setting environment variable 'GO_DEPENDENCY_LABEL_JS_BUILD' to value '44'
[go] setting environment variable 'GO_DEPENDENCY_LOCATOR_JS_BUILD' to value 'JS-Build/44/package/1'
[go] setting environment variable 'GO_DEPENDENCY_LABEL_HTML_PACKAGE' to value '270'
[go] setting environment variable 'GO_DEPENDENCY_LOCATOR_HTML_PACKAGE' to value 'HTML_Report/270/package/1'
[go] setting environment variable 'GOPATH' to value '/tmp'
[go] setting environment variable 'GOBIN' to value '/tmp/bin'
[go] setting environment variable 'GAUGE_PREFIX' to value '/tmp'
[go] setting environment variable 'GAUGE_ROOT' to value '/tmp'
[go] setting environment variable 'GAUGE_TELEMETRY_ENABLED' to value 'false'

[go] Start to build JS-LSP-Tests/232/tests/1/linux on dac910975854 [/go]
[go] Task: fetch artifact [test_installers/gauge-linux.x86_64.zip] => [] from [Gauge-Package/sign/windows]took: 0.220s
[go] Fetching artifact [test_installers/gauge-linux.x86_64.zip] from [Gauge-Package/563/sign/1/windows]
[go] Saved artifact to [pipelines/JS-LSP-Tests/gauge-linux.x86_64.zip] after verifying the integrity of its contents.
[go] Task status: passed, took: 0.220s
[go] Task: /bin/sh -c "mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-linux.x86_64.zip -d $GAUGE_ROOT/bin"took: 0.147s
Archive:  gauge-linux.x86_64.zip
  inflating: /tmp/bin/gauge          
[go] Task status: passed, took: 0.147s
[go] Task: /bin/sh -c "($GAUGE_PREFIX/bin/gauge uninstall js;$GAUGE_PREFIX/bin/gauge uninstall html-report;$GAUGE_PREFIX/bin/gauge uninstall xml-report)"took: 0.69s
Successfully uninstalled plugin js 2.1.1.
Successfully uninstalled plugin html-report 4.0.4.
Plugin xml-report not found.
[go] Task status: passed, took: 0.69s
[go] Task: fetch artifact [deploy] => [] from [JS-Build/package/package]took: 0.73s
[go] Fetching artifact [deploy] from [JS-Build/44/package/1/package]
[go] Saved artifact to [pipelines/JS-LSP-Tests] after verifying the integrity of its contents.
[go] Task status: passed, took: 0.73s
[go] Task: /bin/sh -c "(version=$(ls gauge-js-*.zip | sed \"s/^gauge-js-\([^;]*\).zip/\1/\"); $GAUGE_PREFIX/bin/gauge install js -f gauge-js-$version.zip)"took: 0.312s
Successfully installed plugin 'js'.
[go] Task status: passed, took: 0.312s
[go] Task: fetch artifact [deploy] => [] from [HTML_Report/package/package]took: 0.929s
[go] Fetching artifact [deploy] from [HTML_Report/270/package/1/package]
[go] Saved artifact to [pipelines/JS-LSP-Tests] after verifying the integrity of its contents.
[go] Task status: passed, took: 0.929s
[go] Task: /bin/sh -c "(version=$(ls html-report-*-linux.x86_64.zip | sed \"s/^html-report-\([^;]*\)-linux.x86_64.zip/\1/\"); $GAUGE_PREFIX/bin/gauge install html-report -f html-report-$version-linux.x86_64.zip)"took: 0.237s
Successfully installed plugin 'html-report'.
[go] Task status: passed, took: 0.237s
[go] Task: npm installtook: 0.694s
added 2 packages in 0.279s
[go] Task status: passed, took: 0.694s
[go] Task: /bin/sh -c "($GAUGE_PREFIX/bin/gauge version)"took: 0.14s
Gauge version: 0.9.8
Commit Hash: 1c656c4

Plugins
-------
html-report (4.0.4)
js (2.1.1)
screenshot (0.0.1)
[go] Task status: passed, took: 0.14s
[go] Task: /bin/sh -c "PATH=$GAUGE_PREFIX/bin:$PATH gauge run specs"
[ValidationError] /godata/pipelines/JS-LSP-Tests/specs/diagnostics/format.spec:11 Step implementation not found => 'Feature yet to be implemented'
Add the following missing implementations to fix `Step implementation not found` errors.

step("Feature yet to be implemented", async function() {
	throw 'Unimplemented Step';
});
Unable to start plugin xml-report. Plugin xml-report is not installed. To install, run `gauge install xml-report`.
# Parameter code completion
  ## Static Parameter list for codecomplete	request initialize params 
notification initialized
 ?notification textDocument/didOpen
 ?request textDocument/completion
verification complete
 ?shutDown
request shutdown params 
notification exit
 ?
  ## Dynamic Parameter list for codecomplete	request initialize params 
notification initialized
 ?notification textDocument/didOpen
 ?request textDocument/completion
verification complete
 ?shutDown
request shutdown params 
notification exit
 ?
# Steps code completion
  ## Steps list for codecomplete	request initialize params 
notification initialized
 ?notification textDocument/didOpen
 ?request textDocument/completion
verification complete
 ?shutDown
request shutdown params 
 ?
        Failed Step: stop gauge daemon
        Specification: specs/codecompletion/steps.spec:37
        Error Message: Error: Timed out
        Stacktrace: 
        Error: Timed out
            at Timeout.<anonymous> (/home/go/.gauge/plugins/js/2.1.1/src/test.js:42:23)
            at ontimeout (timers.js:478:11)
            at tryOnTimeout (timers.js:302:5)
            at Timer.listOnTimeout (timers.js:262:5)
  ## Should list steps implemented but not used	request initialize params 
notification initialized
 ?notification textDocument/didOpen
 ?request textDocument/completion
verification complete
 ?shutDown
request shutdown params 
```

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 15/01/18
