### ISSUE TITLE
Already disposed: Project (Disposed) hammurabi_2.11.0-M3

### ISSUE THREAD

**Issue by njacobs5074** [getgauge/gauge#92]
Happened shortly after I loaded a new Scala/SBT project - I was not actively using the editor when it happened.  Will restart IntelliJ and see if it continues.
Gauge version: 0.0.3
IntelliJ version: 14.0.3

Stack trace:
````
Already disposed: Project (Disposed) hammurabi_2.11.0-M3
java.lang.AssertionError: Already disposed: Project (Disposed) hammurabi_2.11.0-M3
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:191)
	at com.intellij.psi.PsiManager.getInstance(PsiManager.java:39)
	at com.intellij.psi.impl.smartPointers.SelfElementInfo$1.compute(SelfElementInfo.java:238)
	at com.intellij.psi.impl.smartPointers.SelfElementInfo$1.compute(SelfElementInfo.java:224)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at com.intellij.psi.impl.smartPointers.SelfElementInfo.restoreFileFromVirtual(SelfElementInfo.java:224)
	at com.intellij.psi.impl.smartPointers.SelfElementInfo.restoreFile(SelfElementInfo.java:174)
	at com.intellij.psi.impl.smartPointers.AnchorElementInfo.restoreElement(AnchorElementInfo.java:62)
	at com.intellij.psi.impl.smartPointers.AnchorElementInfo.fastenBelt(AnchorElementInfo.java:105)
	at com.intellij.psi.impl.smartPointers.SmartPsiElementPointerImpl.fastenBelt(SmartPsiElementPointerImpl.java:177)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.fastenBelts(SmartPointerManagerImpl.java:67)
	at com.intellij.psi.impl.PsiDocumentManagerBase.beforeDocumentChange(PsiDocumentManagerBase.java:614)
	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy22.beforeDocumentChange(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:746)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:714)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:498)
	at com.intellij.openapi.editor.actions.EnterAction.insertNewLineAtCaret(EnterAction.java:109)
	at com.intellij.openapi.editor.actions.EnterAction$Handler.executeWriteAction(EnterAction.java:50)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:220)
	at com.intellij.codeInsight.editorActions.EnterHandler.a(EnterHandler.java:152)
	at com.intellij.codeInsight.editorActions.EnterHandler.access$000(EnterHandler.java:53)
	at com.intellij.codeInsight.editorActions.EnterHandler$1.run(EnterHandler.java:75)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:110)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:107)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:72)
	at com.thoughtworks.gauge.GaugeEnterHandler.executeWriteAction(GaugeEnterHandler.java:34)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:220)
	at com.intellij.codeInsight.editorActions.EnterHandler.a(EnterHandler.java:152)
	at com.intellij.codeInsight.editorActions.EnterHandler.access$000(EnterHandler.java:53)
	at com.intellij.codeInsight.editorActions.EnterHandler$1.run(EnterHandler.java:75)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:110)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:107)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:72)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:220)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:204)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:36)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:201)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:355)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:435)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:346)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:97)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:108)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:82)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:614)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:663)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:513)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:546)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
````

**Comment by sriv** [comment]
Could you also try with the latest Gauge? We've released 0.0.4 with some fixes. There should be an update to the Intellij plugin as well.

**Comment by prateekbaheti** [comment]
Did you have multiple projects open in intellij ? Was the project/module ```hammurabi_2.11.0-M3``` already open when the error was thrown ?

**Comment by prateekbaheti** [comment]
Potential cause could be this [issue](https://github.com/getgauge/Intellij-Plugin/issues/37).

**Comment by njacobs5074** [comment]
Hi Prateek,

Yes the project was open - I don't think I had multiple projects open,
though.  I'll update the plugin and let you know if it happens again.  It's
definitely an intermittent issue.

Thanks,

Nick

On Fri, Feb 20, 2015 at 4:13 PM, Prateek <notifications@github.com> wrote:

> Did you have multiple projects open in intellij ? Was the project/module
> hammurabi_2.11.0-M3 already open when the error was thrown ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/92#issuecomment-75264344>.
>



-- 
Phone: +44 7463 853 913
LinkedIn: http://uk.linkedin.com/in/njacobs5074
Twitter: @njacobs5074

**Comment by deepthigc** [comment]
Closing this for now. We can reopen this if we see it happen again.
