### ISSUE TITLE
Should not get segmentation violation error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#938]
**Actual behavior**
Getting the following error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14876ad]

goroutine 393 [running]:
github.com/getgauge/gauge/api/lang.createValidationDiagnostics(0xc4201f1500, 0x1, 0x1, 0xc4200121e0)
	src/github.com/getgauge/gauge/api/lang/diagnostics.go:83 +0x1dd
github.com/getgauge/gauge/api/lang.validateSpecs(0xc420374f80, 0xc4200121e0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/diagnostics.go:118 +0x20c
github.com/getgauge/gauge/api/lang.getDiagnostics(0x8, 0x15fec28, 0x18b9368)
	src/github.com/getgauge/gauge/api/lang/diagnostics.go:73 +0x86
github.com/getgauge/gauge/api/lang.publishDiagnostics(0x1869800, 0xc42007a3d8, 0x1867900, 0xc4203dd2c0)
	src/github.com/getgauge/gauge/api/lang/diagnostics.go:52 +0x9f
created by github.com/getgauge/gauge/api/lang.documentOpened
	src/github.com/getgauge/gauge/api/lang/server.go:236 +0x212
```

**Version**
```
auge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
dotnet (0.0.1.nightly-2018-02-05)
html-report (4.0.4.nightly-2018-01-11)
js (2.1.1.nightly-2018-02-05)
ruby (0.4.3.nightly-2018-02-07)
xml-report (0.2.1.nightly-2017-10-26)
```

Bug on story https://github.com/getgauge/gauge-vscode/issues/108

**Comment by Apoorva-GA** [comment]
@sguptatw Are there any steps to replicate this error?

**Comment by sguptatw** [comment]
**Steps to replicate**
* Create a gauge-python project
* Create a new spec blah.spec
```
# Something
## Something else
* unimplemented step
```
* Generate stub implementation for this step
* Goto example.spec
> Note the above error occurs

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 15-02-2018

**Comment by sguptatw** [comment]
For the same steps mentioned above getting the following error

<img width="907" alt="screen shot 2018-02-16 at 6 42 05 pm" src="https://user-images.githubusercontent.com/6310197/36309087-2737209a-1349-11e8-94bd-b181d19c5f5c.png">

**Comment by sriv** [comment]
is this still valid?

**Comment by BugDiver** [comment]
The error `use of closed network connection` is related to `gauge-python` and getting tracked as https://github.com/getgauge/gauge-python/issues/42
