### ISSUE TITLE
Segmentation violation while refactoring

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#943]
**Expected behavior**
Should not get segmentation violation while refactoring

**Actual behavior**
Getting the following error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13eda8c]

goroutine 67 [running]:
github.com/getgauge/gauge/refactor.(*rephraseRefactorer).getStepNameFromRunner(0xc420082e40, 0x0, 0x0, 0x18bd6c0, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/refactor/refactor.go:404 +0xbc
github.com/getgauge/gauge/refactor.(*rephraseRefactorer).refactorStepImplementations(0xc420082e40, 0xc420469900, 0xc420014da0)
	src/github.com/getgauge/gauge/refactor/refactor.go:254 +0x186
github.com/getgauge/gauge/refactor.(*rephraseRefactorer).getRefactoringChangesFor(0xc420082e40, 0xc4201d8610, 0x1, 0x1, 0xc420014da0, 0x1)
	src/github.com/getgauge/gauge/refactor/refactor.go:243 +0x6d
github.com/getgauge/gauge/refactor.GetRefactoringChanges(0xc4204d8692, 0x27, 0xc4204d8152, 0x26, 0x0, 0x0, 0xc420469c20, 0x1, 0x1, 0x200001)
	src/github.com/getgauge/gauge/refactor/refactor.go:162 +0x32c
github.com/getgauge/gauge/api/lang.rename(0xc42014c320, 0xc42007e3d8, 0x186b9c0, 0xc4201b2360, 0x0)
	src/github.com/getgauge/gauge/api/lang/rename.go:42 +0x328
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0x18bd6c0, 0x186d8c0, 0xc42007e3d8, 0x186b9c0, 0xc4201b2360, 0xc42014c320, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:162 +0xab7
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0x18bd6c0, 0x186d8c0, 0xc42007e3d8, 0xc4201b2360, 0xc42014c320, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:111 +0x66
github.com/getgauge/gauge/api/lang.(*LangHandler).(github.com/getgauge/gauge/api/lang.handle)-fm(0x186d8c0, 0xc42007e3d8, 0xc4201b2360, 0xc42014c320, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:103 +0x52
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc4201b43e0, 0x186d8c0, 0xc42007e3d8, 0xc4201b2360, 0xc42014c320)
	src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x6f
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	src/github.com/getgauge/gauge/api/lang/server.go:107 +0x6b
[Info  - 17:47:33] Connection to server got closed. Server will restart.
[Error - 17:47:33] Request textDocument/rename failed.
Error: Connection got disposed.
	at Object.dispose (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/sswaroop/.vscode/extensions/getgauge.gauge-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:135:36)
[Error - 17:47:33] Request textDocument/codeLens failed.
  Message: failed to parse specification /Users/sswaroop/work/js/basic1/specs/example.spec
  Code: 0 
```
**Steps to replicate**
* Create a new js project
* Refactor step `* Vowels in English language are "aeiou".` to ``
* No errors are displayed
* Now try refactoring it to `* Vowels in English language are "aeiou"`
> The above error occurs

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-15
Commit Hash: dfbaee0

Plugins
-------
js (2.1.1.nightly-2018-02-14)
```

**Comment by Apoorva-GA** [comment]
Not replicable with latest nightly.
