### ISSUE TITLE
Should not get exception during LSP `autocomplete` call

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#994]
**Expected behavior**
Should not get exception during LSP `autocomplete` call

**Actual behavior**
Getting the following exception
```
textDocument/completion: runtime error: index out of range
goroutine 28 [running]:
runtime/debug.Stack(0xc42006d830, 0x9476c0, 0xc9ad00)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/debug/stack.go:24 +0x79
github.com/getgauge/gauge/api/lang.recoverPanic(0xc4203b6000)
	src/github.com/getgauge/gauge/api/lang/server.go:294 +0x57
panic(0x9476c0, 0xc9ad00)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/getgauge/gauge/api/lang.(*files).line(0xca7040, 0xc4204a0060, 0x5a, 0x5, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/file.go:49 +0xec
github.com/getgauge/gauge/api/lang.getLine(0xc4204a0060, 0x5a, 0x5, 0x8fb900, 0xc4204662c0)
	src/github.com/getgauge/gauge/api/lang/file.go:86 +0x4b
github.com/getgauge/gauge/api/lang.completion(0xc4203b6000, 0x17, 0x9eda19, 0x17, 0xffffffffffffff01)
	src/github.com/getgauge/gauge/api/lang/completion.go:57 +0xdf
github.com/getgauge/gauge/api/lang.(*LangHandler).Handle(0xcc4b78, 0xc746e0, 0xc4200164d0, 0xc727e0, 0xc4201e97a0, 0xc4203b6000, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:134 +0x24a7
github.com/getgauge/gauge/api/lang.(*LangHandler).handle(0xcc4b78, 0xc746e0, 0xc4200164d0, 0xc4201e97a0, 0xc4203b6000, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:86 +0xc3
github.com/getgauge/gauge/api/lang.(*LangHandler).(github.com/getgauge/gauge/api/lang.handle)-fm(0xc746e0, 0xc4200164d0, 0xc4201e97a0, 0xc4203b6000, 0x0, 0x0, 0x0, 0x0)
	src/github.com/getgauge/gauge/api/lang/server.go:77 +0x52
github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc420374070, 0xc746e0, 0xc4200164d0, 0xc4201e97a0, 0xc4203b6000)
	src/github.com/getgauge/gauge/vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x6f
created by github.com/getgauge/gauge/api/lang.lspHandler.Handle
	src/github.com/getgauge/gauge/api/lang/server.go:81 +0x6b
```

**Steps to replicate**
* Gauge LSP tests on Linux with no-working directory
> Refer the [CI pipeline](https://build.getgauge.io/go/tab/build/detail/JS-LSP-Tests/398/tests/1/linux-js-no-wd). The [logs for this run](https://build.getgauge.io/go/files/JS-LSP-Tests/398/tests/1/linux-js-no-wd/logs/logs/lsp-tests/Should+list+steps+implemented+but+unused+steps/lsp.log)

**Version**
```
Gauge version: 0.9.8
Commit Hash: b79de74

Plugins
-------
js (2.2.0)
```

**Comment by nehashri** [comment]
should be available in gauge nightly >= 16-4-18
