### ISSUE TITLE
Failed to start gauge API

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#995]
**Expected behavior**
Should not get error while running gauge specs

**Actual behavior**
Getting the error
```
Failed while loading proto file.
 { Error: ENOENT: no such file or directory, stat '/Users/vagrant/go-agent-17.4.0/pipelines/python-lsp-tests/reports/html-report/html-report'
    at Object.fs.statSync (fs.js:972:11)
    at /private/tmp/plugins/js/2.1.0/src/file-util.js:16:21
    at Array.forEach (<anonymous>)
    at walk (/private/tmp/plugins/js/2.1.0/src/file-util.js:14:25)
    at /private/tmp/plugins/js/2.1.0/src/file-util.js:20:26
    at Array.forEach (<anonymous>)
    at walk (/private/tmp/plugins/js/2.1.0/src/file-util.js:14:25)
    at /private/tmp/plugins/js/2.1.0/src/file-util.js:20:26
    at Array.forEach (<anonymous>)
    at walk (/private/tmp/plugins/js/2.1.0/src/file-util.js:14:25)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/vagrant/go-agent-17.4.0/pipelines/python-lsp-tests/reports/html-report/html-report' }
Error ----------------------------------

Failed to start gauge API: Timed out connecting to 127.0.0.1:61363

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	darwin, 0.9.8, 5df9e12
	html-report (4.0.4), java (0.6.6), js (2.1.0), python (0.2.6), screenshot (0.0.1), xml-report (0.2.1)
```
**Observed on**
* OSx CI pipeline of LSP Tests
https://build.getgauge.io/go/tab/build/detail/python-lsp-tests/92/lsp-tests/1/osx

**Version**
```
darwin, 0.9.8, 5df9e12
	html-report (4.0.4), java (0.6.6), js (2.1.0), python (0.2.6), screenshot (0.0.1), xml-report (0.2.1)
```

**Comment by BugDiver** [comment]
looks related to https://github.com/getgauge/gauge-js/issues/114. Please verify with latest nightlies.
